// Code generated by goplus from continuation.gp. DO NOT EDIT.
//goplus:v v0.28.0

package vm

import (
	"fmt"
	"math"
	"math/big"
	"time"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/term"
)

type VMReductionBudget struct {
	value int
}

type ExecutionProgress struct {
	Reductions        int
	Instructions      int
	TotalInstructions int
}

//goplus:enum ExecutionSlice
type ExecutionSlice interface{ isExecutionSlice() }

//goplus:variant (ExecutionSlice) ExecutionSuspended(Progress ExecutionProgress)
type ExecutionSuspended struct {
	Progress ExecutionProgress
}

func (ExecutionSuspended) isExecutionSlice() {}

//goplus:variant (ExecutionSlice) ExecutionWaiting(Progress ExecutionProgress)
type ExecutionWaiting struct {
	Progress ExecutionProgress
}

func (ExecutionWaiting) isExecutionSlice() {}

//goplus:variant (ExecutionSlice) ExecutionCompleted(Value term.Term, Progress ExecutionProgress)
type ExecutionCompleted struct {
	Value    term.Term
	Progress ExecutionProgress
}

func (ExecutionCompleted) isExecutionSlice() {}

//goplus:variant (ExecutionSlice) ExecutionRaised(Class term.Term, Reason term.Term, Progress ExecutionProgress)
type ExecutionRaised struct {
	Class    term.Term
	Reason   term.Term
	Progress ExecutionProgress
}

func (ExecutionRaised) isExecutionSlice() {}

// ExecutionSliceCases selects one handler per ExecutionSlice variant for ExecutionSliceFold.
type ExecutionSliceCases[R any] struct {
	ExecutionSuspended func(Progress ExecutionProgress) R
	ExecutionWaiting   func(Progress ExecutionProgress) R
	ExecutionCompleted func(Value term.Term, Progress ExecutionProgress) R
	ExecutionRaised    func(Class term.Term, Reason term.Term, Progress ExecutionProgress) R
}

// ExecutionSliceFold reduces ExecutionSlice by one-level case analysis.
func ExecutionSliceFold[R any](e ExecutionSlice, cs ExecutionSliceCases[R]) R {
	switch m := any(e).(type) {
	case ExecutionSuspended:
		return cs.ExecutionSuspended(m.Progress)
	case ExecutionWaiting:
		return cs.ExecutionWaiting(m.Progress)
	case ExecutionCompleted:
		return cs.ExecutionCompleted(m.Value, m.Progress)
	case ExecutionRaised:
		return cs.ExecutionRaised(m.Class, m.Reason, m.Progress)
	default:
		panic("goplus: impossible enum value in ExecutionSliceFold")
	}
}

// ExecutionSliceEqOverrides carries optional per-variant hooks for ExecutionSliceEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ExecutionSliceEqOverrides struct {
	ExecutionSuspended func(x, y ExecutionSuspended) (eq, handled bool)
	ExecutionWaiting   func(x, y ExecutionWaiting) (eq, handled bool)
	ExecutionCompleted func(x, y ExecutionCompleted) (eq, handled bool)
	ExecutionRaised    func(x, y ExecutionRaised) (eq, handled bool)
}

// ExecutionSliceEqualWith reports structural equality of a and b under ov.
func ExecutionSliceEqualWith(a, b ExecutionSlice, ov ExecutionSliceEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ExecutionSuspended:
		y, ok := any(b).(ExecutionSuspended)
		if !ok {
			return false
		}
		if ov.ExecutionSuspended != nil {
			if eq, handled := ov.ExecutionSuspended(x, y); handled {
				return eq
			}
		}
		if x.Progress != y.Progress {
			return false
		}
		return true
	case ExecutionWaiting:
		y, ok := any(b).(ExecutionWaiting)
		if !ok {
			return false
		}
		if ov.ExecutionWaiting != nil {
			if eq, handled := ov.ExecutionWaiting(x, y); handled {
				return eq
			}
		}
		if x.Progress != y.Progress {
			return false
		}
		return true
	case ExecutionCompleted:
		y, ok := any(b).(ExecutionCompleted)
		if !ok {
			return false
		}
		if ov.ExecutionCompleted != nil {
			if eq, handled := ov.ExecutionCompleted(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		if x.Progress != y.Progress {
			return false
		}
		return true
	case ExecutionRaised:
		y, ok := any(b).(ExecutionRaised)
		if !ok {
			return false
		}
		if ov.ExecutionRaised != nil {
			if eq, handled := ov.ExecutionRaised(x, y); handled {
				return eq
			}
		}
		if x.Class != y.Class {
			return false
		}
		if x.Reason != y.Reason {
			return false
		}
		if x.Progress != y.Progress {
			return false
		}
		return true
	}
	return false
}

// ExecutionSliceEqual reports structural equality of a and b.
func ExecutionSliceEqual(a, b ExecutionSlice) bool {
	return ExecutionSliceEqualWith(a, b, ExecutionSliceEqOverrides{})
}

//goplus:enum instructionOutcome
type instructionOutcome interface{ isInstructionOutcome() }

//goplus:variant (instructionOutcome) InstructionContinues()
type instructionContinues struct{}

func (instructionContinues) isInstructionOutcome() {}

//goplus:variant (instructionOutcome) InstructionWaits()
type instructionWaits struct{}

func (instructionWaits) isInstructionOutcome() {}

//goplus:variant (instructionOutcome) InstructionHalts()
type instructionHalts struct{}

func (instructionHalts) isInstructionOutcome() {}

// instructionOutcomeCases selects one handler per instructionOutcome variant for instructionOutcomeFold.
type instructionOutcomeCases[R any] struct {
	InstructionContinues func() R
	InstructionWaits     func() R
	InstructionHalts     func() R
}

// instructionOutcomeFold reduces instructionOutcome by one-level case analysis.
func instructionOutcomeFold[R any](i instructionOutcome, cs instructionOutcomeCases[R]) R {
	switch any(i).(type) {
	case instructionContinues:
		return cs.InstructionContinues()
	case instructionWaits:
		return cs.InstructionWaits()
	case instructionHalts:
		return cs.InstructionHalts()
	default:
		panic("goplus: impossible enum value in instructionOutcomeFold")
	}
}

// instructionOutcomeEqOverrides carries optional per-variant hooks for instructionOutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type instructionOutcomeEqOverrides struct {
	InstructionContinues func(x, y instructionContinues) (eq, handled bool)
	InstructionWaits     func(x, y instructionWaits) (eq, handled bool)
	InstructionHalts     func(x, y instructionHalts) (eq, handled bool)
}

// instructionOutcomeEqualWith reports structural equality of a and b under ov.
func instructionOutcomeEqualWith(a, b instructionOutcome, ov instructionOutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case instructionContinues:
		y, ok := any(b).(instructionContinues)
		if !ok {
			return false
		}
		if ov.InstructionContinues != nil {
			if eq, handled := ov.InstructionContinues(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case instructionWaits:
		y, ok := any(b).(instructionWaits)
		if !ok {
			return false
		}
		if ov.InstructionWaits != nil {
			if eq, handled := ov.InstructionWaits(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case instructionHalts:
		y, ok := any(b).(instructionHalts)
		if !ok {
			return false
		}
		if ov.InstructionHalts != nil {
			if eq, handled := ov.InstructionHalts(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// instructionOutcomeEqual reports structural equality of a and b.
func instructionOutcomeEqual(a, b instructionOutcome) bool {
	return instructionOutcomeEqualWith(a, b, instructionOutcomeEqOverrides{})
}

//goplus:enum ReductionClass
type ReductionClass interface{ isReductionClass() }

//goplus:variant (ReductionClass) ReductionFree()
type ReductionFree struct{}

func (ReductionFree) isReductionClass() {}

//goplus:variant (ReductionClass) DispatchReduction()
type DispatchReduction struct{}

func (DispatchReduction) isReductionClass() {}

// ReductionClassCases selects one handler per ReductionClass variant for ReductionClassFold.
type ReductionClassCases[R any] struct {
	ReductionFree     func() R
	DispatchReduction func() R
}

// ReductionClassFold reduces ReductionClass by one-level case analysis.
func ReductionClassFold[R any](v ReductionClass, cs ReductionClassCases[R]) R {
	switch any(v).(type) {
	case ReductionFree:
		return cs.ReductionFree()
	case DispatchReduction:
		return cs.DispatchReduction()
	default:
		panic("goplus: impossible enum value in ReductionClassFold")
	}
}

// ReductionClassEqOverrides carries optional per-variant hooks for ReductionClassEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ReductionClassEqOverrides struct {
	ReductionFree     func(x, y ReductionFree) (eq, handled bool)
	DispatchReduction func(x, y DispatchReduction) (eq, handled bool)
}

// ReductionClassEqualWith reports structural equality of a and b under ov.
func ReductionClassEqualWith(a, b ReductionClass, ov ReductionClassEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ReductionFree:
		y, ok := any(b).(ReductionFree)
		if !ok {
			return false
		}
		if ov.ReductionFree != nil {
			if eq, handled := ov.ReductionFree(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case DispatchReduction:
		y, ok := any(b).(DispatchReduction)
		if !ok {
			return false
		}
		if ov.DispatchReduction != nil {
			if eq, handled := ov.DispatchReduction(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ReductionClassEqual reports structural equality of a and b.
func ReductionClassEqual(a, b ReductionClass) bool {
	return ReductionClassEqualWith(a, b, ReductionClassEqOverrides{})
}

type Continuation struct {
	machine   *Machine
	completed bool
}

func (continuation *Continuation) ReleaseMemory() {
	if continuation == nil || continuation.machine == nil {
		return
	}
	continuation.machine.resetProcessMemory()
	continuation.completed = true
}

// assayxport:unit gotp.vm.reduction-continuation
func NewVMReductionBudget(value int) result.Result[VMReductionBudget, Failure] {
	if value <= 0 {
		return result.Err[VMReductionBudget, Failure]{Err: InvalidConfiguration{Detail: fmt.Sprintf(
			"VM reduction budget must be positive, got %d",
			value,
		)}}
	}
	return result.Ok[VMReductionBudget, Failure]{Value: VMReductionBudget{value: value}}
}

func VMReductionBudgetValue(budget VMReductionBudget) int {
	return budget.value
}

func OpcodeReductionClass(name string) ReductionClass {
	switch name {
	case "call", "call_only", "call_last", "call_ext", "call_ext_only", "call_ext_last", "call_fun", "call_fun2", "return", "send", "loop_rec_end":
		return DispatchReduction{}
	default:
		return ReductionFree{}
	}
}

func OpcodeReductionCost(name string) int {
	switch any(OpcodeReductionClass(name)).(type) {
	case ReductionFree:

		return 0
	case DispatchReduction:

		return 1
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) Start(entryLabel uint64) result.Result[*Continuation, Failure] {
	entry, present := machine.labels[entryLabel]
	if !present {
		return result.Err[*Continuation, Failure]{Err: MissingLabel{Label: entryLabel}}
	}
	machine.pc = entry + 1
	if machine.pc < len(machine.program) && machine.program[machine.pc].Opcode.Name == "func_info" {
		machine.pc++
	}
	machine.steps = 0
	machine.returnPCs = machine.returnPCs[:0]
	machine.returnImages = machine.returnImages[:0]
	machine.releaseAllCode()
	machine.handlers = machine.handlers[:0]
	machine.nextHandler = 0
	if machine.root != nil {
		machine.activate(machine.root)
	}
	return result.Ok[*Continuation, Failure]{Value: &Continuation{machine: machine}}
}

func (continuation *Continuation) Resume(
	budget VMReductionBudget,
) result.Result[ExecutionSlice, Failure] {
	return continuation.ResumeWithHost(budget, NoHostCapabilities())
}

func (continuation *Continuation) ResumeWithHost(
	budget VMReductionBudget,
	host HostCapabilities,
) result.Result[ExecutionSlice, Failure] {
	if continuation == nil || continuation.machine == nil {
		return result.Err[ExecutionSlice, Failure]{Err: InvalidConfiguration{Detail: "nil continuation"}}
	}
	if continuation.completed {
		return result.Err[ExecutionSlice, Failure]{Err: InvalidProgram{Detail: "continuation has completed"}}
	}
	if budget.value <= 0 {
		return result.Err[ExecutionSlice, Failure]{Err: InvalidConfiguration{Detail: "VM reduction budget must be positive"}}
	}
	machine := continuation.machine
	remaining := budget.value
	reductions := 0
	instructions := 0
	for {
		if machine.steps >= machine.stepLimit {
			return result.Err[ExecutionSlice, Failure]{Err: StepLimitExceeded{Limit: machine.stepLimit}}
		}
		if machine.pc < 0 || machine.pc >= len(machine.program) {
			return result.Err[ExecutionSlice, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
				"program counter %d is out of range",
				machine.pc,
			)}}
		}
		instruction := machine.program[machine.pc]
		cost := OpcodeReductionCost(instruction.Opcode.Name)
		if cost > remaining {
			return result.Ok[ExecutionSlice, Failure]{Value: ExecutionSuspended{Progress: ExecutionProgress{
				Reductions:        reductions,
				Instructions:      instructions,
				TotalInstructions: machine.steps,
			}}}
		}
		machine.steps++
		instructions++
		remaining -= cost
		reductions += cost
		var executed result.Result[instructionOutcome, Failure] = executeInstruction(
			machine,
			instruction,
			host,
		)
		switch __gp_m1 := any(executed).(type) {
		case result.Err[instructionOutcome, Failure]:
			failure := __gp_m1.Err

			var checked Failure = failure
			switch __gp_m2 := any(checked).(type) {
			case RaisedException:
				class := __gp_m2.Class
				reason := __gp_m2.Reason

				switch __gp_m3 := any(machine.unwindException(class, reason)).(type) {
				case result.Err[bool, Failure]:
					unwindFailure := __gp_m3.Err

					return result.Err[ExecutionSlice, Failure]{Err: unwindFailure}
				case result.Ok[bool, Failure]:
					caught := __gp_m3.Value

					if caught {
						continue
					}
				default:
					panic("goplus: impossible enum value in match")
				}
				machine.releaseAllCode()
				return result.Ok[ExecutionSlice, Failure]{Value: ExecutionRaised{Class: term.Clone(class), Reason: term.Clone(reason), Progress: ExecutionProgress{
					Reductions:        reductions,
					Instructions:      instructions,
					TotalInstructions: machine.steps,
				}}}
			case InvalidConfiguration, ImmediateOutOfRange, HeapIndexOutOfRange, MemoryFailure, InvalidProgram, RegisterOutOfRange, UninitializedRegister, MissingConstant, MissingLabel, StepLimitExceeded, UnsupportedOpcode:

				return result.Err[ExecutionSlice, Failure]{Err: failure}
			default:
				panic("goplus: impossible enum value in match")
			}
		case result.Ok[instructionOutcome, Failure]:
			outcome := __gp_m1.Value

			var instructionState instructionOutcome = outcome
			switch any(instructionState).(type) {
			case instructionContinues:

			case instructionWaits:

				return result.Ok[ExecutionSlice, Failure]{Value: ExecutionWaiting{Progress: ExecutionProgress{
					Reductions:        reductions,
					Instructions:      instructions,
					TotalInstructions: machine.steps,
				}}}
			case instructionHalts:

				machine.releaseAllCode()
				continuation.completed = true
				switch __gp_m5 := any(machine.X(0)).(type) {
				case result.Err[term.Term, Failure]:
					failure := __gp_m5.Err

					return result.Err[ExecutionSlice, Failure]{Err: failure}
				case result.Ok[term.Term, Failure]:
					value := __gp_m5.Value

					return result.Ok[ExecutionSlice, Failure]{Value: ExecutionCompleted{Value: value, Progress: ExecutionProgress{
						Reductions:        reductions,
						Instructions:      instructions,
						TotalInstructions: machine.steps,
					}}}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	}
}

// OTP-29.0.4 macros.tab charges FCALLS at DISPATCH and DISPATCH_RETURN.
func executeInstruction(
	machine *Machine,
	instruction beam.Instruction,
	host HostCapabilities,
) result.Result[instructionOutcome, Failure] {
	next := machine.pc + 1
	switch instruction.Opcode.Name {
	case "label":
		machine.pc = next
	case "func_info":
		return result.Err[instructionOutcome, Failure]{Err: RaisedException{Class: term.MustAtom("error"), Reason: term.MustAtom("function_clause")}}
	case "move":
		switch __gp_m6 := any(machine.move(instruction)).(type) {
		case result.Err[MachineMutation, Failure]:
			failure := __gp_m6.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[MachineMutation, Failure]:

			machine.pc = next
		default:
			panic("goplus: impossible enum value in match")
		}
	case "jump":
		switch __gp_m7 := any(machine.instructionLabel(instruction, 0)).(type) {
		case result.Ok[int, Failure]:
			target := __gp_m7.Value

			machine.pc = target
		case result.Err[int, Failure]:
			failure := __gp_m7.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "call":
		switch __gp_m8 := any(machine.instructionLabel(instruction, 1)).(type) {
		case result.Ok[int, Failure]:
			target := __gp_m8.Value

			machine.pushReturn(next)
			machine.pc = target
		case result.Err[int, Failure]:
			failure := __gp_m8.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "call_only":
		switch __gp_m9 := any(machine.instructionLabel(instruction, 1)).(type) {
		case result.Ok[int, Failure]:
			target := __gp_m9.Value

			machine.pc = target
		case result.Err[int, Failure]:
			failure := __gp_m9.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "call_last":
		switch __gp_m10 := any(machine.deallocate(instruction, 2)).(type) {
		case result.Err[MachineMutation, Failure]:
			failure := __gp_m10.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[MachineMutation, Failure]:

		default:
			panic("goplus: impossible enum value in match")
		}
		switch __gp_m11 := any(machine.instructionLabel(instruction, 1)).(type) {
		case result.Ok[int, Failure]:
			target := __gp_m11.Value

			machine.pc = target
		case result.Err[int, Failure]:
			failure := __gp_m11.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "call_ext":
		return executeExternalCall(machine, instruction, host, false, false)
	case "call_ext_only":
		return executeExternalCall(machine, instruction, host, true, false)
	case "call_ext_last":
		return executeExternalCall(machine, instruction, host, true, true)
	case "bif0", "bif1", "bif2", "gc_bif1", "gc_bif2", "gc_bif3":
		return executeBIFInstruction(machine, instruction, host)
	case "is_lt", "is_ge":
		return executeTermOrderInstruction(machine, instruction)
	case "make_fun3":
		return executeMakeFun3(machine, instruction)
	case "call_fun", "call_fun2":
		return executeCallFun(machine, instruction)
	case "is_function", "is_function2":
		return executeFunctionTest(machine, instruction)
	case "catch", "try":
		return executeExceptionSetup(machine, instruction)
	case "catch_end", "try_end", "try_case":
		return executeExceptionCleanup(machine, instruction)
	case "raise", "case_end", "badmatch", "if_end", "badrecord", "try_case_end":
		return executeExceptionRaise(machine, instruction)
	case "allocate", "allocate_zero":
		switch __gp_m12 := any(machine.allocate(instruction, 0)).(type) {
		case result.Ok[MachineMutation, Failure]:

			machine.pc = next
		case result.Err[MachineMutation, Failure]:
			failure := __gp_m12.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "allocate_heap", "get_hd", "get_list", "get_tl", "get_tuple_element", "init_yregs",
		"is_atom", "is_binary", "is_bitstr", "is_boolean", "is_eq", "is_eq_exact", "is_float",
		"is_integer", "is_list", "is_map", "is_ne", "is_ne_exact", "is_nil", "is_nonempty_list",
		"is_number", "is_pid", "is_port", "is_reference", "is_tagged_tuple", "is_tuple", "line",
		"put_list", "put_tuple2", "select_tuple_arity", "select_val", "swap", "test_arity", "test_heap", "trim":
		return executeCoreTermInstruction(machine, instruction)
	case "deallocate":
		switch __gp_m13 := any(machine.deallocate(instruction, 0)).(type) {
		case result.Ok[MachineMutation, Failure]:

			machine.pc = next
		case result.Err[MachineMutation, Failure]:
			failure := __gp_m13.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "send":
		switch __gp_m14 := any(machine.X(0)).(type) {
		case result.Err[term.Term, Failure]:
			failure := __gp_m14.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[term.Term, Failure]:
			destination := __gp_m14.Value

			switch __gp_m15 := any(machine.X(1)).(type) {
			case result.Err[term.Term, Failure]:
				failure := __gp_m15.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[term.Term, Failure]:
				message := __gp_m15.Value

				var sendCapability SendCapability = host.Send
				switch any(sendCapability).(type) {
				case SendUnavailable:

					return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "send requires an explicit host capability"}}
				case SendAllowed:

					effect := host.send
					if effect == nil {
						return result.Err[instructionOutcome, Failure]{Err: InvalidConfiguration{Detail: "send capability effect is nil"}}
					}
					var outcome SendOutcome = effect(destination, message)
					switch __gp_m17 := any(outcome).(type) {
					case SendRejected:
						detail := __gp_m17.Detail

						return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "send rejected: " + detail}}
					case MessageSent:
						value := __gp_m17.Value

						switch __gp_m18 := any(machine.SetX(0, value)).(type) {
						case result.Err[MachineMutation, Failure]:
							failure := __gp_m18.Err

							return result.Err[instructionOutcome, Failure]{Err: failure}
						case result.Ok[MachineMutation, Failure]:

							machine.pc = next
						default:
							panic("goplus: impossible enum value in match")
						}
					default:
						panic("goplus: impossible enum value in match")
					}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "loop_rec":
		if len(instruction.Operands) != 2 {
			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
				"loop_rec has %d operands",
				len(instruction.Operands),
			)}}
		}
		var receiveCapability ReceiveCapability = host.Receive
		switch any(receiveCapability).(type) {
		case ReceiveUnavailable:

			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "loop_rec requires an explicit receive capability"}}
		case ReceiveAllowed:

			if host.peek == nil {
				return result.Err[instructionOutcome, Failure]{Err: InvalidConfiguration{Detail: "receive peek effect is nil"}}
			}
			var outcome ReceiveOutcome = host.peek()
			switch __gp_m20 := any(outcome).(type) {
			case ReceiveRejected:
				detail := __gp_m20.Detail

				return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "receive rejected: " + detail}}
			case ReceiveEmpty:

				switch __gp_m21 := any(machine.instructionLabel(instruction, 0)).(type) {
				case result.Err[int, Failure]:
					failure := __gp_m21.Err

					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[int, Failure]:
					target := __gp_m21.Value

					machine.pc = target
				default:
					panic("goplus: impossible enum value in match")
				}
			case ReceiveMessage:
				message := __gp_m20.Value

				switch __gp_m22 := any(machine.assign(instruction.Operands[1], message)).(type) {
				case result.Err[MachineMutation, Failure]:
					failure := __gp_m22.Err

					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[MachineMutation, Failure]:

					machine.pc = next
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "loop_rec_end":
		if host.advance == nil {
			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "loop_rec_end requires an explicit receive capability"}}
		}
		var advanced AdvanceOutcome = host.advance()
		switch __gp_m23 := any(advanced).(type) {
		case AdvanceRejected:
			detail := __gp_m23.Detail

			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "receive advance rejected: " + detail}}
		case ReceiveCursorAdvanced:

			switch __gp_m24 := any(machine.instructionLabel(instruction, 0)).(type) {
			case result.Err[int, Failure]:
				failure := __gp_m24.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[int, Failure]:
				target := __gp_m24.Value

				machine.pc = target
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "remove_message":
		if host.remove == nil {
			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "remove_message requires an explicit receive capability"}}
		}
		var removed RemoveOutcome = host.remove()
		switch __gp_m25 := any(removed).(type) {
		case RemoveRejected:
			detail := __gp_m25.Detail

			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "receive removal rejected: " + detail}}
		case ReceiveMessageRemoved:

			var timerCapability TimerCapability = host.Timer
			switch any(timerCapability).(type) {
			case TimerUnavailable:

			case TimerAllowed:

				if host.timerCancel == nil {
					return result.Err[instructionOutcome, Failure]{Err: InvalidConfiguration{Detail: "timer cancel effect is nil"}}
				}
				var cancelled TimerMutation = host.timerCancel()
				switch __gp_m27 := any(cancelled).(type) {
				case TimerMutationRejected:
					detail := __gp_m27.Detail

					return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "timer cancellation rejected: " + detail}}
				case TimerChanged, TimerUnchanged:

				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
			machine.pc = next
		default:
			panic("goplus: impossible enum value in match")
		}
	case "timeout":
		var timerCapability TimerCapability = host.Timer
		switch any(timerCapability).(type) {
		case TimerUnavailable:

			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "timeout requires an explicit timer capability"}}
		case TimerAllowed:

			if host.timerFinish == nil {
				return result.Err[instructionOutcome, Failure]{Err: InvalidConfiguration{Detail: "timer finish effect is nil"}}
			}
			var finished TimerMutation = host.timerFinish()
			switch __gp_m29 := any(finished).(type) {
			case TimerMutationRejected:
				detail := __gp_m29.Detail

				return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "timer completion rejected: " + detail}}
			case TimerChanged, TimerUnchanged:

				machine.pc = next
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "wait":
		switch __gp_m30 := any(machine.instructionLabel(instruction, 0)).(type) {
		case result.Err[int, Failure]:
			failure := __gp_m30.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[int, Failure]:
			target := __gp_m30.Value

			machine.pc = target
			return result.Ok[instructionOutcome, Failure]{Value: instructionWaits{}}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "wait_timeout":
		if len(instruction.Operands) != 2 {
			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
				"wait_timeout has %d operands",
				len(instruction.Operands),
			)}}
		}
		switch __gp_m31 := any(receiveTimeout(machine, instruction.Operands[1])).(type) {
		case result.Err[option.Option[time.Duration], Failure]:
			failure := __gp_m31.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[option.Option[time.Duration], Failure]:
			timeout := __gp_m31.Value

			switch __gp_m32 := any(timeout).(type) {
			case option.None[time.Duration]:

				switch __gp_m33 := any(machine.instructionLabel(instruction, 0)).(type) {
				case result.Err[int, Failure]:
					failure := __gp_m33.Err

					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[int, Failure]:
					target := __gp_m33.Value

					machine.pc = target
					return result.Ok[instructionOutcome, Failure]{Value: instructionWaits{}}
				default:
					panic("goplus: impossible enum value in match")
				}
			case option.Some[time.Duration]:
				delay := __gp_m32.Value

				if delay == 0 {
					machine.pc = next
					return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
				}
				var timerCapability TimerCapability = host.Timer
				switch any(timerCapability).(type) {
				case TimerUnavailable:

					return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "wait_timeout requires an explicit timer capability"}}
				case TimerAllowed:

					if host.timerWait == nil {
						return result.Err[instructionOutcome, Failure]{Err: InvalidConfiguration{Detail: "timer wait effect is nil"}}
					}
					var waited TimerWaitOutcome = host.timerWait(delay)
					switch __gp_m35 := any(waited).(type) {
					case TimerRejected:
						detail := __gp_m35.Detail

						return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "timer wait rejected: " + detail}}
					case TimerExpired:

						machine.pc = next
					case TimerPending:

						switch __gp_m36 := any(machine.instructionLabel(instruction, 0)).(type) {
						case result.Err[int, Failure]:
							failure := __gp_m36.Err

							return result.Err[instructionOutcome, Failure]{Err: failure}
						case result.Ok[int, Failure]:
							target := __gp_m36.Value

							machine.pc = target
							return result.Ok[instructionOutcome, Failure]{Value: instructionWaits{}}
						default:
							panic("goplus: impossible enum value in match")
						}
					default:
						panic("goplus: impossible enum value in match")
					}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "return":
		if !machine.returnToCaller() {
			return result.Ok[instructionOutcome, Failure]{Value: instructionHalts{}}
		}
	case "int_code_end":
		return result.Ok[instructionOutcome, Failure]{Value: instructionHalts{}}
	default:
		return result.Err[instructionOutcome, Failure]{Err: UnsupportedOpcode{Name: instruction.Opcode.Name, Arity: instruction.Opcode.Arity, Offset: instruction.Offset}}
	}
	return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
}

func receiveTimeout(
	machine *Machine,
	operand beam.Operand,
) result.Result[option.Option[time.Duration], Failure] {
	switch __gp_m37 := any(machine.resolve(operand)).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m37.Err

		return result.Err[option.Option[time.Duration], Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m37.Value

		switch __gp_m38 := any(term.AtomName(value)).(type) {
		case option.Some[string]:
			name := __gp_m38.Value

			if name == "infinity" {
				return result.Ok[option.Option[time.Duration], Failure]{Value: option.None[time.Duration]{}}
			}
		case option.None[string]:

		default:
			panic("goplus: impossible enum value in match")
		}
		switch __gp_m39 := any(term.IntegerValue(value)).(type) {
		case option.None[*big.Int]:

			return result.Err[option.Option[time.Duration], Failure]{Err: InvalidProgram{Detail: "receive timeout must be a non-negative integer or infinity"}}
		case option.Some[*big.Int]:
			integer := __gp_m39.Value

			if !integer.IsInt64() {
				return result.Err[option.Option[time.Duration], Failure]{Err: InvalidProgram{Detail: "receive timeout is out of range"}}
			}
			milliseconds := integer.Int64()
			if milliseconds < 0 || milliseconds > math.MaxInt64/int64(time.Millisecond) {
				return result.Err[option.Option[time.Duration], Failure]{Err: InvalidProgram{Detail: "receive timeout is out of range"}}
			}
			return result.Ok[option.Option[time.Duration], Failure]{Value: option.Some[time.Duration]{Value: time.Duration(milliseconds) * time.Millisecond}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}
