// Code generated by goplus from effects.gp. DO NOT EDIT.
//goplus:v v0.28.0

package vm

import (
	"time"

	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/term"
)

//goplus:enum TimerWaitOutcome
type TimerWaitOutcome interface{ isTimerWaitOutcome() }

//goplus:variant (TimerWaitOutcome) TimerPending()
type TimerPending struct{}

func (TimerPending) isTimerWaitOutcome() {}

//goplus:variant (TimerWaitOutcome) TimerExpired()
type TimerExpired struct{}

func (TimerExpired) isTimerWaitOutcome() {}

//goplus:variant (TimerWaitOutcome) TimerRejected(Detail string)
type TimerRejected struct {
	Detail string
}

func (TimerRejected) isTimerWaitOutcome() {}

// TimerWaitOutcomeCases selects one handler per TimerWaitOutcome variant for TimerWaitOutcomeFold.
type TimerWaitOutcomeCases[R any] struct {
	TimerPending  func() R
	TimerExpired  func() R
	TimerRejected func(Detail string) R
}

// TimerWaitOutcomeFold reduces TimerWaitOutcome by one-level case analysis.
func TimerWaitOutcomeFold[R any](t TimerWaitOutcome, cs TimerWaitOutcomeCases[R]) R {
	switch m := any(t).(type) {
	case TimerPending:
		return cs.TimerPending()
	case TimerExpired:
		return cs.TimerExpired()
	case TimerRejected:
		return cs.TimerRejected(m.Detail)
	default:
		panic("goplus: impossible enum value in TimerWaitOutcomeFold")
	}
}

// TimerWaitOutcomeEqOverrides carries optional per-variant hooks for TimerWaitOutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TimerWaitOutcomeEqOverrides struct {
	TimerPending  func(x, y TimerPending) (eq, handled bool)
	TimerExpired  func(x, y TimerExpired) (eq, handled bool)
	TimerRejected func(x, y TimerRejected) (eq, handled bool)
}

// TimerWaitOutcomeEqualWith reports structural equality of a and b under ov.
func TimerWaitOutcomeEqualWith(a, b TimerWaitOutcome, ov TimerWaitOutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case TimerPending:
		y, ok := any(b).(TimerPending)
		if !ok {
			return false
		}
		if ov.TimerPending != nil {
			if eq, handled := ov.TimerPending(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TimerExpired:
		y, ok := any(b).(TimerExpired)
		if !ok {
			return false
		}
		if ov.TimerExpired != nil {
			if eq, handled := ov.TimerExpired(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TimerRejected:
		y, ok := any(b).(TimerRejected)
		if !ok {
			return false
		}
		if ov.TimerRejected != nil {
			if eq, handled := ov.TimerRejected(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// TimerWaitOutcomeEqual reports structural equality of a and b.
func TimerWaitOutcomeEqual(a, b TimerWaitOutcome) bool {
	return TimerWaitOutcomeEqualWith(a, b, TimerWaitOutcomeEqOverrides{})
}

//goplus:enum TimerMutation
type TimerMutation interface{ isTimerMutation() }

//goplus:variant (TimerMutation) TimerChanged()
type TimerChanged struct{}

func (TimerChanged) isTimerMutation() {}

//goplus:variant (TimerMutation) TimerUnchanged()
type TimerUnchanged struct{}

func (TimerUnchanged) isTimerMutation() {}

//goplus:variant (TimerMutation) TimerMutationRejected(Detail string)
type TimerMutationRejected struct {
	Detail string
}

func (TimerMutationRejected) isTimerMutation() {}

// TimerMutationCases selects one handler per TimerMutation variant for TimerMutationFold.
type TimerMutationCases[R any] struct {
	TimerChanged          func() R
	TimerUnchanged        func() R
	TimerMutationRejected func(Detail string) R
}

// TimerMutationFold reduces TimerMutation by one-level case analysis.
func TimerMutationFold[R any](t TimerMutation, cs TimerMutationCases[R]) R {
	switch m := any(t).(type) {
	case TimerChanged:
		return cs.TimerChanged()
	case TimerUnchanged:
		return cs.TimerUnchanged()
	case TimerMutationRejected:
		return cs.TimerMutationRejected(m.Detail)
	default:
		panic("goplus: impossible enum value in TimerMutationFold")
	}
}

// TimerMutationEqOverrides carries optional per-variant hooks for TimerMutationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TimerMutationEqOverrides struct {
	TimerChanged          func(x, y TimerChanged) (eq, handled bool)
	TimerUnchanged        func(x, y TimerUnchanged) (eq, handled bool)
	TimerMutationRejected func(x, y TimerMutationRejected) (eq, handled bool)
}

// TimerMutationEqualWith reports structural equality of a and b under ov.
func TimerMutationEqualWith(a, b TimerMutation, ov TimerMutationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case TimerChanged:
		y, ok := any(b).(TimerChanged)
		if !ok {
			return false
		}
		if ov.TimerChanged != nil {
			if eq, handled := ov.TimerChanged(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TimerUnchanged:
		y, ok := any(b).(TimerUnchanged)
		if !ok {
			return false
		}
		if ov.TimerUnchanged != nil {
			if eq, handled := ov.TimerUnchanged(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TimerMutationRejected:
		y, ok := any(b).(TimerMutationRejected)
		if !ok {
			return false
		}
		if ov.TimerMutationRejected != nil {
			if eq, handled := ov.TimerMutationRejected(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// TimerMutationEqual reports structural equality of a and b.
func TimerMutationEqual(a, b TimerMutation) bool {
	return TimerMutationEqualWith(a, b, TimerMutationEqOverrides{})
}

type TimerWaitEffect func(Delay time.Duration) TimerWaitOutcome
type TimerMutationEffect func() TimerMutation

//goplus:enum TimerCapability
type TimerCapability interface{ isTimerCapability() }

//goplus:variant (TimerCapability) TimerUnavailable()
type TimerUnavailable struct{}

func (TimerUnavailable) isTimerCapability() {}

//goplus:variant (TimerCapability) TimerAllowed()
type TimerAllowed struct{}

func (TimerAllowed) isTimerCapability() {}

// TimerCapabilityCases selects one handler per TimerCapability variant for TimerCapabilityFold.
type TimerCapabilityCases[R any] struct {
	TimerUnavailable func() R
	TimerAllowed     func() R
}

// TimerCapabilityFold reduces TimerCapability by one-level case analysis.
func TimerCapabilityFold[R any](t TimerCapability, cs TimerCapabilityCases[R]) R {
	switch any(t).(type) {
	case TimerUnavailable:
		return cs.TimerUnavailable()
	case TimerAllowed:
		return cs.TimerAllowed()
	default:
		panic("goplus: impossible enum value in TimerCapabilityFold")
	}
}

// TimerCapabilityEqOverrides carries optional per-variant hooks for TimerCapabilityEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TimerCapabilityEqOverrides struct {
	TimerUnavailable func(x, y TimerUnavailable) (eq, handled bool)
	TimerAllowed     func(x, y TimerAllowed) (eq, handled bool)
}

// TimerCapabilityEqualWith reports structural equality of a and b under ov.
func TimerCapabilityEqualWith(a, b TimerCapability, ov TimerCapabilityEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case TimerUnavailable:
		y, ok := any(b).(TimerUnavailable)
		if !ok {
			return false
		}
		if ov.TimerUnavailable != nil {
			if eq, handled := ov.TimerUnavailable(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TimerAllowed:
		y, ok := any(b).(TimerAllowed)
		if !ok {
			return false
		}
		if ov.TimerAllowed != nil {
			if eq, handled := ov.TimerAllowed(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// TimerCapabilityEqual reports structural equality of a and b.
func TimerCapabilityEqual(a, b TimerCapability) bool {
	return TimerCapabilityEqualWith(a, b, TimerCapabilityEqOverrides{})
}

type TimerEffects struct {
	Wait   TimerWaitEffect
	Cancel TimerMutationEffect
	Finish TimerMutationEffect
}

type ExternalFunction struct {
	Module   string
	Function string
	Arity    uint32
}

// assayxport:unit gotp.vm.exception-propagation
//
//goplus:enum ExternalCallOutcome
type ExternalCallOutcome interface{ isExternalCallOutcome() }

//goplus:variant (ExternalCallOutcome) ExternalCallUnbound()
type ExternalCallUnbound struct{}

func (ExternalCallUnbound) isExternalCallOutcome() {}

//goplus:variant (ExternalCallOutcome) ExternalCallReturned(Value term.Term)
type ExternalCallReturned struct {
	Value term.Term
}

func (ExternalCallReturned) isExternalCallOutcome() {}

//goplus:variant (ExternalCallOutcome) ExternalCallRaised(Class term.Term, Reason term.Term)
type ExternalCallRaised struct {
	Class  term.Term
	Reason term.Term
}

func (ExternalCallRaised) isExternalCallOutcome() {}

//goplus:variant (ExternalCallOutcome) ExternalCallRejected(Detail string)
type ExternalCallRejected struct {
	Detail string
}

func (ExternalCallRejected) isExternalCallOutcome() {}

// ExternalCallOutcomeCases selects one handler per ExternalCallOutcome variant for ExternalCallOutcomeFold.
type ExternalCallOutcomeCases[R any] struct {
	ExternalCallUnbound  func() R
	ExternalCallReturned func(Value term.Term) R
	ExternalCallRaised   func(Class term.Term, Reason term.Term) R
	ExternalCallRejected func(Detail string) R
}

// ExternalCallOutcomeFold reduces ExternalCallOutcome by one-level case analysis.
func ExternalCallOutcomeFold[R any](e ExternalCallOutcome, cs ExternalCallOutcomeCases[R]) R {
	switch m := any(e).(type) {
	case ExternalCallUnbound:
		return cs.ExternalCallUnbound()
	case ExternalCallReturned:
		return cs.ExternalCallReturned(m.Value)
	case ExternalCallRaised:
		return cs.ExternalCallRaised(m.Class, m.Reason)
	case ExternalCallRejected:
		return cs.ExternalCallRejected(m.Detail)
	default:
		panic("goplus: impossible enum value in ExternalCallOutcomeFold")
	}
}

// ExternalCallOutcomeEqOverrides carries optional per-variant hooks for ExternalCallOutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ExternalCallOutcomeEqOverrides struct {
	ExternalCallUnbound  func(x, y ExternalCallUnbound) (eq, handled bool)
	ExternalCallReturned func(x, y ExternalCallReturned) (eq, handled bool)
	ExternalCallRaised   func(x, y ExternalCallRaised) (eq, handled bool)
	ExternalCallRejected func(x, y ExternalCallRejected) (eq, handled bool)
}

// ExternalCallOutcomeEqualWith reports structural equality of a and b under ov.
func ExternalCallOutcomeEqualWith(a, b ExternalCallOutcome, ov ExternalCallOutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ExternalCallUnbound:
		y, ok := any(b).(ExternalCallUnbound)
		if !ok {
			return false
		}
		if ov.ExternalCallUnbound != nil {
			if eq, handled := ov.ExternalCallUnbound(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExternalCallReturned:
		y, ok := any(b).(ExternalCallReturned)
		if !ok {
			return false
		}
		if ov.ExternalCallReturned != nil {
			if eq, handled := ov.ExternalCallReturned(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case ExternalCallRaised:
		y, ok := any(b).(ExternalCallRaised)
		if !ok {
			return false
		}
		if ov.ExternalCallRaised != nil {
			if eq, handled := ov.ExternalCallRaised(x, y); handled {
				return eq
			}
		}
		if x.Class != y.Class {
			return false
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	case ExternalCallRejected:
		y, ok := any(b).(ExternalCallRejected)
		if !ok {
			return false
		}
		if ov.ExternalCallRejected != nil {
			if eq, handled := ov.ExternalCallRejected(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// ExternalCallOutcomeEqual reports structural equality of a and b.
func ExternalCallOutcomeEqual(a, b ExternalCallOutcome) bool {
	return ExternalCallOutcomeEqualWith(a, b, ExternalCallOutcomeEqOverrides{})
}

type ExternalCallEffect func(Target ExternalFunction, Arguments []term.Term) ExternalCallOutcome

//goplus:enum ExternalCallCapability
type ExternalCallCapability interface{ isExternalCallCapability() }

//goplus:variant (ExternalCallCapability) ExternalCallsUnavailable()
type ExternalCallsUnavailable struct{}

func (ExternalCallsUnavailable) isExternalCallCapability() {}

//goplus:variant (ExternalCallCapability) ExternalCallsAllowed()
type ExternalCallsAllowed struct{}

func (ExternalCallsAllowed) isExternalCallCapability() {}

// ExternalCallCapabilityCases selects one handler per ExternalCallCapability variant for ExternalCallCapabilityFold.
type ExternalCallCapabilityCases[R any] struct {
	ExternalCallsUnavailable func() R
	ExternalCallsAllowed     func() R
}

// ExternalCallCapabilityFold reduces ExternalCallCapability by one-level case analysis.
func ExternalCallCapabilityFold[R any](e ExternalCallCapability, cs ExternalCallCapabilityCases[R]) R {
	switch any(e).(type) {
	case ExternalCallsUnavailable:
		return cs.ExternalCallsUnavailable()
	case ExternalCallsAllowed:
		return cs.ExternalCallsAllowed()
	default:
		panic("goplus: impossible enum value in ExternalCallCapabilityFold")
	}
}

// ExternalCallCapabilityEqOverrides carries optional per-variant hooks for ExternalCallCapabilityEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ExternalCallCapabilityEqOverrides struct {
	ExternalCallsUnavailable func(x, y ExternalCallsUnavailable) (eq, handled bool)
	ExternalCallsAllowed     func(x, y ExternalCallsAllowed) (eq, handled bool)
}

// ExternalCallCapabilityEqualWith reports structural equality of a and b under ov.
func ExternalCallCapabilityEqualWith(a, b ExternalCallCapability, ov ExternalCallCapabilityEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ExternalCallsUnavailable:
		y, ok := any(b).(ExternalCallsUnavailable)
		if !ok {
			return false
		}
		if ov.ExternalCallsUnavailable != nil {
			if eq, handled := ov.ExternalCallsUnavailable(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExternalCallsAllowed:
		y, ok := any(b).(ExternalCallsAllowed)
		if !ok {
			return false
		}
		if ov.ExternalCallsAllowed != nil {
			if eq, handled := ov.ExternalCallsAllowed(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ExternalCallCapabilityEqual reports structural equality of a and b.
func ExternalCallCapabilityEqual(a, b ExternalCallCapability) bool {
	return ExternalCallCapabilityEqualWith(a, b, ExternalCallCapabilityEqOverrides{})
}

//goplus:enum LinkedCodeOutcome
type LinkedCodeOutcome interface{ isLinkedCodeOutcome() }

//goplus:variant (LinkedCodeOutcome) LinkedCodeUnchanged()
type LinkedCodeUnchanged struct{}

func (LinkedCodeUnchanged) isLinkedCodeOutcome() {}

//goplus:variant (LinkedCodeOutcome) LinkedCodeResolved(Image ModuleImage, Leave func())
type LinkedCodeResolved struct {
	Image ModuleImage
	Leave func()
}

func (LinkedCodeResolved) isLinkedCodeOutcome() {}

//goplus:variant (LinkedCodeOutcome) LinkedCodeRejected(Detail string)
type LinkedCodeRejected struct {
	Detail string
}

func (LinkedCodeRejected) isLinkedCodeOutcome() {}

// LinkedCodeOutcomeCases selects one handler per LinkedCodeOutcome variant for LinkedCodeOutcomeFold.
type LinkedCodeOutcomeCases[R any] struct {
	LinkedCodeUnchanged func() R
	LinkedCodeResolved  func(Image ModuleImage, Leave func()) R
	LinkedCodeRejected  func(Detail string) R
}

// LinkedCodeOutcomeFold reduces LinkedCodeOutcome by one-level case analysis.
func LinkedCodeOutcomeFold[R any](l LinkedCodeOutcome, cs LinkedCodeOutcomeCases[R]) R {
	switch m := any(l).(type) {
	case LinkedCodeUnchanged:
		return cs.LinkedCodeUnchanged()
	case LinkedCodeResolved:
		return cs.LinkedCodeResolved(m.Image, m.Leave)
	case LinkedCodeRejected:
		return cs.LinkedCodeRejected(m.Detail)
	default:
		panic("goplus: impossible enum value in LinkedCodeOutcomeFold")
	}
}

type LinkedCodeEffect func(Target ExternalFunction) LinkedCodeOutcome

//goplus:enum LinkedCodeCapability
type LinkedCodeCapability interface{ isLinkedCodeCapability() }

//goplus:variant (LinkedCodeCapability) LinkedCodeUnavailable()
type LinkedCodeUnavailable struct{}

func (LinkedCodeUnavailable) isLinkedCodeCapability() {}

//goplus:variant (LinkedCodeCapability) LinkedCodeAllowed()
type LinkedCodeAllowed struct{}

func (LinkedCodeAllowed) isLinkedCodeCapability() {}

// LinkedCodeCapabilityCases selects one handler per LinkedCodeCapability variant for LinkedCodeCapabilityFold.
type LinkedCodeCapabilityCases[R any] struct {
	LinkedCodeUnavailable func() R
	LinkedCodeAllowed     func() R
}

// LinkedCodeCapabilityFold reduces LinkedCodeCapability by one-level case analysis.
func LinkedCodeCapabilityFold[R any](l LinkedCodeCapability, cs LinkedCodeCapabilityCases[R]) R {
	switch any(l).(type) {
	case LinkedCodeUnavailable:
		return cs.LinkedCodeUnavailable()
	case LinkedCodeAllowed:
		return cs.LinkedCodeAllowed()
	default:
		panic("goplus: impossible enum value in LinkedCodeCapabilityFold")
	}
}

// LinkedCodeCapabilityEqOverrides carries optional per-variant hooks for LinkedCodeCapabilityEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type LinkedCodeCapabilityEqOverrides struct {
	LinkedCodeUnavailable func(x, y LinkedCodeUnavailable) (eq, handled bool)
	LinkedCodeAllowed     func(x, y LinkedCodeAllowed) (eq, handled bool)
}

// LinkedCodeCapabilityEqualWith reports structural equality of a and b under ov.
func LinkedCodeCapabilityEqualWith(a, b LinkedCodeCapability, ov LinkedCodeCapabilityEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case LinkedCodeUnavailable:
		y, ok := any(b).(LinkedCodeUnavailable)
		if !ok {
			return false
		}
		if ov.LinkedCodeUnavailable != nil {
			if eq, handled := ov.LinkedCodeUnavailable(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case LinkedCodeAllowed:
		y, ok := any(b).(LinkedCodeAllowed)
		if !ok {
			return false
		}
		if ov.LinkedCodeAllowed != nil {
			if eq, handled := ov.LinkedCodeAllowed(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// LinkedCodeCapabilityEqual reports structural equality of a and b.
func LinkedCodeCapabilityEqual(a, b LinkedCodeCapability) bool {
	return LinkedCodeCapabilityEqualWith(a, b, LinkedCodeCapabilityEqOverrides{})
}

//goplus:enum SendOutcome
type SendOutcome interface{ isSendOutcome() }

//goplus:variant (SendOutcome) MessageSent(Value term.Term)
type MessageSent struct {
	Value term.Term
}

func (MessageSent) isSendOutcome() {}

//goplus:variant (SendOutcome) SendRejected(Detail string)
type SendRejected struct {
	Detail string
}

func (SendRejected) isSendOutcome() {}

// SendOutcomeCases selects one handler per SendOutcome variant for SendOutcomeFold.
type SendOutcomeCases[R any] struct {
	MessageSent  func(Value term.Term) R
	SendRejected func(Detail string) R
}

// SendOutcomeFold reduces SendOutcome by one-level case analysis.
func SendOutcomeFold[R any](s SendOutcome, cs SendOutcomeCases[R]) R {
	switch m := any(s).(type) {
	case MessageSent:
		return cs.MessageSent(m.Value)
	case SendRejected:
		return cs.SendRejected(m.Detail)
	default:
		panic("goplus: impossible enum value in SendOutcomeFold")
	}
}

// SendOutcomeEqOverrides carries optional per-variant hooks for SendOutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type SendOutcomeEqOverrides struct {
	MessageSent  func(x, y MessageSent) (eq, handled bool)
	SendRejected func(x, y SendRejected) (eq, handled bool)
}

// SendOutcomeEqualWith reports structural equality of a and b under ov.
func SendOutcomeEqualWith(a, b SendOutcome, ov SendOutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case MessageSent:
		y, ok := any(b).(MessageSent)
		if !ok {
			return false
		}
		if ov.MessageSent != nil {
			if eq, handled := ov.MessageSent(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case SendRejected:
		y, ok := any(b).(SendRejected)
		if !ok {
			return false
		}
		if ov.SendRejected != nil {
			if eq, handled := ov.SendRejected(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// SendOutcomeEqual reports structural equality of a and b.
func SendOutcomeEqual(a, b SendOutcome) bool {
	return SendOutcomeEqualWith(a, b, SendOutcomeEqOverrides{})
}

type SendEffect func(To term.Term, Message term.Term) SendOutcome

//goplus:enum SendCapability
type SendCapability interface{ isSendCapability() }

//goplus:variant (SendCapability) SendUnavailable()
type SendUnavailable struct{}

func (SendUnavailable) isSendCapability() {}

//goplus:variant (SendCapability) SendAllowed()
type SendAllowed struct{}

func (SendAllowed) isSendCapability() {}

// SendCapabilityCases selects one handler per SendCapability variant for SendCapabilityFold.
type SendCapabilityCases[R any] struct {
	SendUnavailable func() R
	SendAllowed     func() R
}

// SendCapabilityFold reduces SendCapability by one-level case analysis.
func SendCapabilityFold[R any](s SendCapability, cs SendCapabilityCases[R]) R {
	switch any(s).(type) {
	case SendUnavailable:
		return cs.SendUnavailable()
	case SendAllowed:
		return cs.SendAllowed()
	default:
		panic("goplus: impossible enum value in SendCapabilityFold")
	}
}

// SendCapabilityEqOverrides carries optional per-variant hooks for SendCapabilityEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type SendCapabilityEqOverrides struct {
	SendUnavailable func(x, y SendUnavailable) (eq, handled bool)
	SendAllowed     func(x, y SendAllowed) (eq, handled bool)
}

// SendCapabilityEqualWith reports structural equality of a and b under ov.
func SendCapabilityEqualWith(a, b SendCapability, ov SendCapabilityEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case SendUnavailable:
		y, ok := any(b).(SendUnavailable)
		if !ok {
			return false
		}
		if ov.SendUnavailable != nil {
			if eq, handled := ov.SendUnavailable(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case SendAllowed:
		y, ok := any(b).(SendAllowed)
		if !ok {
			return false
		}
		if ov.SendAllowed != nil {
			if eq, handled := ov.SendAllowed(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// SendCapabilityEqual reports structural equality of a and b.
func SendCapabilityEqual(a, b SendCapability) bool {
	return SendCapabilityEqualWith(a, b, SendCapabilityEqOverrides{})
}

//goplus:enum ReceiveOutcome
type ReceiveOutcome interface{ isReceiveOutcome() }

//goplus:variant (ReceiveOutcome) ReceiveMessage(Value term.Term)
type ReceiveMessage struct {
	Value term.Term
}

func (ReceiveMessage) isReceiveOutcome() {}

//goplus:variant (ReceiveOutcome) ReceiveEmpty()
type ReceiveEmpty struct{}

func (ReceiveEmpty) isReceiveOutcome() {}

//goplus:variant (ReceiveOutcome) ReceiveRejected(Detail string)
type ReceiveRejected struct {
	Detail string
}

func (ReceiveRejected) isReceiveOutcome() {}

// ReceiveOutcomeCases selects one handler per ReceiveOutcome variant for ReceiveOutcomeFold.
type ReceiveOutcomeCases[R any] struct {
	ReceiveMessage  func(Value term.Term) R
	ReceiveEmpty    func() R
	ReceiveRejected func(Detail string) R
}

// ReceiveOutcomeFold reduces ReceiveOutcome by one-level case analysis.
func ReceiveOutcomeFold[R any](v ReceiveOutcome, cs ReceiveOutcomeCases[R]) R {
	switch m := any(v).(type) {
	case ReceiveMessage:
		return cs.ReceiveMessage(m.Value)
	case ReceiveEmpty:
		return cs.ReceiveEmpty()
	case ReceiveRejected:
		return cs.ReceiveRejected(m.Detail)
	default:
		panic("goplus: impossible enum value in ReceiveOutcomeFold")
	}
}

// ReceiveOutcomeEqOverrides carries optional per-variant hooks for ReceiveOutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ReceiveOutcomeEqOverrides struct {
	ReceiveMessage  func(x, y ReceiveMessage) (eq, handled bool)
	ReceiveEmpty    func(x, y ReceiveEmpty) (eq, handled bool)
	ReceiveRejected func(x, y ReceiveRejected) (eq, handled bool)
}

// ReceiveOutcomeEqualWith reports structural equality of a and b under ov.
func ReceiveOutcomeEqualWith(a, b ReceiveOutcome, ov ReceiveOutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ReceiveMessage:
		y, ok := any(b).(ReceiveMessage)
		if !ok {
			return false
		}
		if ov.ReceiveMessage != nil {
			if eq, handled := ov.ReceiveMessage(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case ReceiveEmpty:
		y, ok := any(b).(ReceiveEmpty)
		if !ok {
			return false
		}
		if ov.ReceiveEmpty != nil {
			if eq, handled := ov.ReceiveEmpty(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ReceiveRejected:
		y, ok := any(b).(ReceiveRejected)
		if !ok {
			return false
		}
		if ov.ReceiveRejected != nil {
			if eq, handled := ov.ReceiveRejected(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// ReceiveOutcomeEqual reports structural equality of a and b.
func ReceiveOutcomeEqual(a, b ReceiveOutcome) bool {
	return ReceiveOutcomeEqualWith(a, b, ReceiveOutcomeEqOverrides{})
}

//goplus:enum AdvanceOutcome
type AdvanceOutcome interface{ isAdvanceOutcome() }

//goplus:variant (AdvanceOutcome) ReceiveCursorAdvanced()
type ReceiveCursorAdvanced struct{}

func (ReceiveCursorAdvanced) isAdvanceOutcome() {}

//goplus:variant (AdvanceOutcome) AdvanceRejected(Detail string)
type AdvanceRejected struct {
	Detail string
}

func (AdvanceRejected) isAdvanceOutcome() {}

// AdvanceOutcomeCases selects one handler per AdvanceOutcome variant for AdvanceOutcomeFold.
type AdvanceOutcomeCases[R any] struct {
	ReceiveCursorAdvanced func() R
	AdvanceRejected       func(Detail string) R
}

// AdvanceOutcomeFold reduces AdvanceOutcome by one-level case analysis.
func AdvanceOutcomeFold[R any](a AdvanceOutcome, cs AdvanceOutcomeCases[R]) R {
	switch m := any(a).(type) {
	case ReceiveCursorAdvanced:
		return cs.ReceiveCursorAdvanced()
	case AdvanceRejected:
		return cs.AdvanceRejected(m.Detail)
	default:
		panic("goplus: impossible enum value in AdvanceOutcomeFold")
	}
}

// AdvanceOutcomeEqOverrides carries optional per-variant hooks for AdvanceOutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type AdvanceOutcomeEqOverrides struct {
	ReceiveCursorAdvanced func(x, y ReceiveCursorAdvanced) (eq, handled bool)
	AdvanceRejected       func(x, y AdvanceRejected) (eq, handled bool)
}

// AdvanceOutcomeEqualWith reports structural equality of a and b under ov.
func AdvanceOutcomeEqualWith(a, b AdvanceOutcome, ov AdvanceOutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ReceiveCursorAdvanced:
		y, ok := any(b).(ReceiveCursorAdvanced)
		if !ok {
			return false
		}
		if ov.ReceiveCursorAdvanced != nil {
			if eq, handled := ov.ReceiveCursorAdvanced(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AdvanceRejected:
		y, ok := any(b).(AdvanceRejected)
		if !ok {
			return false
		}
		if ov.AdvanceRejected != nil {
			if eq, handled := ov.AdvanceRejected(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// AdvanceOutcomeEqual reports structural equality of a and b.
func AdvanceOutcomeEqual(a, b AdvanceOutcome) bool {
	return AdvanceOutcomeEqualWith(a, b, AdvanceOutcomeEqOverrides{})
}

//goplus:enum RemoveOutcome
type RemoveOutcome interface{ isRemoveOutcome() }

//goplus:variant (RemoveOutcome) ReceiveMessageRemoved()
type ReceiveMessageRemoved struct{}

func (ReceiveMessageRemoved) isRemoveOutcome() {}

//goplus:variant (RemoveOutcome) RemoveRejected(Detail string)
type RemoveRejected struct {
	Detail string
}

func (RemoveRejected) isRemoveOutcome() {}

// RemoveOutcomeCases selects one handler per RemoveOutcome variant for RemoveOutcomeFold.
type RemoveOutcomeCases[R any] struct {
	ReceiveMessageRemoved func() R
	RemoveRejected        func(Detail string) R
}

// RemoveOutcomeFold reduces RemoveOutcome by one-level case analysis.
func RemoveOutcomeFold[R any](v RemoveOutcome, cs RemoveOutcomeCases[R]) R {
	switch m := any(v).(type) {
	case ReceiveMessageRemoved:
		return cs.ReceiveMessageRemoved()
	case RemoveRejected:
		return cs.RemoveRejected(m.Detail)
	default:
		panic("goplus: impossible enum value in RemoveOutcomeFold")
	}
}

// RemoveOutcomeEqOverrides carries optional per-variant hooks for RemoveOutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type RemoveOutcomeEqOverrides struct {
	ReceiveMessageRemoved func(x, y ReceiveMessageRemoved) (eq, handled bool)
	RemoveRejected        func(x, y RemoveRejected) (eq, handled bool)
}

// RemoveOutcomeEqualWith reports structural equality of a and b under ov.
func RemoveOutcomeEqualWith(a, b RemoveOutcome, ov RemoveOutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ReceiveMessageRemoved:
		y, ok := any(b).(ReceiveMessageRemoved)
		if !ok {
			return false
		}
		if ov.ReceiveMessageRemoved != nil {
			if eq, handled := ov.ReceiveMessageRemoved(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case RemoveRejected:
		y, ok := any(b).(RemoveRejected)
		if !ok {
			return false
		}
		if ov.RemoveRejected != nil {
			if eq, handled := ov.RemoveRejected(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// RemoveOutcomeEqual reports structural equality of a and b.
func RemoveOutcomeEqual(a, b RemoveOutcome) bool {
	return RemoveOutcomeEqualWith(a, b, RemoveOutcomeEqOverrides{})
}

type ReceivePeekEffect func() ReceiveOutcome
type ReceiveAdvanceEffect func() AdvanceOutcome
type ReceiveRemoveEffect func() RemoveOutcome

//goplus:enum ReceiveCapability
type ReceiveCapability interface{ isReceiveCapability() }

//goplus:variant (ReceiveCapability) ReceiveUnavailable()
type ReceiveUnavailable struct{}

func (ReceiveUnavailable) isReceiveCapability() {}

//goplus:variant (ReceiveCapability) ReceiveAllowed()
type ReceiveAllowed struct{}

func (ReceiveAllowed) isReceiveCapability() {}

// ReceiveCapabilityCases selects one handler per ReceiveCapability variant for ReceiveCapabilityFold.
type ReceiveCapabilityCases[R any] struct {
	ReceiveUnavailable func() R
	ReceiveAllowed     func() R
}

// ReceiveCapabilityFold reduces ReceiveCapability by one-level case analysis.
func ReceiveCapabilityFold[R any](v ReceiveCapability, cs ReceiveCapabilityCases[R]) R {
	switch any(v).(type) {
	case ReceiveUnavailable:
		return cs.ReceiveUnavailable()
	case ReceiveAllowed:
		return cs.ReceiveAllowed()
	default:
		panic("goplus: impossible enum value in ReceiveCapabilityFold")
	}
}

// ReceiveCapabilityEqOverrides carries optional per-variant hooks for ReceiveCapabilityEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ReceiveCapabilityEqOverrides struct {
	ReceiveUnavailable func(x, y ReceiveUnavailable) (eq, handled bool)
	ReceiveAllowed     func(x, y ReceiveAllowed) (eq, handled bool)
}

// ReceiveCapabilityEqualWith reports structural equality of a and b under ov.
func ReceiveCapabilityEqualWith(a, b ReceiveCapability, ov ReceiveCapabilityEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ReceiveUnavailable:
		y, ok := any(b).(ReceiveUnavailable)
		if !ok {
			return false
		}
		if ov.ReceiveUnavailable != nil {
			if eq, handled := ov.ReceiveUnavailable(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ReceiveAllowed:
		y, ok := any(b).(ReceiveAllowed)
		if !ok {
			return false
		}
		if ov.ReceiveAllowed != nil {
			if eq, handled := ov.ReceiveAllowed(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ReceiveCapabilityEqual reports structural equality of a and b.
func ReceiveCapabilityEqual(a, b ReceiveCapability) bool {
	return ReceiveCapabilityEqualWith(a, b, ReceiveCapabilityEqOverrides{})
}

type ReceiveEffects struct {
	Peek    ReceivePeekEffect
	Advance ReceiveAdvanceEffect
	Remove  ReceiveRemoveEffect
}

type MessagingEffects struct {
	Send    SendEffect
	Receive ReceiveEffects
}

type TimedMessagingEffects struct {
	Messaging MessagingEffects
	Timer     TimerEffects
}

type HostCapabilities struct {
	Send          SendCapability
	Receive       ReceiveCapability
	Timer         TimerCapability
	ExternalCalls ExternalCallCapability
	LinkedCode    LinkedCodeCapability
	send          SendEffect
	peek          ReceivePeekEffect
	advance       ReceiveAdvanceEffect
	remove        ReceiveRemoveEffect
	timerWait     TimerWaitEffect
	timerCancel   TimerMutationEffect
	timerFinish   TimerMutationEffect
	externalCall  ExternalCallEffect
	linkedCode    LinkedCodeEffect
}

func NoHostCapabilities() HostCapabilities {
	var unavailable SendCapability = SendUnavailable{}
	var receiveUnavailable ReceiveCapability = ReceiveUnavailable{}
	var timerUnavailable TimerCapability = TimerUnavailable{}
	var callsUnavailable ExternalCallCapability = ExternalCallsUnavailable{}
	var linkedCodeUnavailable LinkedCodeCapability = LinkedCodeUnavailable{}
	return HostCapabilities{
		Send:          unavailable,
		Receive:       receiveUnavailable,
		Timer:         timerUnavailable,
		ExternalCalls: callsUnavailable,
		LinkedCode:    linkedCodeUnavailable,
	}
}

// assayxport:unit gotp.vm.host-effects
func HostWithSend(effect SendEffect) result.Result[HostCapabilities, Failure] {
	if effect == nil {
		return result.Err[HostCapabilities, Failure]{Err: InvalidConfiguration{Detail: "send effect is nil"}}
	}
	var allowed SendCapability = SendAllowed{}
	var receiveUnavailable ReceiveCapability = ReceiveUnavailable{}
	var timerUnavailable TimerCapability = TimerUnavailable{}
	var callsUnavailable ExternalCallCapability = ExternalCallsUnavailable{}
	var linkedCodeUnavailable LinkedCodeCapability = LinkedCodeUnavailable{}
	return result.Ok[HostCapabilities, Failure]{Value: HostCapabilities{
		Send:          allowed,
		Receive:       receiveUnavailable,
		Timer:         timerUnavailable,
		ExternalCalls: callsUnavailable,
		LinkedCode:    linkedCodeUnavailable,
		send:          effect,
	}}
}

func HostWithReceive(effects ReceiveEffects) result.Result[HostCapabilities, Failure] {
	switch __gp_m0 := any(validateReceiveEffects(effects)).(type) {
	case result.Err[bool, Failure]:
		failure := __gp_m0.Err

		return result.Err[HostCapabilities, Failure]{Err: failure}
	case result.Ok[bool, Failure]:

		var sendUnavailable SendCapability = SendUnavailable{}
		var receiveAllowed ReceiveCapability = ReceiveAllowed{}
		var timerUnavailable TimerCapability = TimerUnavailable{}
		var callsUnavailable ExternalCallCapability = ExternalCallsUnavailable{}
		var linkedCodeUnavailable LinkedCodeCapability = LinkedCodeUnavailable{}
		return result.Ok[HostCapabilities, Failure]{Value: HostCapabilities{
			Send:          sendUnavailable,
			Receive:       receiveAllowed,
			Timer:         timerUnavailable,
			ExternalCalls: callsUnavailable,
			LinkedCode:    linkedCodeUnavailable,
			peek:          effects.Peek,
			advance:       effects.Advance,
			remove:        effects.Remove,
		}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func HostWithMessaging(effects MessagingEffects) result.Result[HostCapabilities, Failure] {
	if effects.Send == nil {
		return result.Err[HostCapabilities, Failure]{Err: InvalidConfiguration{Detail: "send effect is nil"}}
	}
	switch __gp_m1 := any(validateReceiveEffects(effects.Receive)).(type) {
	case result.Err[bool, Failure]:
		failure := __gp_m1.Err

		return result.Err[HostCapabilities, Failure]{Err: failure}
	case result.Ok[bool, Failure]:

		var sendAllowed SendCapability = SendAllowed{}
		var receiveAllowed ReceiveCapability = ReceiveAllowed{}
		var timerUnavailable TimerCapability = TimerUnavailable{}
		var callsUnavailable ExternalCallCapability = ExternalCallsUnavailable{}
		var linkedCodeUnavailable LinkedCodeCapability = LinkedCodeUnavailable{}
		return result.Ok[HostCapabilities, Failure]{Value: HostCapabilities{
			Send:          sendAllowed,
			Receive:       receiveAllowed,
			Timer:         timerUnavailable,
			ExternalCalls: callsUnavailable,
			LinkedCode:    linkedCodeUnavailable,
			send:          effects.Send,
			peek:          effects.Receive.Peek,
			advance:       effects.Receive.Advance,
			remove:        effects.Receive.Remove,
		}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// assayxport:unit gotp.vm.external-call-capability
func HostGrantExternalCalls(
	host HostCapabilities,
	effect ExternalCallEffect,
) result.Result[HostCapabilities, Failure] {
	if effect == nil {
		return result.Err[HostCapabilities, Failure]{Err: InvalidConfiguration{Detail: "external call effect is nil"}}
	}
	var allowed ExternalCallCapability = ExternalCallsAllowed{}
	host.ExternalCalls = allowed
	host.externalCall = effect
	return result.Ok[HostCapabilities, Failure]{Value: host}
}

// assayxport:unit gotp.vm.linked-code-capability
func HostGrantLinkedCode(
	host HostCapabilities,
	effect LinkedCodeEffect,
) result.Result[HostCapabilities, Failure] {
	if effect == nil {
		return result.Err[HostCapabilities, Failure]{Err: InvalidConfiguration{Detail: "linked code effect is nil"}}
	}
	var allowed LinkedCodeCapability = LinkedCodeAllowed{}
	host.LinkedCode = allowed
	host.linkedCode = effect
	return result.Ok[HostCapabilities, Failure]{Value: host}
}

// assayxport:unit gotp.vm.receive-timeout
func HostWithTimedMessaging(effects TimedMessagingEffects) result.Result[HostCapabilities, Failure] {
	switch __gp_m2 := any(HostWithMessaging(effects.Messaging)).(type) {
	case result.Err[HostCapabilities, Failure]:
		failure := __gp_m2.Err

		return result.Err[HostCapabilities, Failure]{Err: failure}
	case result.Ok[HostCapabilities, Failure]:
		host := __gp_m2.Value

		if effects.Timer.Wait == nil || effects.Timer.Cancel == nil || effects.Timer.Finish == nil {
			return result.Err[HostCapabilities, Failure]{Err: InvalidConfiguration{Detail: "timer effects must be complete"}}
		}
		var timerAllowed TimerCapability = TimerAllowed{}
		host.Timer = timerAllowed
		host.timerWait = effects.Timer.Wait
		host.timerCancel = effects.Timer.Cancel
		host.timerFinish = effects.Timer.Finish
		return result.Ok[HostCapabilities, Failure]{Value: host}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func validateReceiveEffects(effects ReceiveEffects) result.Result[bool, Failure] {
	if effects.Peek == nil || effects.Advance == nil || effects.Remove == nil {
		return result.Err[bool, Failure]{Err: InvalidConfiguration{Detail: "receive effects must be complete"}}
	}
	return result.Ok[bool, Failure]{Value: true}
}
