// Code generated by goplus from heap_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package vm

import (
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
)

func TestSmallIntegerRoundTripLaw(t *testing.T) {
	law := func(raw int64) bool {
		value := raw >> 3
		switch __gp_m0 := any(SmallInteger(value)).(type) {
		case result.Err[Word, Failure]:

			return false
		case result.Ok[Word, Failure]:
			word := __gp_m0.Value

			switch __gp_m1 := any(word.SmallInteger()).(type) {
			case option.Some[int64]:
				decoded := __gp_m1.Value

				return decoded == value
			case option.None[int64]:

				return false
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	switch __gp_m2 := any(result.Of(true, quick.Check(law, nil))).(type) {
	case result.Err[bool, error]:
		cause := __gp_m2.Err

		t.Fatal(cause)
	case result.Ok[bool, error]:

	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestProcessHeapStoresImmediateWord(t *testing.T) {
	switch __gp_m3 := any(NewProcessHeap(4096)).(type) {
	case result.Err[*ProcessHeap, Failure]:
		failure := __gp_m3.Err

		t.Fatal(Error(failure))
	case result.Ok[*ProcessHeap, Failure]:
		heap := __gp_m3.Value

		defer heap.Close()
		switch __gp_m4 := any(heap.Allocate(2)).(type) {
		case result.Err[HeapRef, Failure]:
			failure := __gp_m4.Err

			t.Fatal(Error(failure))
		case result.Ok[HeapRef, Failure]:
			reference := __gp_m4.Value

			switch __gp_m5 := any(SmallInteger(-42)).(type) {
			case result.Err[Word, Failure]:
				failure := __gp_m5.Err

				t.Fatal(Error(failure))
			case result.Ok[Word, Failure]:
				word := __gp_m5.Value

				switch __gp_m6 := any(heap.Store(reference, 1, word)).(type) {
				case result.Err[HeapMutation, Failure]:
					failure := __gp_m6.Err

					t.Fatal(Error(failure))
				case result.Ok[HeapMutation, Failure]:

				default:
					panic("goplus: impossible enum value in match")
				}
				switch __gp_m7 := any(heap.Load(reference, 1)).(type) {
				case result.Err[Word, Failure]:
					failure := __gp_m7.Err

					t.Fatal(Error(failure))
				case result.Ok[Word, Failure]:
					loaded := __gp_m7.Value

					switch __gp_m8 := any(loaded.SmallInteger()).(type) {
					case option.Some[int64]:
						value := __gp_m8.Value

						if value != -42 {
							t.Fatalf("loaded = %d", value)
						}
					case option.None[int64]:

						t.Fatal("loaded word is not a small integer")
					default:
						panic("goplus: impossible enum value in match")
					}
				default:
					panic("goplus: impossible enum value in match")
				}
				switch __gp_m9 := any(heap.Reset()).(type) {
				case result.Err[HeapMutation, Failure]:
					failure := __gp_m9.Err

					t.Fatal(Error(failure))
				case result.Ok[HeapMutation, Failure]:

				default:
					panic("goplus: impossible enum value in match")
				}
				switch any(heap.Load(reference, 1)).(type) {
				case result.Err[Word, Failure]:

				case result.Ok[Word, Failure]:

					t.Fatal("expired heap reference remained readable")
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}
