// Code generated by goplus from interpreter.gp. DO NOT EDIT.
//goplus:v v0.28.0

package vm

import (
	"fmt"
	"math/big"

	"goforge.dev/goplus/std/memory"
	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/term"
)

type MachineConfig struct {
	XRegisters    int
	StepLimit     int
	HeapBytes     int
	Atoms         map[uint64]string
	Literals      map[uint64]term.Term
	Imports       map[uint64]ExternalFunction
	Functions     map[uint64]beam.FunctionTemplate
	ModuleName    string
	Exports       map[ExternalFunction]uint64
	LinkedModules map[string]ModuleImage
}

type ModuleImage struct {
	Name      string
	Program   []beam.Instruction
	Atoms     map[uint64]string
	Literals  map[uint64]term.Term
	Imports   map[uint64]ExternalFunction
	Functions map[uint64]beam.FunctionTemplate
	Exports   map[ExternalFunction]uint64
}

type machineImage struct {
	name      string
	program   []beam.Instruction
	labels    map[uint64]int
	atoms     map[uint64]string
	literals  map[uint64]term.Term
	imports   map[uint64]ExternalFunction
	functions map[uint64]beam.FunctionTemplate
	exports   map[ExternalFunction]uint64
}

type RunResult struct {
	Value term.Term
	Steps int
}

//goplus:enum MachineMutation
type MachineMutation interface{ isMachineMutation() }

//goplus:variant (MachineMutation) MachineMutated()
type MachineMutated struct{}

func (MachineMutated) isMachineMutation() {}

// MachineMutationCases selects one handler per MachineMutation variant for MachineMutationFold.
type MachineMutationCases[R any] struct {
	MachineMutated func() R
}

// MachineMutationFold reduces MachineMutation by one-level case analysis.
func MachineMutationFold[R any](m MachineMutation, cs MachineMutationCases[R]) R {
	switch any(m).(type) {
	case MachineMutated:
		return cs.MachineMutated()
	default:
		panic("goplus: impossible enum value in MachineMutationFold")
	}
}

// MachineMutationEqOverrides carries optional per-variant hooks for MachineMutationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type MachineMutationEqOverrides struct {
	MachineMutated func(x, y MachineMutated) (eq, handled bool)
}

// MachineMutationEqualWith reports structural equality of a and b under ov.
func MachineMutationEqualWith(a, b MachineMutation, ov MachineMutationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case MachineMutated:
		y, ok := any(b).(MachineMutated)
		if !ok {
			return false
		}
		if ov.MachineMutated != nil {
			if eq, handled := ov.MachineMutated(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// MachineMutationEqual reports structural equality of a and b.
func MachineMutationEqual(a, b MachineMutation) bool {
	return MachineMutationEqualWith(a, b, MachineMutationEqOverrides{})
}

type returnFrame struct {
	pc        int
	image     *machineImage
	codeLeave func()
}

type Machine struct {
	program          []beam.Instruction
	labels           map[uint64]int
	x                memory.Buffer[option.Option[term.Term]]
	y                memory.Buffer[option.Option[term.Term]]
	atoms            map[uint64]string
	literals         map[uint64]term.Term
	imports          map[uint64]ExternalFunction
	functions        map[uint64]beam.FunctionTemplate
	returns          memory.Buffer[returnFrame]
	current          *machineImage
	currentCodeLeave func()
	root             *machineImage
	modules          map[string]*machineImage
	handlers         memory.Buffer[exceptionHandler]
	processMemory    *ProcessMemory
	nextHandler      uint64
	pc               int
	steps            int
	stepLimit        int
}

func NewMachine(
	program []beam.Instruction,
	config MachineConfig,
) result.Result[*Machine, Failure] {
	if config.XRegisters <= 0 {
		config.XRegisters = 256
	}
	if config.StepLimit <= 0 {
		config.StepLimit = 1_000_000
	}
	if config.HeapBytes <= 0 {
		config.HeapBytes = 1 << 20
	}
	labels := make(map[uint64]int)
	for index, instruction := range program {
		if instruction.Opcode.Name != "label" {
			continue
		}
		if len(instruction.Operands) != 1 {
			return result.Err[*Machine, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
				"label at instruction %d has %d operands",
				index,
				len(instruction.Operands),
			)}}
		}
		switch __gp_m0 := any(labelIndex(instruction.Operands[0])).(type) {
		case option.None[uint64]:

			return result.Err[*Machine, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
				"label at instruction %d is not a nonnegative uint64",
				index,
			)}}
		case option.Some[uint64]:
			label := __gp_m0.Value

			_, duplicate := labels[label]
			if duplicate {
				return result.Err[*Machine, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
					"duplicate label %d",
					label,
				)}}
			}
			labels[label] = index
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	registers := memory.NewBuffer[option.Option[term.Term]](config.XRegisters)
	for index := 0; index < config.XRegisters; index++ {
		registers.Append(option.None[term.Term]{})
	}
	moduleName := config.ModuleName
	if moduleName == "" {
		moduleName = "$root"
	}
	root := &machineImage{
		name:      moduleName,
		program:   append([]beam.Instruction(nil), program...),
		labels:    labels,
		atoms:     cloneAtomPool(config.Atoms),
		literals:  cloneLiteralPool(config.Literals),
		imports:   cloneImportPool(config.Imports),
		functions: cloneFunctionPool(config.Functions),
		exports:   cloneExportPool(config.Exports),
	}
	switch __gp_m1 := any(validateImageExports(root)).(type) {
	case result.Err[bool, Failure]:
		failure := __gp_m1.Err

		return result.Err[*Machine, Failure]{Err: failure}
	case result.Ok[bool, Failure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	modules := map[string]*machineImage{moduleName: root}
	for name, linked := range config.LinkedModules {
		if name == moduleName {
			return result.Err[*Machine, Failure]{Err: InvalidProgram{Detail: "linked module duplicates root module " + name}}
		}
		if linked.Name != "" && linked.Name != name {
			return result.Err[*Machine, Failure]{Err: InvalidProgram{Detail: "linked module name differs from its registry key"}}
		}
		linked.Name = name
		switch __gp_m2 := any(newMachineImage(linked)).(type) {
		case result.Err[*machineImage, Failure]:
			failure := __gp_m2.Err

			return result.Err[*Machine, Failure]{Err: failure}
		case result.Ok[*machineImage, Failure]:
			image := __gp_m2.Value

			modules[name] = image
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	var processMemory *ProcessMemory
	switch __gp_m3 := any(NewProcessMemory(config.HeapBytes)).(type) {
	case result.Err[*ProcessMemory, Failure]:
		failure := __gp_m3.Err

		return result.Err[*Machine, Failure]{Err: failure}
	case result.Ok[*ProcessMemory, Failure]:
		owned := __gp_m3.Value

		processMemory = owned
	default:
		panic("goplus: impossible enum value in match")
	}
	return result.Ok[*Machine, Failure]{Value: &Machine{
		program:       root.program,
		labels:        root.labels,
		x:             registers,
		y:             memory.NewBuffer[option.Option[term.Term]](64),
		returns:       memory.NewBuffer[returnFrame](32),
		handlers:      memory.NewBuffer[exceptionHandler](8),
		processMemory: processMemory,
		atoms:         root.atoms,
		literals:      root.literals,
		imports:       root.imports,
		functions:     root.functions,
		current:       root,
		root:          root,
		modules:       modules,
		stepLimit:     config.StepLimit,
	}}
}

func (machine *Machine) SetX(
	index int,
	value term.Term,
) result.Result[MachineMutation, Failure] {
	if index < 0 || index >= machine.x.Len() {
		return result.Err[MachineMutation, Failure]{Err: RegisterOutOfRange{Register: "x", Index: index}}
	}
	machine.x.Set(index, option.Some[term.Term]{Value: term.Clone(value)})
	return result.Ok[MachineMutation, Failure]{Value: MachineMutated{}}
}

func (machine *Machine) resetProcessMemory() {
	machine.releaseAllCode()
	for index := 0; index < machine.x.Len(); index++ {
		machine.x.Set(index, option.None[term.Term]{})
	}
	machine.y.Release()
	machine.returns.Release()
	machine.handlers.Release()
	if machine.processMemory != nil {
		machine.processMemory.Reset()
	}
}

func (machine *Machine) X(index int) result.Result[term.Term, Failure] {
	return machine.register(machine.x, "x", index)
}

func (machine *Machine) Run(entryLabel uint64) result.Result[RunResult, Failure] {
	var started result.Result[*Continuation, Failure] = machine.Start(entryLabel)
	switch __gp_m4 := any(started).(type) {
	case result.Err[*Continuation, Failure]:
		failure := __gp_m4.Err

		return result.Err[RunResult, Failure]{Err: failure}
	case result.Ok[*Continuation, Failure]:
		continuation := __gp_m4.Value

		var resumed result.Result[ExecutionSlice, Failure] = continuation.Resume(
			VMReductionBudget{value: machine.stepLimit},
		)
		switch __gp_m5 := any(resumed).(type) {
		case result.Err[ExecutionSlice, Failure]:
			failure := __gp_m5.Err

			return result.Err[RunResult, Failure]{Err: failure}
		case result.Ok[ExecutionSlice, Failure]:
			slice := __gp_m5.Value

			var execution ExecutionSlice = slice
			switch __gp_m6 := any(execution).(type) {
			case ExecutionSuspended:

				return result.Err[RunResult, Failure]{Err: StepLimitExceeded{Limit: machine.stepLimit}}
			case ExecutionWaiting:

				return result.Err[RunResult, Failure]{Err: InvalidProgram{Detail: "execution waited without a process scheduler"}}
			case ExecutionRaised:
				class := __gp_m6.Class
				reason := __gp_m6.Reason

				return result.Err[RunResult, Failure]{Err: RaisedException{Class: class, Reason: reason}}
			case ExecutionCompleted:
				value := __gp_m6.Value

				return result.Ok[RunResult, Failure]{Value: RunResult{Value: value, Steps: machine.steps}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) finish() result.Result[RunResult, Failure] {
	switch __gp_m7 := any(machine.X(0)).(type) {
	case result.Ok[term.Term, Failure]:
		value := __gp_m7.Value

		return result.Ok[RunResult, Failure]{Value: RunResult{Value: value, Steps: machine.steps}}
	case result.Err[term.Term, Failure]:
		failure := __gp_m7.Err

		return result.Err[RunResult, Failure]{Err: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) move(
	instruction beam.Instruction,
) result.Result[MachineMutation, Failure] {
	if len(instruction.Operands) != 2 {
		return result.Err[MachineMutation, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
			"move has %d operands",
			len(instruction.Operands),
		)}}
	}
	switch __gp_m8 := any(machine.resolve(instruction.Operands[0])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m8.Err

		return result.Err[MachineMutation, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m8.Value

		return machine.assign(instruction.Operands[1], value)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) resolve(
	operand beam.Operand,
) result.Result[term.Term, Failure] {
	switch __gp_m9 := any(operand).(type) {
	case beam.TypedRegisterOperand:
		register := __gp_m9.Register

		return machine.resolve(register)
	case beam.XRegisterOperand:
		index := __gp_m9.Index

		return machine.readIndexed(machine.x, "x", index)
	case beam.YRegisterOperand:
		index := __gp_m9.Index

		switch __gp_m10 := any(machine.yPosition(index)).(type) {
		case result.Ok[int, Failure]:
			position := __gp_m10.Value

			return machine.register(machine.y, "y", position)
		case result.Err[int, Failure]:
			failure := __gp_m10.Err

			return result.Err[term.Term, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case beam.UnsignedOperand:
		value := __gp_m9.Value

		return result.Ok[term.Term, Failure]{Value: integerTerm(value)}
	case beam.IntegerOperand:
		value := __gp_m9.Value

		return result.Ok[term.Term, Failure]{Value: integerTerm(value)}
	case beam.AtomOperand:
		index := __gp_m9.Index

		return machine.atomConstant(index)
	case beam.CharacterOperand:
		value := __gp_m9.Value

		return result.Ok[term.Term, Failure]{Value: integerTerm(value)}
	case beam.LiteralOperand:
		index := __gp_m9.Index

		return machine.literalConstant(index)
	default:

		return result.Err[term.Term, Failure]{Err: InvalidProgram{Detail: "operand is not a value"}}
	}
}

func (machine *Machine) assign(
	destination beam.Operand,
	value term.Term,
) result.Result[MachineMutation, Failure] {
	switch __gp_m11 := any(destination).(type) {
	case beam.TypedRegisterOperand:
		register := __gp_m11.Register

		return machine.assign(register, value)
	case beam.XRegisterOperand:
		index := __gp_m11.Index

		return machine.writeIndexed(&machine.x, "x", index, value)
	case beam.YRegisterOperand:
		index := __gp_m11.Index

		switch __gp_m12 := any(machine.yPosition(index)).(type) {
		case result.Err[int, Failure]:
			failure := __gp_m12.Err

			return result.Err[MachineMutation, Failure]{Err: failure}
		case result.Ok[int, Failure]:
			position := __gp_m12.Value

			machine.y.Set(position, option.Some[term.Term]{Value: term.Clone(value)})
			return result.Ok[MachineMutation, Failure]{Value: MachineMutated{}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:

		return result.Err[MachineMutation, Failure]{Err: InvalidProgram{Detail: "move destination is not a register"}}
	}
}

func (machine *Machine) readIndexed(
	registers memory.Buffer[option.Option[term.Term]],
	name string,
	index *big.Int,
) result.Result[term.Term, Failure] {
	switch __gp_m13 := any(registerIndex(index)).(type) {
	case option.None[uint64]:

		return result.Err[term.Term, Failure]{Err: InvalidProgram{Detail: name + " register index is not uint64"}}
	case option.Some[uint64]:
		value := __gp_m13.Value

		if value > uint64(maxInt()) {
			return result.Err[term.Term, Failure]{Err: RegisterOutOfRange{Register: name, Index: maxInt()}}
		}
		return machine.register(registers, name, int(value))
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) writeIndexed(
	registers *memory.Buffer[option.Option[term.Term]],
	name string,
	index *big.Int,
	value term.Term,
) result.Result[MachineMutation, Failure] {
	switch __gp_m14 := any(registerIndex(index)).(type) {
	case option.None[uint64]:

		return result.Err[MachineMutation, Failure]{Err: InvalidProgram{Detail: name + " register index is not uint64"}}
	case option.Some[uint64]:
		position := __gp_m14.Value

		if position >= uint64(registers.Len()) {
			return result.Err[MachineMutation, Failure]{Err: RegisterOutOfRange{Register: name, Index: int(position)}}
		}
		registers.Set(int(position), option.Some[term.Term]{Value: term.Clone(value)})
		return result.Ok[MachineMutation, Failure]{Value: MachineMutated{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) register(
	registers memory.Buffer[option.Option[term.Term]],
	name string,
	index int,
) result.Result[term.Term, Failure] {
	if index < 0 || index >= registers.Len() {
		return result.Err[term.Term, Failure]{Err: RegisterOutOfRange{Register: name, Index: index}}
	}
	switch __gp_m15 := any(registers.At(index)).(type) {
	case option.None[option.Option[term.Term]]:
		return result.Err[term.Term, Failure]{Err: RegisterOutOfRange{Register: name, Index: index}}
	case option.Some[option.Option[term.Term]]:
		slot := __gp_m15.Value
		switch __gp_m16 := any(slot).(type) {
		case option.Some[term.Term]:
			value := __gp_m16.Value

			return result.Ok[term.Term, Failure]{Value: term.Clone(value)}
		case option.None[term.Term]:

			return result.Err[term.Term, Failure]{Err: UninitializedRegister{Register: name, Index: index}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) yPosition(index *big.Int) result.Result[int, Failure] {
	switch __gp_m17 := any(registerIndex(index)).(type) {
	case option.None[uint64]:

		return result.Err[int, Failure]{Err: InvalidProgram{Detail: "y register index is not uint64"}}
	case option.Some[uint64]:
		value := __gp_m17.Value

		if value >= uint64(machine.y.Len()) {
			return result.Err[int, Failure]{Err: RegisterOutOfRange{Register: "y", Index: int(value)}}
		}
		return result.Ok[int, Failure]{Value: machine.y.Len() - 1 - int(value)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) instructionLabel(
	instruction beam.Instruction,
	operandIndex int,
) result.Result[int, Failure] {
	if operandIndex < 0 || operandIndex >= len(instruction.Operands) {
		return result.Err[int, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
			"%s is missing label operand %d",
			instruction.Opcode.Name,
			operandIndex,
		)}}
	}
	switch __gp_m18 := any(labelIndex(instruction.Operands[operandIndex])).(type) {
	case option.None[uint64]:

		return result.Err[int, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
			"%s operand %d is not a label",
			instruction.Opcode.Name,
			operandIndex,
		)}}
	case option.Some[uint64]:
		label := __gp_m18.Value

		target, present := machine.labels[label]
		switch __gp_m19 := any(option.Of(target, present)).(type) {
		case option.Some[int]:
			position := __gp_m19.Value

			return result.Ok[int, Failure]{Value: position + 1}
		case option.None[int]:

			return result.Err[int, Failure]{Err: MissingLabel{Label: label}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) allocate(
	instruction beam.Instruction,
	operandIndex int,
) result.Result[MachineMutation, Failure] {
	switch __gp_m20 := any(allocationCount(instruction, operandIndex)).(type) {
	case result.Err[int, Failure]:
		failure := __gp_m20.Err

		return result.Err[MachineMutation, Failure]{Err: failure}
	case result.Ok[int, Failure]:
		count := __gp_m20.Value

		for index := 0; index < count; index++ {
			machine.y.Append(option.None[term.Term]{})
		}
		return result.Ok[MachineMutation, Failure]{Value: MachineMutated{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (machine *Machine) deallocate(
	instruction beam.Instruction,
	operandIndex int,
) result.Result[MachineMutation, Failure] {
	switch __gp_m21 := any(allocationCount(instruction, operandIndex)).(type) {
	case result.Err[int, Failure]:
		failure := __gp_m21.Err

		return result.Err[MachineMutation, Failure]{Err: failure}
	case result.Ok[int, Failure]:
		count := __gp_m21.Value

		if count > machine.y.Len() {
			return result.Err[MachineMutation, Failure]{Err: InvalidProgram{Detail: "invalid deallocation count"}}
		}
		machine.y.Truncate(machine.y.Len() - count)
		return result.Ok[MachineMutation, Failure]{Value: MachineMutated{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func allocationCount(
	instruction beam.Instruction,
	operandIndex int,
) result.Result[int, Failure] {
	if operandIndex < 0 || operandIndex >= len(instruction.Operands) {
		return result.Err[int, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
			"%s is missing allocation operand",
			instruction.Opcode.Name,
		)}}
	}
	switch __gp_m22 := any(instruction.Operands[operandIndex]).(type) {
	case beam.UnsignedOperand:
		value := __gp_m22.Value

		switch __gp_m23 := any(registerIndex(value)).(type) {
		case option.Some[uint64]:
			count := __gp_m23.Value

			if count <= 1_000_000 {
				return result.Ok[int, Failure]{Value: int(count)}
			}
		case option.None[uint64]:

		default:
			panic("goplus: impossible enum value in match")
		}
	default:

	}
	return result.Err[int, Failure]{Err: InvalidProgram{Detail: "invalid allocation count"}}
}

func labelIndex(operand beam.Operand) option.Option[uint64] {
	switch __gp_m24 := any(operand).(type) {
	case beam.LabelOperand:
		index := __gp_m24.Index

		return registerIndex(index)
	case beam.UnsignedOperand:
		index := __gp_m24.Value

		return registerIndex(index)
	default:

		return option.None[uint64]{}
	}
}

func registerIndex(index *big.Int) option.Option[uint64] {
	if index.Sign() < 0 || !index.IsUint64() {
		return option.None[uint64]{}
	}
	return option.Some[uint64]{Value: index.Uint64()}
}

func maxInt() int {
	return int(^uint(0) >> 1)
}

func integerTerm(value *big.Int) term.Term {
	if value.IsInt64() {
		return term.Integer(value.Int64())
	}
	return term.MustBigInteger(value)
}

func (machine *Machine) atomConstant(index *big.Int) result.Result[term.Term, Failure] {
	if !index.IsUint64() {
		return result.Err[term.Term, Failure]{Err: InvalidProgram{Detail: "atom index is not uint64"}}
	}
	position := index.Uint64()
	if position == 0 {
		return result.Ok[term.Term, Failure]{Value: term.List()}
	}
	name, present := machine.atoms[position]
	if !present {
		return result.Err[term.Term, Failure]{Err: MissingConstant{Kind: "atom", Index: position}}
	}
	return result.Ok[term.Term, Failure]{Value: term.MustAtom(name)}
}

func (machine *Machine) literalConstant(index *big.Int) result.Result[term.Term, Failure] {
	if !index.IsUint64() {
		return result.Err[term.Term, Failure]{Err: InvalidProgram{Detail: "literal index is not uint64"}}
	}
	position := index.Uint64()
	value, present := machine.literals[position]
	if !present {
		return result.Err[term.Term, Failure]{Err: MissingConstant{Kind: "literal", Index: position}}
	}
	return result.Ok[term.Term, Failure]{Value: term.Clone(value)}
}

func cloneAtomPool(values map[uint64]string) map[uint64]string {
	cloned := make(map[uint64]string, len(values))
	for index, value := range values {
		cloned[index] = value
	}
	return cloned
}

func cloneLiteralPool(values map[uint64]term.Term) map[uint64]term.Term {
	cloned := make(map[uint64]term.Term, len(values))
	for index, value := range values {
		cloned[index] = term.Clone(value)
	}
	return cloned
}

func cloneImportPool(source map[uint64]ExternalFunction) map[uint64]ExternalFunction {
	cloned := make(map[uint64]ExternalFunction, len(source))
	for index, target := range source {
		cloned[index] = target
	}
	return cloned
}

func cloneFunctionPool(source map[uint64]beam.FunctionTemplate) map[uint64]beam.FunctionTemplate {
	cloned := make(map[uint64]beam.FunctionTemplate, len(source))
	for index, function := range source {
		cloned[index] = function
	}
	return cloned
}

func cloneExportPool(source map[ExternalFunction]uint64) map[ExternalFunction]uint64 {
	cloned := make(map[ExternalFunction]uint64, len(source))
	for target, label := range source {
		cloned[target] = label
	}
	return cloned
}

func labelsForProgram(program []beam.Instruction) result.Result[map[uint64]int, Failure] {
	labels := make(map[uint64]int)
	for index, instruction := range program {
		if instruction.Opcode.Name != "label" {
			continue
		}
		if len(instruction.Operands) != 1 {
			return result.Err[map[uint64]int, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
				"label at instruction %d has %d operands",
				index,
				len(instruction.Operands),
			)}}
		}
		switch __gp_m25 := any(labelIndex(instruction.Operands[0])).(type) {
		case option.None[uint64]:

			return result.Err[map[uint64]int, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
				"label at instruction %d is not a nonnegative uint64",
				index,
			)}}
		case option.Some[uint64]:
			label := __gp_m25.Value

			if _, duplicate := labels[label]; duplicate {
				return result.Err[map[uint64]int, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf("duplicate label %d", label)}}
			}
			labels[label] = index
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return result.Ok[map[uint64]int, Failure]{Value: labels}
}

func newMachineImage(config ModuleImage) result.Result[*machineImage, Failure] {
	if config.Name == "" {
		return result.Err[*machineImage, Failure]{Err: InvalidProgram{Detail: "linked module name is empty"}}
	}
	switch __gp_m26 := any(labelsForProgram(config.Program)).(type) {
	case result.Err[map[uint64]int, Failure]:
		failure := __gp_m26.Err

		return result.Err[*machineImage, Failure]{Err: failure}
	case result.Ok[map[uint64]int, Failure]:
		labels := __gp_m26.Value

		image := &machineImage{
			name:      config.Name,
			program:   append([]beam.Instruction(nil), config.Program...),
			labels:    labels,
			atoms:     cloneAtomPool(config.Atoms),
			literals:  cloneLiteralPool(config.Literals),
			imports:   cloneImportPool(config.Imports),
			functions: cloneFunctionPool(config.Functions),
			exports:   cloneExportPool(config.Exports),
		}
		switch __gp_m27 := any(validateImageExports(image)).(type) {
		case result.Err[bool, Failure]:
			failure := __gp_m27.Err

			return result.Err[*machineImage, Failure]{Err: failure}
		case result.Ok[bool, Failure]:

			return result.Ok[*machineImage, Failure]{Value: image}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func validateImageExports(image *machineImage) result.Result[bool, Failure] {
	for target, label := range image.exports {
		if target.Module != image.name {
			return result.Err[bool, Failure]{Err: InvalidProgram{Detail: "module export identity differs from image name"}}
		}
		if _, present := image.labels[label]; !present {
			return result.Err[bool, Failure]{Err: MissingLabel{Label: label}}
		}
	}
	return result.Ok[bool, Failure]{Value: true}
}

func (machine *Machine) activate(image *machineImage) {
	machine.current = image
	machine.program = image.program
	machine.labels = image.labels
	machine.atoms = image.atoms
	machine.literals = image.literals
	machine.imports = image.imports
	machine.functions = image.functions
}

func (machine *Machine) pushReturn(pc int) {
	machine.returns.Append(returnFrame{pc: pc, image: machine.current, codeLeave: machine.currentCodeLeave})
}

func (machine *Machine) returnToCaller() bool {
	if machine.returns.Len() == 0 {
		machine.leaveCurrentCode()
		return false
	}
	last := machine.returns.Len() - 1
	var frame returnFrame
	switch __gp_m28 := any(machine.returns.Remove(last)).(type) {
	case option.None[returnFrame]:
		return false
	case option.Some[returnFrame]:
		found := __gp_m28.Value
		frame = found
	default:
		panic("goplus: impossible enum value in match")
	}
	machine.leaveCurrentCode()
	machine.activate(frame.image)
	machine.currentCodeLeave = frame.codeLeave
	machine.pc = frame.pc
	return true
}

func (machine *Machine) activateLinkedCode(image *machineImage, leave func()) {
	machine.activate(image)
	machine.currentCodeLeave = leave
}

func (machine *Machine) leaveCurrentCode() {
	if machine.currentCodeLeave != nil {
		leave := machine.currentCodeLeave
		machine.currentCodeLeave = nil
		leave()
	}
}

func (machine *Machine) releaseAllCode() {
	machine.leaveCurrentCode()
	for index := machine.returns.Len() - 1; index >= 0; index-- {
		switch __gp_m29 := any(machine.returns.At(index)).(type) {
		case option.Some[returnFrame]:
			frame := __gp_m29.Value
			if frame.codeLeave != nil {
				frame.codeLeave()
			}
		case option.None[returnFrame]:
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	machine.returns.Reset()
}
