// Code generated by goplus from selective_receive_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package vm

import (
	"testing"

	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/term"
)

// assayxport:unit gotp.vm.selective-receive-laws
func TestSelectiveReceiveWaitsAndResumes(t *testing.T) {
	messages := []term.Term{}
	cursor := 0
	removed := 0
	host := mustReceiveHost(t, &messages, &cursor, &removed)
	program := []beam.Instruction{
		instruction("label", label(1)),
		instruction("loop_rec", label(2), xregister(0)),
		instruction("remove_message"),
		instruction("return"),
		instruction("label", label(2)),
		instruction("wait", label(1)),
	}
	switch __gp_m0 := any(NewMachine(program, MachineConfig{})).(type) {
	case result.Err[*Machine, Failure]:
		failure := __gp_m0.Err

		t.Fatal(Error(failure))
	case result.Ok[*Machine, Failure]:
		machine := __gp_m0.Value

		switch __gp_m1 := any(machine.Start(1)).(type) {
		case result.Err[*Continuation, Failure]:
			failure := __gp_m1.Err

			t.Fatal(Error(failure))
		case result.Ok[*Continuation, Failure]:
			continuation := __gp_m1.Value

			budget := mustVMReceiveBudget(t, 1)
			switch __gp_m2 := any(continuation.ResumeWithHost(budget, host)).(type) {
			case result.Err[ExecutionSlice, Failure]:
				failure := __gp_m2.Err

				t.Fatal(Error(failure))
			case result.Ok[ExecutionSlice, Failure]:
				slice := __gp_m2.Value

				var execution ExecutionSlice = slice
				switch any(execution).(type) {
				case ExecutionWaiting:

				default:

					t.Fatal("empty receive did not wait")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
			messages = append(messages, term.Integer(42))
			switch __gp_m4 := any(continuation.ResumeWithHost(budget, host)).(type) {
			case result.Err[ExecutionSlice, Failure]:
				failure := __gp_m4.Err

				t.Fatal(Error(failure))
			case result.Ok[ExecutionSlice, Failure]:
				slice := __gp_m4.Value

				var execution ExecutionSlice = slice
				switch __gp_m5 := any(execution).(type) {
				case ExecutionCompleted:
					value := __gp_m5.Value

					if !term.Equal(value, term.Integer(42)) || removed != 1 {
						t.Fatalf("value=%#v removed=%d", value, removed)
					}
				default:

					t.Fatal("resumed receive did not complete")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestLoopRecEndAdvancesAndConsumesReduction(t *testing.T) {
	messages := []term.Term{term.Integer(1), term.Integer(2)}
	cursor := 0
	removed := 0
	host := mustReceiveHost(t, &messages, &cursor, &removed)
	program := []beam.Instruction{
		instruction("label", label(1)),
		instruction("loop_rec", label(3), xregister(0)),
		instruction("loop_rec_end", label(2)),
		instruction("label", label(2)),
		instruction("loop_rec", label(3), xregister(0)),
		instruction("remove_message"),
		instruction("return"),
		instruction("label", label(3)),
		instruction("wait", label(1)),
	}
	switch __gp_m6 := any(NewMachine(program, MachineConfig{})).(type) {
	case result.Err[*Machine, Failure]:
		failure := __gp_m6.Err

		t.Fatal(Error(failure))
	case result.Ok[*Machine, Failure]:
		machine := __gp_m6.Value

		switch __gp_m7 := any(machine.Start(1)).(type) {
		case result.Err[*Continuation, Failure]:
			failure := __gp_m7.Err

			t.Fatal(Error(failure))
		case result.Ok[*Continuation, Failure]:
			continuation := __gp_m7.Value

			switch __gp_m8 := any(continuation.ResumeWithHost(mustVMReceiveBudget(t, 2), host)).(type) {
			case result.Err[ExecutionSlice, Failure]:
				failure := __gp_m8.Err

				t.Fatal(Error(failure))
			case result.Ok[ExecutionSlice, Failure]:
				slice := __gp_m8.Value

				var execution ExecutionSlice = slice
				switch __gp_m9 := any(execution).(type) {
				case ExecutionCompleted:
					value := __gp_m9.Value
					progress := __gp_m9.Progress

					if !term.Equal(value, term.Integer(2)) || progress.Reductions != 2 ||
						len(messages) != 1 || !term.Equal(messages[0], term.Integer(1)) {
						t.Fatalf("value=%#v progress=%#v messages=%#v", value, progress, messages)
					}
				default:

					t.Fatal("selective receive did not complete")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func mustReceiveHost(
	t *testing.T,
	messages *[]term.Term,
	cursor *int,
	removed *int,
) HostCapabilities {
	t.Helper()
	switch __gp_m10 := any(HostWithReceive(ReceiveEffects{
		Peek: func() ReceiveOutcome {
			if *cursor >= len(*messages) {
				return ReceiveEmpty{}
			}
			return ReceiveMessage{Value: term.Clone((*messages)[*cursor])}
		},
		Advance: func() AdvanceOutcome {
			if *cursor >= len(*messages) {
				return AdvanceRejected{Detail: "no current message"}
			}
			(*cursor)++
			return ReceiveCursorAdvanced{}
		},
		Remove: func() RemoveOutcome {
			if *cursor >= len(*messages) {
				return RemoveRejected{Detail: "no current message"}
			}
			copy((*messages)[*cursor:], (*messages)[*cursor+1:])
			*messages = (*messages)[:len(*messages)-1]
			*cursor = 0
			(*removed)++
			return ReceiveMessageRemoved{}
		},
	})).(type) {
	case result.Err[HostCapabilities, Failure]:
		failure := __gp_m10.Err

		t.Fatal(Error(failure))
		return NoHostCapabilities()
	case result.Ok[HostCapabilities, Failure]:
		host := __gp_m10.Value

		return host
	default:
		panic("goplus: impossible enum value in match")
	}
}

func mustVMReceiveBudget(t *testing.T, value int) VMReductionBudget {
	t.Helper()
	switch __gp_m11 := any(NewVMReductionBudget(value)).(type) {
	case result.Err[VMReductionBudget, Failure]:
		failure := __gp_m11.Err

		t.Fatal(Error(failure))
		return VMReductionBudget{}
	case result.Ok[VMReductionBudget, Failure]:
		budget := __gp_m11.Value

		return budget
	default:
		panic("goplus: impossible enum value in match")
	}
}
