// Code generated by goplus from term_instructions.gp. DO NOT EDIT.
//goplus:v v0.28.0

package vm

import (
	"fmt"
	"math"
	"math/big"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/term"
)

// assayxport:unit gotp.vm.core-term-instructions
func executeCoreTermInstruction(
	machine *Machine,
	instruction beam.Instruction,
) result.Result[instructionOutcome, Failure] {
	switch instruction.Opcode.Name {
	case "line":
		machine.pc++
	case "test_heap":
		switch __gp_m0 := any(heapWordCount(instruction, 0)).(type) {
		case result.Err[int, Failure]:
			failure := __gp_m0.Err
			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[int, Failure]:
			words := __gp_m0.Value

			switch __gp_m1 := any(machine.ensureHeap(words)).(type) {
			case result.Err[HeapMutation, Failure]:
				failure := __gp_m1.Err
				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[HeapMutation, Failure]:
				machine.pc++
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "allocate_heap":
		switch __gp_m2 := any(heapWordCount(instruction, 1)).(type) {
		case result.Err[int, Failure]:
			failure := __gp_m2.Err
			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[int, Failure]:
			words := __gp_m2.Value

			switch __gp_m3 := any(machine.ensureHeap(words)).(type) {
			case result.Err[HeapMutation, Failure]:
				failure := __gp_m3.Err
				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[HeapMutation, Failure]:

				switch __gp_m4 := any(machine.allocate(instruction, 0)).(type) {
				case result.Err[MachineMutation, Failure]:
					failure := __gp_m4.Err
					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[MachineMutation, Failure]:
					machine.pc++
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	case "trim":
		switch __gp_m5 := any(machine.deallocate(instruction, 0)).(type) {
		case result.Err[MachineMutation, Failure]:
			failure := __gp_m5.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[MachineMutation, Failure]:

			machine.pc++
		default:
			panic("goplus: impossible enum value in match")
		}
	case "init_yregs":
		return initializeYRegisters(machine, instruction)
	case "swap":
		return swapRegisters(machine, instruction)
	case "get_list":
		return getList(machine, instruction, false)
	case "get_hd":
		return getList(machine, instruction, true)
	case "get_tl":
		return getListTail(machine, instruction)
	case "put_list":
		return putList(machine, instruction)
	case "get_tuple_element":
		return getTupleElement(machine, instruction)
	case "has_map_fields":
		return hasMapFields(machine, instruction)
	case "get_map_elements":
		return getMapElements(machine, instruction)
	case "put_map_assoc":
		return putMap(machine, instruction, false)
	case "put_map_exact":
		return putMap(machine, instruction, true)
	case "put_tuple2":
		return putTuple(machine, instruction)
	case "select_val":
		return selectValue(machine, instruction)
	case "select_tuple_arity":
		return selectTupleArity(machine, instruction)
	case "test_arity":
		return testArity(machine, instruction)
	case "is_tagged_tuple":
		return testTaggedTuple(machine, instruction)
	case "is_atom", "is_binary", "is_bitstr", "is_boolean", "is_float", "is_integer",
		"is_list", "is_map", "is_nil", "is_nonempty_list", "is_number", "is_pid",
		"is_port", "is_reference", "is_tuple":
		return testTermKind(machine, instruction)
	case "is_eq", "is_eq_exact", "is_ne", "is_ne_exact":
		return testEquality(machine, instruction)
	default:
		return result.Err[instructionOutcome, Failure]{Err: UnsupportedOpcode{Name: instruction.Opcode.Name, Arity: instruction.Opcode.Arity, Offset: instruction.Offset}}
	}
	return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
}

func hasMapFields(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 3 {
		return malformedCoreInstruction(instruction)
	}
	var keys []beam.Operand
	switch __gp_m6 := any(instruction.Operands[2]).(type) {
	case beam.ListOperand:
		found := __gp_m6.Items
		keys = found
	default:
		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "has_map_fields keys are not a list operand"}}
	}
	switch __gp_m7 := any(machine.resolve(instruction.Operands[1])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m7.Err
		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m7.Value

		switch __gp_m8 := any(value).(type) {
		case term.MapTerm:
			entries := __gp_m8.Entries

			for _, keyOperand := range keys {
				var key term.Term
				switch __gp_m9 := any(machine.resolve(keyOperand)).(type) {
				case result.Err[term.Term, Failure]:
					failure := __gp_m9.Err
					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[term.Term, Failure]:
					found := __gp_m9.Value
					key = found
				default:
					panic("goplus: impossible enum value in match")
				}
				present := false
				for _, entry := range entries {
					if term.Equal(entry.Key, key) {
						present = true
						break
					}
				}
				if !present {
					return branchOnTest(machine, instruction.Operands[0], false)
				}
			}
			return branchOnTest(machine, instruction.Operands[0], true)
		default:
			return branchOnTest(machine, instruction.Operands[0], false)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func getMapElements(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 3 {
		return malformedCoreInstruction(instruction)
	}
	var pairs []beam.Operand
	switch __gp_m10 := any(instruction.Operands[2]).(type) {
	case beam.ListOperand:
		found := __gp_m10.Items
		pairs = found
	default:
		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "get_map_elements pairs are not a list operand"}}
	}
	if len(pairs)%2 != 0 {
		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "get_map_elements pairs are not key/destination pairs"}}
	}
	switch __gp_m11 := any(machine.resolve(instruction.Operands[1])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m11.Err
		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		source := __gp_m11.Value

		switch __gp_m12 := any(source).(type) {
		case term.MapTerm:
			entries := __gp_m12.Entries

			destinations := make([]beam.Operand, 0, len(pairs)/2)
			values := make([]term.Term, 0, len(pairs)/2)
			for index := 0; index < len(pairs); index += 2 {
				var key term.Term
				switch __gp_m13 := any(machine.resolve(pairs[index])).(type) {
				case result.Err[term.Term, Failure]:
					failure := __gp_m13.Err
					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[term.Term, Failure]:
					found := __gp_m13.Value
					key = found
				default:
					panic("goplus: impossible enum value in match")
				}
				found := false
				for _, entry := range entries {
					if term.Equal(entry.Key, key) {
						destinations = append(destinations, pairs[index+1])
						values = append(values, entry.Value)
						found = true
						break
					}
				}
				if !found {
					return branchOnTest(machine, instruction.Operands[0], false)
				}
			}
			for index, destination := range destinations {
				switch __gp_m14 := any(machine.assign(destination, values[index])).(type) {
				case result.Err[MachineMutation, Failure]:
					failure := __gp_m14.Err
					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[MachineMutation, Failure]:
				default:
					panic("goplus: impossible enum value in match")
				}
			}
			machine.pc++
			return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
		default:
			return branchOnTest(machine, instruction.Operands[0], false)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func putMap(machine *Machine, instruction beam.Instruction, exact bool) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 5 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m15 := any(allocationCount(instruction, 3)).(type) {
	case result.Err[int, Failure]:
		failure := __gp_m15.Err
		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[int, Failure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	var pairs []beam.Operand
	switch __gp_m16 := any(instruction.Operands[4]).(type) {
	case beam.ListOperand:
		found := __gp_m16.Items
		pairs = found
	default:
		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "put_map pairs are not a list operand"}}
	}
	if len(pairs)%2 != 0 {
		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "put_map pairs are not key/value pairs"}}
	}
	switch __gp_m17 := any(machine.resolve(instruction.Operands[1])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m17.Err
		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		source := __gp_m17.Value

		switch __gp_m18 := any(source).(type) {
		case term.MapTerm:
			sourceEntries := __gp_m18.Entries

			entries := append([]term.MapEntry(nil), sourceEntries...)
			for index := 0; index < len(pairs); index += 2 {
				var key term.Term
				var value term.Term
				switch __gp_m19 := any(machine.resolve(pairs[index])).(type) {
				case result.Err[term.Term, Failure]:
					failure := __gp_m19.Err
					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[term.Term, Failure]:
					found := __gp_m19.Value
					key = found
				default:
					panic("goplus: impossible enum value in match")
				}
				switch __gp_m20 := any(machine.resolve(pairs[index+1])).(type) {
				case result.Err[term.Term, Failure]:
					failure := __gp_m20.Err
					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[term.Term, Failure]:
					found := __gp_m20.Value
					value = found
				default:
					panic("goplus: impossible enum value in match")
				}
				position := -1
				for candidate, entry := range entries {
					if term.Equal(entry.Key, key) {
						position = candidate
						break
					}
				}
				if position < 0 {
					if exact {
						return branchOnTest(machine, instruction.Operands[0], false)
					}
					entries = append(entries, term.MapEntry{Key: key, Value: value})
				} else {
					entries[position] = term.MapEntry{Key: key, Value: value}
				}
			}
			switch __gp_m21 := any(term.Map(entries)).(type) {
			case result.Err[term.Term, term.ValidationFailure]:
				cause := __gp_m21.Err
				return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: term.Error(cause)}}
			case result.Ok[term.Term, term.ValidationFailure]:
				updated := __gp_m21.Value

				switch __gp_m22 := any(machine.trackHeapTerm(updated, 3+2*len(entries))).(type) {
				case result.Err[HeapMutation, Failure]:
					failure := __gp_m22.Err
					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[HeapMutation, Failure]:
				default:
					panic("goplus: impossible enum value in match")
				}
				switch __gp_m23 := any(machine.assign(instruction.Operands[2], updated)).(type) {
				case result.Err[MachineMutation, Failure]:
					failure := __gp_m23.Err
					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[MachineMutation, Failure]:
					machine.pc++
					return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			return branchOnTest(machine, instruction.Operands[0], false)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func testTermKind(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 2 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m24 := any(machine.resolve(instruction.Operands[1])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m24.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m24.Value

		matched := false
		var kind term.Kind = term.TermKind(value)
		switch any(kind).(type) {
		case term.InvalidKind:

		case term.IntegerKind:

			matched = instruction.Opcode.Name == "is_integer" || instruction.Opcode.Name == "is_number"
		case term.FloatKind:

			matched = instruction.Opcode.Name == "is_float" || instruction.Opcode.Name == "is_number"
		case term.AtomKind:

			matched = instruction.Opcode.Name == "is_atom" ||
				(instruction.Opcode.Name == "is_boolean" && isBooleanAtom(value))
		case term.BinaryKind:

			matched = instruction.Opcode.Name == "is_binary" || instruction.Opcode.Name == "is_bitstr"
		case term.TupleKind:

			matched = instruction.Opcode.Name == "is_tuple"
		case term.ListKind:

			matched = listKindMatches(instruction.Opcode.Name, value)
		case term.MapKind:

			matched = instruction.Opcode.Name == "is_map"
		case term.PIDKind:

			matched = instruction.Opcode.Name == "is_pid"
		case term.ReferenceKind:

			matched = instruction.Opcode.Name == "is_reference"
		case term.FunKind:

		case term.PortKind:

			matched = instruction.Opcode.Name == "is_port"
		default:
			panic("goplus: impossible enum value in match")
		}
		return branchOnTest(machine, instruction.Operands[0], matched)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func listKindMatches(name string, value term.Term) bool {
	switch __gp_m26 := any(value).(type) {
	case term.ProperListTerm:
		elements := __gp_m26.Elements

		if name == "is_nil" {
			return len(elements) == 0
		}
		if name == "is_nonempty_list" {
			return len(elements) > 0
		}
		return name == "is_list"
	case term.ImproperListTerm:
		elements := __gp_m26.Elements

		return (name == "is_list" || name == "is_nonempty_list") && len(elements) > 0
	default:

		return false
	}
}

func isBooleanAtom(value term.Term) bool {
	switch __gp_m27 := any(term.AtomName(value)).(type) {
	case option.None[string]:

		return false
	case option.Some[string]:
		name := __gp_m27.Value

		return name == "true" || name == "false"
	default:
		panic("goplus: impossible enum value in match")
	}
}

func testArity(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 3 {
		return malformedCoreInstruction(instruction)
	}
	var wanted uint64
	switch __gp_m28 := any(beam.Uint64(instruction.Operands[2])).(type) {
	case option.None[uint64]:

		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "test_arity arity is not uint64"}}
	case option.Some[uint64]:
		value := __gp_m28.Value

		wanted = value
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m29 := any(machine.resolve(instruction.Operands[1])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m29.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m29.Value

		matched := false
		switch __gp_m30 := any(value).(type) {
		case term.TupleTerm:
			elements := __gp_m30.Elements

			matched = uint64(len(elements)) == wanted
		default:

		}
		return branchOnTest(machine, instruction.Operands[0], matched)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func testTaggedTuple(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 4 {
		return malformedCoreInstruction(instruction)
	}
	var wanted uint64
	switch __gp_m31 := any(beam.Uint64(instruction.Operands[2])).(type) {
	case option.None[uint64]:

		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "is_tagged_tuple arity is not uint64"}}
	case option.Some[uint64]:
		value := __gp_m31.Value

		wanted = value
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m32 := any(machine.resolve(instruction.Operands[1])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m32.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m32.Value

		switch __gp_m33 := any(machine.resolve(instruction.Operands[3])).(type) {
		case result.Err[term.Term, Failure]:
			failure := __gp_m33.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[term.Term, Failure]:
			tag := __gp_m33.Value

			matched := false
			switch __gp_m34 := any(value).(type) {
			case term.TupleTerm:
				elements := __gp_m34.Elements

				matched = uint64(len(elements)) == wanted && len(elements) > 0 && term.Equal(elements[0], tag)
			default:

			}
			return branchOnTest(machine, instruction.Operands[0], matched)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func testEquality(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 3 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m35 := any(machine.resolve(instruction.Operands[1])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m35.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		left := __gp_m35.Value

		switch __gp_m36 := any(machine.resolve(instruction.Operands[2])).(type) {
		case result.Err[term.Term, Failure]:
			failure := __gp_m36.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[term.Term, Failure]:
			right := __gp_m36.Value

			equal := term.Equal(left, right)
			if instruction.Opcode.Name == "is_eq" || instruction.Opcode.Name == "is_ne" {
				equal = numericOrExactEqual(left, right)
			}
			if instruction.Opcode.Name == "is_ne" || instruction.Opcode.Name == "is_ne_exact" {
				equal = !equal
			}
			return branchOnTest(machine, instruction.Operands[0], equal)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func numericOrExactEqual(left term.Term, right term.Term) bool {
	if term.Equal(left, right) {
		return true
	}
	switch __gp_m37 := any(term.IntegerValue(left)).(type) {
	case option.Some[*big.Int]:
		integer := __gp_m37.Value

		switch __gp_m38 := any(term.FloatValue(right)).(type) {
		case option.Some[float64]:
			floating := __gp_m38.Value

			return integerFloatEqual(integer, floating)
		case option.None[float64]:

		default:
			panic("goplus: impossible enum value in match")
		}
	case option.None[*big.Int]:

	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m39 := any(term.FloatValue(left)).(type) {
	case option.Some[float64]:
		floating := __gp_m39.Value

		switch __gp_m40 := any(term.IntegerValue(right)).(type) {
		case option.Some[*big.Int]:
			integer := __gp_m40.Value

			return integerFloatEqual(integer, floating)
		case option.None[*big.Int]:

		default:
			panic("goplus: impossible enum value in match")
		}
	case option.None[float64]:

	default:
		panic("goplus: impossible enum value in match")
	}
	return false
}

func integerFloatEqual(integer *big.Int, floating float64) bool {
	if math.IsNaN(floating) || math.IsInf(floating, 0) {
		return false
	}
	converted := new(big.Rat).SetFloat64(floating)
	wanted := new(big.Rat).SetInt(integer)
	return converted.Cmp(wanted) == 0
}

func getList(machine *Machine, instruction beam.Instruction, headOnly bool) result.Result[instructionOutcome, Failure] {
	want := 3
	if headOnly {
		want = 2
	}
	if len(instruction.Operands) != want {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m41 := any(machine.resolve(instruction.Operands[0])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m41.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m41.Value

		switch __gp_m42 := any(splitList(value)).(type) {
		case option.None[listParts]:

			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: instruction.Opcode.Name + " source is not a nonempty list"}}
		case option.Some[listParts]:
			parts := __gp_m42.Value

			switch __gp_m43 := any(machine.assign(instruction.Operands[1], parts.Head)).(type) {
			case result.Err[MachineMutation, Failure]:
				failure := __gp_m43.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[MachineMutation, Failure]:

			default:
				panic("goplus: impossible enum value in match")
			}
			if !headOnly {
				switch __gp_m44 := any(machine.assign(instruction.Operands[2], parts.Tail)).(type) {
				case result.Err[MachineMutation, Failure]:
					failure := __gp_m44.Err

					return result.Err[instructionOutcome, Failure]{Err: failure}
				case result.Ok[MachineMutation, Failure]:

				default:
					panic("goplus: impossible enum value in match")
				}
			}
			machine.pc++
			return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

type listParts struct {
	Head term.Term
	Tail term.Term
}

func splitList(value term.Term) option.Option[listParts] {
	switch __gp_m45 := any(value).(type) {
	case term.ProperListTerm:
		elements := __gp_m45.Elements

		if len(elements) == 0 {
			return option.None[listParts]{}
		}
		return option.Some[listParts]{Value: listParts{Head: term.Clone(elements[0]), Tail: term.List(elements[1:]...)}}
	case term.ImproperListTerm:
		elements := __gp_m45.Elements
		tail := __gp_m45.Tail

		if len(elements) == 0 {
			return option.None[listParts]{}
		}
		remaining := term.Clone(tail)
		if len(elements) > 1 {
			remaining = term.ImproperList(elements[1:], tail)
		}
		return option.Some[listParts]{Value: listParts{Head: term.Clone(elements[0]), Tail: remaining}}
	default:

		return option.None[listParts]{}
	}
}

func getListTail(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 2 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m46 := any(machine.resolve(instruction.Operands[0])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m46.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m46.Value

		switch __gp_m47 := any(splitList(value)).(type) {
		case option.None[listParts]:

			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "get_tl source is not a nonempty list"}}
		case option.Some[listParts]:
			parts := __gp_m47.Value

			switch __gp_m48 := any(machine.assign(instruction.Operands[1], parts.Tail)).(type) {
			case result.Err[MachineMutation, Failure]:
				failure := __gp_m48.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[MachineMutation, Failure]:

				machine.pc++
				return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func putList(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 3 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m49 := any(machine.resolve(instruction.Operands[0])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m49.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		head := __gp_m49.Value

		switch __gp_m50 := any(machine.resolve(instruction.Operands[1])).(type) {
		case result.Err[term.Term, Failure]:
			failure := __gp_m50.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[term.Term, Failure]:
			tail := __gp_m50.Value

			value := prependList(head, tail)
			switch __gp_m51 := any(machine.trackHeapTerm(value, 2)).(type) {
			case result.Err[HeapMutation, Failure]:
				failure := __gp_m51.Err
				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[HeapMutation, Failure]:

			default:
				panic("goplus: impossible enum value in match")
			}
			switch __gp_m52 := any(machine.assign(instruction.Operands[2], value)).(type) {
			case result.Err[MachineMutation, Failure]:
				failure := __gp_m52.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[MachineMutation, Failure]:

				machine.pc++
				return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func prependList(head term.Term, tail term.Term) term.Term {
	switch __gp_m53 := any(tail).(type) {
	case term.ProperListTerm:
		elements := __gp_m53.Elements

		return term.List(append([]term.Term{term.Clone(head)}, elements...)...)
	case term.ImproperListTerm:
		elements := __gp_m53.Elements
		improperTail := __gp_m53.Tail

		return term.ImproperList(append([]term.Term{term.Clone(head)}, elements...), improperTail)
	default:

		return term.ImproperList([]term.Term{term.Clone(head)}, tail)
	}
}

func getTupleElement(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 3 {
		return malformedCoreInstruction(instruction)
	}
	var index uint64
	switch __gp_m54 := any(beam.Uint64(instruction.Operands[1])).(type) {
	case option.None[uint64]:

		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "tuple element index is not uint64"}}
	case option.Some[uint64]:
		value := __gp_m54.Value

		index = value
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m55 := any(machine.resolve(instruction.Operands[0])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m55.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m55.Value

		switch __gp_m56 := any(value).(type) {
		case term.TupleTerm:
			elements := __gp_m56.Elements

			if index >= uint64(len(elements)) {
				return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "tuple element index is out of range"}}
			}
			switch __gp_m57 := any(machine.assign(instruction.Operands[2], elements[index])).(type) {
			case result.Err[MachineMutation, Failure]:
				failure := __gp_m57.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[MachineMutation, Failure]:

				machine.pc++
				return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:

			return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "get_tuple_element source is not a tuple"}}
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func putTuple(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 2 {
		return malformedCoreInstruction(instruction)
	}
	var operands []beam.Operand
	switch __gp_m58 := any(instruction.Operands[1]).(type) {
	case beam.ListOperand:
		items := __gp_m58.Items

		operands = items
	default:

		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "put_tuple2 elements are not a list operand"}}
	}
	elements := make([]term.Term, len(operands))
	for index, operand := range operands {
		switch __gp_m59 := any(machine.resolve(operand)).(type) {
		case result.Err[term.Term, Failure]:
			failure := __gp_m59.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[term.Term, Failure]:
			value := __gp_m59.Value

			elements[index] = value
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	value := term.Tuple(elements...)
	switch __gp_m60 := any(machine.trackHeapTerm(value, len(elements)+1)).(type) {
	case result.Err[HeapMutation, Failure]:
		failure := __gp_m60.Err
		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[HeapMutation, Failure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m61 := any(machine.assign(instruction.Operands[0], value)).(type) {
	case result.Err[MachineMutation, Failure]:
		failure := __gp_m61.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[MachineMutation, Failure]:

		machine.pc++
		return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:enum heapAllocation
type heapAllocation interface{ isHeapAllocation() }

//goplus:variant (heapAllocation) HeapWords(Count uint64)
type heapWords struct {
	count uint64
}

func (heapWords) isHeapAllocation() {}

//goplus:variant (heapAllocation) FloatSlots(Count uint64)
type floatSlots struct {
	count uint64
}

func (floatSlots) isHeapAllocation() {}

//goplus:variant (heapAllocation) FunSlots(Count uint64)
type funSlots struct {
	count uint64
}

func (funSlots) isHeapAllocation() {}

// heapAllocationCases selects one handler per heapAllocation variant for heapAllocationFold.
type heapAllocationCases[R any] struct {
	HeapWords  func(Count uint64) R
	FloatSlots func(Count uint64) R
	FunSlots   func(Count uint64) R
}

// heapAllocationFold reduces heapAllocation by one-level case analysis.
func heapAllocationFold[R any](h heapAllocation, cs heapAllocationCases[R]) R {
	switch m := any(h).(type) {
	case heapWords:
		return cs.HeapWords(m.count)
	case floatSlots:
		return cs.FloatSlots(m.count)
	case funSlots:
		return cs.FunSlots(m.count)
	default:
		panic("goplus: impossible enum value in heapAllocationFold")
	}
}

// heapAllocationEqOverrides carries optional per-variant hooks for heapAllocationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type heapAllocationEqOverrides struct {
	HeapWords  func(x, y heapWords) (eq, handled bool)
	FloatSlots func(x, y floatSlots) (eq, handled bool)
	FunSlots   func(x, y funSlots) (eq, handled bool)
}

// heapAllocationEqualWith reports structural equality of a and b under ov.
func heapAllocationEqualWith(a, b heapAllocation, ov heapAllocationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case heapWords:
		y, ok := any(b).(heapWords)
		if !ok {
			return false
		}
		if ov.HeapWords != nil {
			if eq, handled := ov.HeapWords(x, y); handled {
				return eq
			}
		}
		if x.count != y.count {
			return false
		}
		return true
	case floatSlots:
		y, ok := any(b).(floatSlots)
		if !ok {
			return false
		}
		if ov.FloatSlots != nil {
			if eq, handled := ov.FloatSlots(x, y); handled {
				return eq
			}
		}
		if x.count != y.count {
			return false
		}
		return true
	case funSlots:
		y, ok := any(b).(funSlots)
		if !ok {
			return false
		}
		if ov.FunSlots != nil {
			if eq, handled := ov.FunSlots(x, y); handled {
				return eq
			}
		}
		if x.count != y.count {
			return false
		}
		return true
	}
	return false
}

// heapAllocationEqual reports structural equality of a and b.
func heapAllocationEqual(a, b heapAllocation) bool {
	return heapAllocationEqualWith(a, b, heapAllocationEqOverrides{})
}

func heapWordCount(instruction beam.Instruction, operandIndex int) result.Result[int, Failure] {
	if operandIndex < 0 || operandIndex >= len(instruction.Operands) {
		return result.Err[int, Failure]{Err: InvalidProgram{Detail: "missing heap allocation operand"}}
	}
	switch __gp_m62 := any(instruction.Operands[operandIndex]).(type) {
	case beam.UnsignedOperand:

		return allocationCount(instruction, operandIndex)
	case beam.AllocationListOperand:
		raw := __gp_m62.Allocations

		words := uint64(0)
		for _, entry := range raw {
			switch __gp_m63 := any(classifyHeapAllocation(entry)).(type) {
			case result.Err[heapAllocation, Failure]:
				failure := __gp_m63.Err
				return result.Err[int, Failure]{Err: failure}
			case result.Ok[heapAllocation, Failure]:
				allocation := __gp_m63.Value

				switch __gp_m64 := any(allocation).(type) {
				case heapWords:
					count := __gp_m64.count

					if count > uint64(maxInt())-words {
						return result.Err[int, Failure]{Err: InvalidProgram{Detail: "heap allocation count overflows int"}}
					}
					words += count
				case floatSlots, funSlots:

				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		return result.Ok[int, Failure]{Value: int(words)}
	default:

		return result.Err[int, Failure]{Err: InvalidProgram{Detail: "invalid heap allocation operand"}}
	}
}

// OTP-29.0.4 beam_asm:encode_alloc_list_1 defines kinds 0, 1, and 2.
func classifyHeapAllocation(entry beam.Allocation) result.Result[heapAllocation, Failure] {
	switch entry.Kind {
	case 0:
		return result.Ok[heapAllocation, Failure]{Value: heapWords{count: entry.Count}}
	case 1:
		return result.Ok[heapAllocation, Failure]{Value: floatSlots{count: entry.Count}}
	case 2:
		return result.Ok[heapAllocation, Failure]{Value: funSlots{count: entry.Count}}
	default:
		return result.Err[heapAllocation, Failure]{Err: InvalidProgram{Detail: "unknown heap allocation kind"}}
	}
}

func swapRegisters(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 2 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m65 := any(machine.resolve(instruction.Operands[0])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m65.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		left := __gp_m65.Value

		switch __gp_m66 := any(machine.resolve(instruction.Operands[1])).(type) {
		case result.Err[term.Term, Failure]:
			failure := __gp_m66.Err

			return result.Err[instructionOutcome, Failure]{Err: failure}
		case result.Ok[term.Term, Failure]:
			right := __gp_m66.Value

			switch __gp_m67 := any(machine.assign(instruction.Operands[0], right)).(type) {
			case result.Err[MachineMutation, Failure]:
				failure := __gp_m67.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[MachineMutation, Failure]:

			default:
				panic("goplus: impossible enum value in match")
			}
			switch __gp_m68 := any(machine.assign(instruction.Operands[1], left)).(type) {
			case result.Err[MachineMutation, Failure]:
				failure := __gp_m68.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[MachineMutation, Failure]:

				machine.pc++
				return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func initializeYRegisters(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 1 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m69 := any(instruction.Operands[0]).(type) {
	case beam.ListOperand:
		registers := __gp_m69.Items

		for _, register := range registers {
			switch __gp_m70 := any(machine.assign(register, term.List())).(type) {
			case result.Err[MachineMutation, Failure]:
				failure := __gp_m70.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[MachineMutation, Failure]:

			default:
				panic("goplus: impossible enum value in match")
			}
		}
		machine.pc++
		return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
	default:

		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "init_yregs operand is not a register list"}}
	}
}

func selectValue(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 3 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m71 := any(machine.resolve(instruction.Operands[0])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m71.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m71.Value

		return selectFromPairs(machine, value, instruction.Operands[1], instruction.Operands[2], false)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func selectTupleArity(machine *Machine, instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	if len(instruction.Operands) != 3 {
		return malformedCoreInstruction(instruction)
	}
	switch __gp_m72 := any(machine.resolve(instruction.Operands[0])).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m72.Err

		return result.Err[instructionOutcome, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		value := __gp_m72.Value

		switch __gp_m73 := any(value).(type) {
		case term.TupleTerm:
			elements := __gp_m73.Elements

			return selectFromPairs(machine, term.Integer(int64(len(elements))), instruction.Operands[1], instruction.Operands[2], true)
		default:

			return jumpToOperand(machine, instruction.Operands[1])
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func selectFromPairs(
	machine *Machine,
	value term.Term,
	fail beam.Operand,
	pairsOperand beam.Operand,
	unsignedKeys bool,
) result.Result[instructionOutcome, Failure] {
	var pairs []beam.Operand
	switch __gp_m74 := any(pairsOperand).(type) {
	case beam.ListOperand:
		items := __gp_m74.Items

		pairs = items
	default:

		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "select destinations are not a list operand"}}
	}
	if len(pairs)%2 != 0 {
		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "select destinations are not key/label pairs"}}
	}
	for index := 0; index < len(pairs); index += 2 {
		var key term.Term
		if unsignedKeys {
			switch __gp_m75 := any(beam.Uint64(pairs[index])).(type) {
			case option.None[uint64]:

				return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "tuple arity key is not uint64"}}
			case option.Some[uint64]:
				arity := __gp_m75.Value

				key = term.MustBigInteger(new(big.Int).SetUint64(arity))
			default:
				panic("goplus: impossible enum value in match")
			}
		} else {
			switch __gp_m76 := any(machine.resolve(pairs[index])).(type) {
			case result.Err[term.Term, Failure]:
				failure := __gp_m76.Err

				return result.Err[instructionOutcome, Failure]{Err: failure}
			case result.Ok[term.Term, Failure]:
				resolved := __gp_m76.Value

				key = resolved
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		if term.Equal(value, key) {
			return jumpToOperand(machine, pairs[index+1])
		}
	}
	return jumpToOperand(machine, fail)
}

func branchOnTest(
	machine *Machine,
	fail beam.Operand,
	matched bool,
) result.Result[instructionOutcome, Failure] {
	if matched {
		machine.pc++
		return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
	}
	return jumpToOperand(machine, fail)
}

func jumpToOperand(machine *Machine, operand beam.Operand) result.Result[instructionOutcome, Failure] {
	switch __gp_m77 := any(labelIndex(operand)).(type) {
	case option.None[uint64]:

		return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: "branch destination is not a label"}}
	case option.Some[uint64]:
		label := __gp_m77.Value

		target, present := machine.labels[label]
		switch __gp_m78 := any(option.Of(target, present)).(type) {
		case option.None[int]:

			return result.Err[instructionOutcome, Failure]{Err: MissingLabel{Label: label}}
		case option.Some[int]:
			position := __gp_m78.Value

			machine.pc = position + 1
			return result.Ok[instructionOutcome, Failure]{Value: instructionContinues{}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func malformedCoreInstruction(instruction beam.Instruction) result.Result[instructionOutcome, Failure] {
	return result.Err[instructionOutcome, Failure]{Err: InvalidProgram{Detail: fmt.Sprintf(
		"%s has %d operands",
		instruction.Opcode.Name,
		len(instruction.Operands),
	)}}
}
