// Code generated by goplus from mnesia.gp. DO NOT EDIT.
//goplus:v v0.28.0

package mnesia

import (
	"fmt"
	"sync"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/term"
)

//goplus:enum TransactionDecision
type TransactionDecision interface{ isTransactionDecision() }

//goplus:variant (TransactionDecision) DecideCommit(Value term.Term)
type DecideCommit struct {
	Value term.Term
}

func (DecideCommit) isTransactionDecision() {}

//goplus:variant (TransactionDecision) DecideAbort(Reason term.Term)
type DecideAbort struct {
	Reason term.Term
}

func (DecideAbort) isTransactionDecision() {}

// TransactionDecisionCases selects one handler per TransactionDecision variant for TransactionDecisionFold.
type TransactionDecisionCases[R any] struct {
	DecideCommit func(Value term.Term) R
	DecideAbort  func(Reason term.Term) R
}

// TransactionDecisionFold reduces TransactionDecision by one-level case analysis.
func TransactionDecisionFold[R any](t TransactionDecision, cs TransactionDecisionCases[R]) R {
	switch m := any(t).(type) {
	case DecideCommit:
		return cs.DecideCommit(m.Value)
	case DecideAbort:
		return cs.DecideAbort(m.Reason)
	default:
		panic("goplus: impossible enum value in TransactionDecisionFold")
	}
}

// TransactionDecisionEqOverrides carries optional per-variant hooks for TransactionDecisionEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TransactionDecisionEqOverrides struct {
	DecideCommit func(x, y DecideCommit) (eq, handled bool)
	DecideAbort  func(x, y DecideAbort) (eq, handled bool)
}

// TransactionDecisionEqualWith reports structural equality of a and b under ov.
func TransactionDecisionEqualWith(a, b TransactionDecision, ov TransactionDecisionEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case DecideCommit:
		y, ok := any(b).(DecideCommit)
		if !ok {
			return false
		}
		if ov.DecideCommit != nil {
			if eq, handled := ov.DecideCommit(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case DecideAbort:
		y, ok := any(b).(DecideAbort)
		if !ok {
			return false
		}
		if ov.DecideAbort != nil {
			if eq, handled := ov.DecideAbort(x, y); handled {
				return eq
			}
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	}
	return false
}

// TransactionDecisionEqual reports structural equality of a and b.
func TransactionDecisionEqual(a, b TransactionDecision) bool {
	return TransactionDecisionEqualWith(a, b, TransactionDecisionEqOverrides{})
}

//goplus:enum TransactionOutcome
type TransactionOutcome interface{ isTransactionOutcome() }

//goplus:variant (TransactionOutcome) Committed(Value term.Term)
type Committed struct {
	Value term.Term
}

func (Committed) isTransactionOutcome() {}

//goplus:variant (TransactionOutcome) Aborted(Reason term.Term)
type Aborted struct {
	Reason term.Term
}

func (Aborted) isTransactionOutcome() {}

// TransactionOutcomeCases selects one handler per TransactionOutcome variant for TransactionOutcomeFold.
type TransactionOutcomeCases[R any] struct {
	Committed func(Value term.Term) R
	Aborted   func(Reason term.Term) R
}

// TransactionOutcomeFold reduces TransactionOutcome by one-level case analysis.
func TransactionOutcomeFold[R any](t TransactionOutcome, cs TransactionOutcomeCases[R]) R {
	switch m := any(t).(type) {
	case Committed:
		return cs.Committed(m.Value)
	case Aborted:
		return cs.Aborted(m.Reason)
	default:
		panic("goplus: impossible enum value in TransactionOutcomeFold")
	}
}

// TransactionOutcomeEqOverrides carries optional per-variant hooks for TransactionOutcomeEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TransactionOutcomeEqOverrides struct {
	Committed func(x, y Committed) (eq, handled bool)
	Aborted   func(x, y Aborted) (eq, handled bool)
}

// TransactionOutcomeEqualWith reports structural equality of a and b under ov.
func TransactionOutcomeEqualWith(a, b TransactionOutcome, ov TransactionOutcomeEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Committed:
		y, ok := any(b).(Committed)
		if !ok {
			return false
		}
		if ov.Committed != nil {
			if eq, handled := ov.Committed(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case Aborted:
		y, ok := any(b).(Aborted)
		if !ok {
			return false
		}
		if ov.Aborted != nil {
			if eq, handled := ov.Aborted(x, y); handled {
				return eq
			}
		}
		if x.Reason != y.Reason {
			return false
		}
		return true
	}
	return false
}

// TransactionOutcomeEqual reports structural equality of a and b.
func TransactionOutcomeEqual(a, b TransactionOutcome) bool {
	return TransactionOutcomeEqualWith(a, b, TransactionOutcomeEqOverrides{})
}

//goplus:enum Mutation
type Mutation interface{ isMutation() }

//goplus:variant (Mutation) Changed()
type Changed struct{}

func (Changed) isMutation() {}

//goplus:variant (Mutation) Unchanged()
type Unchanged struct{}

func (Unchanged) isMutation() {}

// MutationCases selects one handler per Mutation variant for MutationFold.
type MutationCases[R any] struct {
	Changed   func() R
	Unchanged func() R
}

// MutationFold reduces Mutation by one-level case analysis.
func MutationFold[R any](m Mutation, cs MutationCases[R]) R {
	switch any(m).(type) {
	case Changed:
		return cs.Changed()
	case Unchanged:
		return cs.Unchanged()
	default:
		panic("goplus: impossible enum value in MutationFold")
	}
}

// MutationEqOverrides carries optional per-variant hooks for MutationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type MutationEqOverrides struct {
	Changed   func(x, y Changed) (eq, handled bool)
	Unchanged func(x, y Unchanged) (eq, handled bool)
}

// MutationEqualWith reports structural equality of a and b under ov.
func MutationEqualWith(a, b Mutation, ov MutationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Changed:
		y, ok := any(b).(Changed)
		if !ok {
			return false
		}
		if ov.Changed != nil {
			if eq, handled := ov.Changed(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Unchanged:
		y, ok := any(b).(Unchanged)
		if !ok {
			return false
		}
		if ov.Unchanged != nil {
			if eq, handled := ov.Unchanged(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// MutationEqual reports structural equality of a and b.
func MutationEqual(a, b Mutation) bool {
	return MutationEqualWith(a, b, MutationEqOverrides{})
}

//goplus:enum Failure
type Failure interface{ isFailure() }

//goplus:variant (Failure) InvalidTableName(Name string)
type InvalidTableName struct {
	Name string
}

func (InvalidTableName) isFailure() {}

//goplus:variant (Failure) DuplicateTable(Name string)
type DuplicateTable struct {
	Name string
}

func (DuplicateTable) isFailure() {}

//goplus:variant (Failure) MissingTable(Name string)
type MissingTable struct {
	Name string
}

func (MissingTable) isFailure() {}

//goplus:variant (Failure) InactiveTransaction()
type InactiveTransaction struct{}

func (InactiveTransaction) isFailure() {}

//goplus:variant (Failure) NilTransactionEffect()
type NilTransactionEffect struct{}

func (NilTransactionEffect) isFailure() {}

// FailureCases selects one handler per Failure variant for FailureFold.
type FailureCases[R any] struct {
	InvalidTableName     func(Name string) R
	DuplicateTable       func(Name string) R
	MissingTable         func(Name string) R
	InactiveTransaction  func() R
	NilTransactionEffect func() R
}

// FailureFold reduces Failure by one-level case analysis.
func FailureFold[R any](f Failure, cs FailureCases[R]) R {
	switch m := any(f).(type) {
	case InvalidTableName:
		return cs.InvalidTableName(m.Name)
	case DuplicateTable:
		return cs.DuplicateTable(m.Name)
	case MissingTable:
		return cs.MissingTable(m.Name)
	case InactiveTransaction:
		return cs.InactiveTransaction()
	case NilTransactionEffect:
		return cs.NilTransactionEffect()
	default:
		panic("goplus: impossible enum value in FailureFold")
	}
}

// FailureEqOverrides carries optional per-variant hooks for FailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FailureEqOverrides struct {
	InvalidTableName     func(x, y InvalidTableName) (eq, handled bool)
	DuplicateTable       func(x, y DuplicateTable) (eq, handled bool)
	MissingTable         func(x, y MissingTable) (eq, handled bool)
	InactiveTransaction  func(x, y InactiveTransaction) (eq, handled bool)
	NilTransactionEffect func(x, y NilTransactionEffect) (eq, handled bool)
}

// FailureEqualWith reports structural equality of a and b under ov.
func FailureEqualWith(a, b Failure, ov FailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case InvalidTableName:
		y, ok := any(b).(InvalidTableName)
		if !ok {
			return false
		}
		if ov.InvalidTableName != nil {
			if eq, handled := ov.InvalidTableName(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		return true
	case DuplicateTable:
		y, ok := any(b).(DuplicateTable)
		if !ok {
			return false
		}
		if ov.DuplicateTable != nil {
			if eq, handled := ov.DuplicateTable(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		return true
	case MissingTable:
		y, ok := any(b).(MissingTable)
		if !ok {
			return false
		}
		if ov.MissingTable != nil {
			if eq, handled := ov.MissingTable(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		return true
	case InactiveTransaction:
		y, ok := any(b).(InactiveTransaction)
		if !ok {
			return false
		}
		if ov.InactiveTransaction != nil {
			if eq, handled := ov.InactiveTransaction(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case NilTransactionEffect:
		y, ok := any(b).(NilTransactionEffect)
		if !ok {
			return false
		}
		if ov.NilTransactionEffect != nil {
			if eq, handled := ov.NilTransactionEffect(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// FailureEqual reports structural equality of a and b.
func FailureEqual(a, b Failure) bool {
	return FailureEqualWith(a, b, FailureEqOverrides{})
}

//goplus:method (Failure) Error
func FailureError(failure Failure) string {
	switch __gp_m0 := any(failure).(type) {
	case InvalidTableName:
		name := __gp_m0.Name

		return fmt.Sprintf("gotp/mnesia: invalid table name %q", name)
	case DuplicateTable:
		name := __gp_m0.Name

		return fmt.Sprintf("gotp/mnesia: table %q already exists", name)
	case MissingTable:
		name := __gp_m0.Name

		return fmt.Sprintf("gotp/mnesia: table %q does not exist", name)
	case InactiveTransaction:

		return "gotp/mnesia: transaction is no longer active"
	case NilTransactionEffect:

		return "gotp/mnesia: transaction effect is nil"
	default:
		panic("goplus: impossible enum value in match")
	}
}

type row struct {
	key   term.Term
	value term.Term
}

type state struct {
	tables map[string][]row
}

type Database struct {
	mu    sync.Mutex
	state state
}

type Transaction struct {
	workspace state
	active    bool
}

type TransactionEffect func(*Transaction) TransactionDecision

func NewDatabase() *Database {
	return &Database{state: state{tables: make(map[string][]row)}}
}

// assayxport:unit gotp.otp.mnesia-transactions
func (database *Database) CreateTable(name string) result.Result[Mutation, Failure] {
	if name == "" {
		return result.Err[Mutation, Failure]{Err: InvalidTableName{Name: name}}
	}
	database.mu.Lock()
	defer database.mu.Unlock()
	if _, duplicate := database.state.tables[name]; duplicate {
		return result.Err[Mutation, Failure]{Err: DuplicateTable{Name: name}}
	}
	database.state.tables[name] = []row{}
	return result.Ok[Mutation, Failure]{Value: Changed{}}
}

func Run(
	database *Database,
	effect TransactionEffect,
) result.Result[TransactionOutcome, Failure] {
	if effect == nil {
		return result.Err[TransactionOutcome, Failure]{Err: NilTransactionEffect{}}
	}
	database.mu.Lock()
	defer database.mu.Unlock()
	transaction := &Transaction{workspace: cloneState(database.state), active: true}
	decision := effect(transaction)
	transaction.active = false
	var checked TransactionDecision = decision
	switch __gp_m1 := any(checked).(type) {
	case DecideCommit:
		value := __gp_m1.Value

		database.state = transaction.workspace
		return result.Ok[TransactionOutcome, Failure]{Value: Committed{Value: term.Clone(value)}}
	case DecideAbort:
		reason := __gp_m1.Reason

		return result.Ok[TransactionOutcome, Failure]{Value: Aborted{Reason: term.Clone(reason)}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (transaction *Transaction) Read(
	table string,
	key term.Term,
) result.Result[option.Option[term.Term], Failure] {
	switch __gp_m2 := any(transaction.rows(table)).(type) {
	case result.Err[[]row, Failure]:
		failure := __gp_m2.Err

		return result.Err[option.Option[term.Term], Failure]{Err: failure}
	case result.Ok[[]row, Failure]:
		rows := __gp_m2.Value

		for _, candidate := range rows {
			if term.Equal(candidate.key, key) {
				return result.Ok[option.Option[term.Term], Failure]{Value: option.Some[term.Term]{Value: term.Clone(candidate.value)}}
			}
		}
		return result.Ok[option.Option[term.Term], Failure]{Value: option.None[term.Term]{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (transaction *Transaction) Write(
	table string,
	key term.Term,
	value term.Term,
) result.Result[Mutation, Failure] {
	switch __gp_m3 := any(transaction.rows(table)).(type) {
	case result.Err[[]row, Failure]:
		failure := __gp_m3.Err

		return result.Err[Mutation, Failure]{Err: failure}
	case result.Ok[[]row, Failure]:
		rows := __gp_m3.Value

		for index, candidate := range rows {
			if term.Equal(candidate.key, key) {
				rows[index] = row{key: term.Clone(key), value: term.Clone(value)}
				transaction.workspace.tables[table] = rows
				return result.Ok[Mutation, Failure]{Value: Changed{}}
			}
		}
		transaction.workspace.tables[table] = append(rows, row{
			key: term.Clone(key), value: term.Clone(value),
		})
		return result.Ok[Mutation, Failure]{Value: Changed{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (transaction *Transaction) Delete(
	table string,
	key term.Term,
) result.Result[Mutation, Failure] {
	switch __gp_m4 := any(transaction.rows(table)).(type) {
	case result.Err[[]row, Failure]:
		failure := __gp_m4.Err

		return result.Err[Mutation, Failure]{Err: failure}
	case result.Ok[[]row, Failure]:
		rows := __gp_m4.Value

		kept := rows[:0]
		removed := false
		for _, candidate := range rows {
			if term.Equal(candidate.key, key) {
				removed = true
			} else {
				kept = append(kept, candidate)
			}
		}
		transaction.workspace.tables[table] = kept
		if removed {
			return result.Ok[Mutation, Failure]{Value: Changed{}}
		}
		return result.Ok[Mutation, Failure]{Value: Unchanged{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (transaction *Transaction) rows(table string) result.Result[[]row, Failure] {
	if transaction == nil || !transaction.active {
		return result.Err[[]row, Failure]{Err: InactiveTransaction{}}
	}
	rows, present := transaction.workspace.tables[table]
	switch __gp_m5 := any(option.Of(rows, present)).(type) {
	case option.None[[]row]:

		return result.Err[[]row, Failure]{Err: MissingTable{Name: table}}
	case option.Some[[]row]:
		found := __gp_m5.Value

		return result.Ok[[]row, Failure]{Value: found}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (database *Database) DirtyRead(
	table string,
	key term.Term,
) result.Result[option.Option[term.Term], Failure] {
	database.mu.Lock()
	defer database.mu.Unlock()
	rows, present := database.state.tables[table]
	switch __gp_m6 := any(option.Of(rows, present)).(type) {
	case option.None[[]row]:

		return result.Err[option.Option[term.Term], Failure]{Err: MissingTable{Name: table}}
	case option.Some[[]row]:
		found := __gp_m6.Value

		for _, candidate := range found {
			if term.Equal(candidate.key, key) {
				return result.Ok[option.Option[term.Term], Failure]{Value: option.Some[term.Term]{Value: term.Clone(candidate.value)}}
			}
		}
		return result.Ok[option.Option[term.Term], Failure]{Value: option.None[term.Term]{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func cloneState(source state) state {
	tables := make(map[string][]row, len(source.tables))
	for name, rows := range source.tables {
		cloned := make([]row, len(rows))
		for index, candidate := range rows {
			cloned[index] = row{key: term.Clone(candidate.key), value: term.Clone(candidate.value)}
		}
		tables[name] = cloned
	}
	return state{tables: tables}
}
