// Code generated by goplus from snapshot_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package mnesia

import (
	"bytes"
	"testing"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/etf"
	"goforge.dev/gotp/term"
)

func seedSnapshotForward(transaction *Transaction) TransactionDecision {
	switch __gp_m0 := any(writeOrAbort(transaction, "alpha", term.List(term.Integer(2)), term.Tuple(term.MustAtom("two")))).(type) {
	case option.Some[term.Term]:
		reason := __gp_m0.Value
		return DecideAbort{Reason: reason}
	case option.None[term.Term]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m1 := any(writeOrAbort(transaction, "alpha", term.List(term.Integer(1)), term.Tuple(term.MustAtom("one")))).(type) {
	case option.Some[term.Term]:
		reason := __gp_m1.Value
		return DecideAbort{Reason: reason}
	case option.None[term.Term]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m2 := any(writeOrAbort(transaction, "beta", term.MustAtom("key"), term.Binary([]byte("value")))).(type) {
	case option.Some[term.Term]:
		reason := __gp_m2.Value
		return DecideAbort{Reason: reason}
	case option.None[term.Term]:
		return DecideCommit{Value: term.MustAtom("ok")}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func seedSnapshotReverse(transaction *Transaction) TransactionDecision {
	switch __gp_m3 := any(writeOrAbort(transaction, "beta", term.MustAtom("key"), term.Binary([]byte("value")))).(type) {
	case option.Some[term.Term]:
		reason := __gp_m3.Value
		return DecideAbort{Reason: reason}
	case option.None[term.Term]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m4 := any(writeOrAbort(transaction, "alpha", term.List(term.Integer(1)), term.Tuple(term.MustAtom("one")))).(type) {
	case option.Some[term.Term]:
		reason := __gp_m4.Value
		return DecideAbort{Reason: reason}
	case option.None[term.Term]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m5 := any(writeOrAbort(transaction, "alpha", term.List(term.Integer(2)), term.Tuple(term.MustAtom("two")))).(type) {
	case option.Some[term.Term]:
		reason := __gp_m5.Value
		return DecideAbort{Reason: reason}
	case option.None[term.Term]:
		return DecideCommit{Value: term.MustAtom("ok")}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func snapshotDatabase(t *testing.T, seed TransactionEffect) *Database {
	database := NewDatabase()
	mustCreateTable(t, database, "alpha")
	mustCreateTable(t, database, "beta")
	switch __gp_m6 := any(Run(database, seed)).(type) {
	case result.Err[TransactionOutcome, Failure]:
		failure := __gp_m6.Err
		t.Fatal(failure)
	case result.Ok[TransactionOutcome, Failure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	return database
}

func mustSnapshot(t *testing.T, database *Database) []byte {
	switch __gp_m7 := any(Snapshot(database, etf.CanonicalCodec{})).(type) {
	case result.Err[[]byte, SnapshotFailure]:
		failure := __gp_m7.Err
		t.Fatal(failure)
	case result.Ok[[]byte, SnapshotFailure]:
		payload := __gp_m7.Value
		return payload
	default:
		panic("goplus: impossible enum value in match")
	}
	panic("unreachable")
}

// assayxport:law gotp.otp.mnesia-snapshot-laws
func TestSnapshotIsDeterministicAcrossInsertionOrder(t *testing.T) {
	left := mustSnapshot(t, snapshotDatabase(t, seedSnapshotForward))
	right := mustSnapshot(t, snapshotDatabase(t, seedSnapshotReverse))
	if !bytes.Equal(left, right) {
		t.Fatal("snapshot bytes depend on insertion order")
	}
}

func TestSnapshotRestoreRoundTripArbitraryTerms(t *testing.T) {
	source := snapshotDatabase(t, seedSnapshotForward)
	payload := mustSnapshot(t, source)
	restored := NewDatabase()
	switch __gp_m8 := any(Restore(restored, etf.CanonicalCodec{}, payload)).(type) {
	case result.Err[Mutation, SnapshotFailure]:
		failure := __gp_m8.Err
		t.Fatal(failure)
	case result.Ok[Mutation, SnapshotFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m9 := any(mustDirtyRead(t, restored, "alpha", term.List(term.Integer(1)))).(type) {
	case option.None[term.Term]:
		t.Fatal("restored key missing")
	case option.Some[term.Term]:
		value := __gp_m9.Value
		if !term.Equal(value, term.Tuple(term.MustAtom("one"))) {
			t.Fatalf("restored value = %v", value)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
	if !bytes.Equal(payload, mustSnapshot(t, restored)) {
		t.Fatal("restored snapshot is not canonical")
	}
}

func TestMalformedRestoreLeavesDatabaseUnchanged(t *testing.T) {
	database := snapshotDatabase(t, seedSnapshotForward)
	before := mustSnapshot(t, database)
	malformed := term.Tuple(term.MustAtom("gotp_mnesia_snapshot"), term.Integer(99), term.List())
	var payload []byte
	codec := etf.CanonicalCodec{}
	switch __gp_m10 := any(codec.Encode(malformed)).(type) {
	case result.Err[[]byte, etf.Failure]:
		failure := __gp_m10.Err
		t.Fatal(failure)
	case result.Ok[[]byte, etf.Failure]:
		encoded := __gp_m10.Value
		payload = encoded
	default:
		panic("goplus: impossible enum value in match")
	}
	switch any(Restore(database, etf.CanonicalCodec{}, payload)).(type) {
	case result.Ok[Mutation, SnapshotFailure]:
		t.Fatal("malformed snapshot restored")
	case result.Err[Mutation, SnapshotFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	if !bytes.Equal(before, mustSnapshot(t, database)) {
		t.Fatal("failed restore changed database")
	}
}

func TestCorruptETFRestoreLeavesDatabaseUnchanged(t *testing.T) {
	database := snapshotDatabase(t, seedSnapshotForward)
	before := mustSnapshot(t, database)
	switch any(Restore(database, etf.CanonicalCodec{}, []byte{131, 104})).(type) {
	case result.Ok[Mutation, SnapshotFailure]:
		t.Fatal("corrupt ETF restored")
	case result.Err[Mutation, SnapshotFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	if !bytes.Equal(before, mustSnapshot(t, database)) {
		t.Fatal("corrupt restore changed database")
	}
}
