// Code generated by goplus from atom_cache_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package distribution

import (
	"bytes"
	"strings"
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
)

// assayxport:unit gotp.distribution.atom-cache-header-laws
func TestAtomCacheHeaderMatchesOTPLayout(t *testing.T) {
	cache := NewAtomCache()
	references := []AtomReference{
		{Segment: 4, Internal: 236, NewAtom: option.Some[string]{Value: "reg"}},
		{Segment: 1, Internal: 9, NewAtom: option.Some[string]{Value: "call"}},
	}
	switch __gp_m0 := any(cache.EncodeHeader(references)).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m0.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		encoded := __gp_m0.Value

		want := []byte{131, 68, 2, 0x9c, 0, 236, 3, 'r', 'e', 'g', 9, 4, 'c', 'a', 'l', 'l'}
		if !bytes.Equal(encoded, want) {
			t.Fatalf("encoded = %v, want %v", encoded, want)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestAtomCachePersistsReferencesAcrossHeaders(t *testing.T) {
	sender := NewAtomCache()
	receiver := NewAtomCache()
	first := []AtomReference{{Segment: 3, Internal: 7, NewAtom: option.Some[string]{Value: "worker"}}}
	switch __gp_m1 := any(sender.EncodeHeader(first)).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m1.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		encoded := __gp_m1.Value

		switch __gp_m2 := any(receiver.DecodeHeader(append(encoded, 99, 100))).(type) {
		case result.Err[DecodedHeader, Failure]:
			failure := __gp_m2.Err
			t.Fatal(Error(failure))
		case result.Ok[DecodedHeader, Failure]:
			header := __gp_m2.Value

			if header.BytesConsumed != len(encoded) || len(header.Atoms) != 1 || header.Atoms[0] != "worker" {
				t.Fatalf("header = %#v", header)
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
	second := []AtomReference{{Segment: 3, Internal: 7, NewAtom: option.None[string]{}}}
	switch __gp_m3 := any(sender.EncodeHeader(second)).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m3.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		encoded := __gp_m3.Value

		switch __gp_m4 := any(receiver.DecodeHeader(encoded)).(type) {
		case result.Err[DecodedHeader, Failure]:
			failure := __gp_m4.Err
			t.Fatal(Error(failure))
		case result.Ok[DecodedHeader, Failure]:
			header := __gp_m4.Value
			if header.Atoms[0] != "worker" {
				t.Fatalf("atoms = %v", header.Atoms)
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestLongAtomFlagAppliesToAllNewEntries(t *testing.T) {
	long := strings.Repeat("\u00e9", 128)
	cache := NewAtomCache()
	switch __gp_m5 := any(cache.EncodeHeader([]AtomReference{
		{Segment: 0, Internal: 1, NewAtom: option.Some[string]{Value: "a"}},
		{Segment: 0, Internal: 2, NewAtom: option.Some[string]{Value: long}},
	})).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m5.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		encoded := __gp_m5.Value

		if encoded[4]&1 == 0 {
			t.Fatal("long-atoms flag is unset")
		}
		switch __gp_m6 := any(NewAtomCache().DecodeHeader(encoded)).(type) {
		case result.Err[DecodedHeader, Failure]:
			failure := __gp_m6.Err
			t.Fatal(Error(failure))
		case result.Ok[DecodedHeader, Failure]:
			header := __gp_m6.Value

			if header.Atoms[0] != "a" || header.Atoms[1] != long {
				t.Fatal("long atoms did not round trip")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestMalformedHeaderRollsBackCacheUpdates(t *testing.T) {
	cache := NewAtomCache()
	malformed := []byte{131, 68, 2, 0x88, 0, 1, 1, 'a', 2, 5, 'b'}
	switch any(cache.DecodeHeader(malformed)).(type) {
	case result.Err[DecodedHeader, Failure]:

	case result.Ok[DecodedHeader, Failure]:
		t.Fatal("malformed header was accepted")
	default:
		panic("goplus: impossible enum value in match")
	}
	switch any(cache.EncodeHeader([]AtomReference{{Segment: 0, Internal: 1, NewAtom: option.None[string]{}}})).(type) {
	case result.Err[[]byte, Failure]:

	case result.Ok[[]byte, Failure]:
		t.Fatal("failed decode leaked cache update")
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestAtomCacheDecoderNeverPanics(t *testing.T) {
	law := func(raw []byte) bool {
		if len(raw) > 1024 {
			raw = raw[:1024]
		}
		NewAtomCache().DecodeHeader(raw)
		return true
	}
	switch __gp_m9 := any(result.Of(true, quick.Check(law, &quick.Config{MaxCount: 2_000}))).(type) {
	case result.Err[bool, error]:
		cause := __gp_m9.Err
		t.Fatal(cause)
	case result.Ok[bool, error]:

	default:
		panic("goplus: impossible enum value in match")
	}
}
