// Code generated by goplus from outbound_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package distribution

import (
	"sync"
	"testing"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/etf"
	"goforge.dev/gotp/term"
)

// assayxport:unit gotp.distribution.outbound-control-laws
func TestRequiredReplyPrecedesQueuedOrdinaryOutput(t *testing.T) {
	from, to, _, _, _ := controlFixtureTerms()
	queue := NewOutboundQueue()
	ordinary := mustControl(t, LinkCode{}, from, to)
	reply := mustControl(t, UnlinkIDAckCode{}, term.Integer(9), from, to)
	switch __gp_m0 := any(queue.Enqueue(OrdinaryOutput{}, term.PID{Node: 2, Number: 2}, ordinary, option.None[term.Term]{})).(type) {
	case result.Err[bool, Failure]:
		failure := __gp_m0.Err
		t.Fatal(Error(failure))
	case result.Ok[bool, Failure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m1 := any(queue.Enqueue(RequiredReplyOutput{}, term.PID{Node: 2, Number: 2}, reply, option.None[term.Term]{})).(type) {
	case result.Err[bool, Failure]:
		failure := __gp_m1.Err
		t.Fatal(Error(failure))
	case result.Ok[bool, Failure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m2 := any(queue.Next()).(type) {
	case option.None[OutboundMessage]:
		t.Fatal("queue is empty")
	case option.Some[OutboundMessage]:
		message := __gp_m2.Value
		if message.Control.Number() != 36 {
			t.Fatal("required reply was not first")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m3 := any(queue.Next()).(type) {
	case option.None[OutboundMessage]:
		t.Fatal("ordinary output was lost")
	case option.Some[OutboundMessage]:
		message := __gp_m3.Value
		if message.Control.Number() != 1 {
			t.Fatal("ordinary output changed")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestOutboundQueueClonesPayloadAndEncodesNegotiatedPacket(t *testing.T) {
	from, to, _, _, _ := controlFixtureTerms()
	queue := NewOutboundQueue()
	raw := []byte("message")
	control := mustControl(t, SendSenderCode{}, from, to)
	payload := option.Some[term.Term]{Value: term.Binary(raw)}
	switch __gp_m4 := any(queue.Enqueue(OrdinaryOutput{}, term.PID{Node: 2, Number: 2}, control, payload)).(type) {
	case result.Err[bool, Failure]:
		failure := __gp_m4.Err
		t.Fatal(Error(failure))
	case result.Ok[bool, Failure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	raw[0] = 'X'
	connected := NewConnectedCodec(nil, etf.CanonicalCodec{Nodes: mustNodes(t)})
	codec := NewNegotiatedCodec(connected, DFlagSendSender)
	switch __gp_m5 := any(queue.EncodeNext(codec)).(type) {
	case result.Err[option.Option[[]byte], Failure]:
		failure := __gp_m5.Err
		t.Fatal(Error(failure))
	case result.Ok[option.Option[[]byte], Failure]:
		packetOption := __gp_m5.Value

		switch __gp_m6 := any(packetOption).(type) {
		case option.None[[]byte]:
			t.Fatal("encoded queue is empty")
		case option.Some[[]byte]:
			packet := __gp_m6.Value

			switch __gp_m7 := any(connected.DecodeTyped(packet)).(type) {
			case result.Err[TypedConnectedFrame, Failure]:
				failure := __gp_m7.Err
				t.Fatal(Error(failure))
			case result.Ok[TypedConnectedFrame, Failure]:
				frame := __gp_m7.Value

				switch __gp_m8 := any(frame).(type) {
				case TypedTick:
					t.Fatal("output decoded as tick")
				case TypedSignal:
					decoded := __gp_m8.Payload

					switch __gp_m9 := any(decoded).(type) {
					case option.None[term.Term]:
						t.Fatal("payload is absent")
					case option.Some[term.Term]:
						value := __gp_m9.Value

						if !term.Equal(value, term.Binary([]byte("message"))) {
							t.Fatalf("payload = %#v", value)
						}
					default:
						panic("goplus: impossible enum value in match")
					}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestOutboundConcurrentEnqueueLosesNoMessages(t *testing.T) {
	from, to, _, _, _ := controlFixtureTerms()
	control := mustControl(t, LinkCode{}, from, to)
	queue := NewOutboundQueue()
	var wait sync.WaitGroup
	for index := 0; index < 100; index++ {
		wait.Add(1)
		go func() {
			defer wait.Done()
			queue.Enqueue(OrdinaryOutput{}, term.PID{Node: 2, Number: 2}, control, option.None[term.Term]{})
		}()
	}
	wait.Wait()
	count := 0
	for {
		switch any(queue.Next()).(type) {
		case option.None[OutboundMessage]:

			if count != 100 {
				t.Fatalf("messages = %d", count)
			}
			return
		case option.Some[OutboundMessage]:
			count++
		default:
			panic("goplus: impossible enum value in match")
		}
	}
}
