// Code generated by goplus from wire_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package distribution

import (
	"bytes"
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/result"
)

// assayxport:unit gotp.distribution.handshake-wire-laws
func TestSendNameMatchesOTPVersionSixLayout(t *testing.T) {
	node := Node{Name: "a@b", Flags: 0x0102030405060708, Creation: 0x090a0b0c}
	switch __gp_m0 := any(EncodeSendName(node)).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m0.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		packet := __gp_m0.Value

		want := []byte{
			0, 18, 'N', 1, 2, 3, 4, 5, 6, 7, 8,
			9, 10, 11, 12, 0, 3, 'a', '@', 'b',
		}
		if !bytes.Equal(packet, want) {
			t.Fatalf("packet = %x, want %x", packet, want)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestHandshakeWireRoundTrips(t *testing.T) {
	node := Node{Name: "client@local", Flags: 1<<36 | 1<<35, Creation: 17}
	switch __gp_m1 := any(EncodeChallenge(node, 0x01020304)).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m1.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		packet := __gp_m1.Value

		packet = append(packet, 0xaa)
		packet[1]++
		switch __gp_m2 := any(DecodeChallenge(packet)).(type) {
		case result.Err[struct {
			Node      Node
			Challenge uint32
		}, Failure]:
			failure := __gp_m2.Err
			t.Fatal(Error(failure))
		case result.Ok[struct {
			Node      Node
			Challenge uint32
		}, Failure]:
			decoded := __gp_m2.Value

			if decoded.Node != node || decoded.Challenge != 0x01020304 {
				t.Fatalf("decoded = %#v", decoded)
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
	for _, status := range []Status{
		StatusOK{}, StatusOKSimultaneous{}, StatusNOK{}, StatusNotAllowed{},
		StatusAlive{}, StatusContinue{Continue: true}, StatusContinue{Continue: false},
		StatusNamed{Node: Node{Name: "dynamic@local", Creation: 99}},
	} {
		switch __gp_m3 := any(EncodeStatus(status)).(type) {
		case result.Err[[]byte, Failure]:
			failure := __gp_m3.Err
			t.Fatal(Error(failure))
		case result.Ok[[]byte, Failure]:
			packet := __gp_m3.Value

			switch __gp_m4 := any(DecodeStatus(packet)).(type) {
			case result.Err[Status, Failure]:
				failure := __gp_m4.Err
				t.Fatal(Error(failure))
			case result.Ok[Status, Failure]:
				decoded := __gp_m4.Value

				if decoded != status {
					t.Fatalf("status = %#v, want %#v", decoded, status)
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	}
}

func TestPacketFramingClonesAndSupportsTicks(t *testing.T) {
	payload := []byte{1, 2, 3}
	switch __gp_m5 := any(EncodePacket4(payload)).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m5.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		packet := __gp_m5.Value

		payload[0] = 9
		switch __gp_m6 := any(DecodePacket4(packet)).(type) {
		case result.Err[[]byte, Failure]:
			failure := __gp_m6.Err
			t.Fatal(Error(failure))
		case result.Ok[[]byte, Failure]:
			decoded := __gp_m6.Value

			if !bytes.Equal(decoded, []byte{1, 2, 3}) {
				t.Fatalf("decoded = %v", decoded)
			}
			decoded[0] = 8
			if packet[4] != 1 {
				t.Fatal("decode aliased packet")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m7 := any(DecodePacket4([]byte{0, 0, 0, 0})).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m7.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		tick := __gp_m7.Value
		if len(tick) != 0 {
			t.Fatalf("tick = %v", tick)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestWireDecodersNeverPanic(t *testing.T) {
	law := func(raw []byte) bool {
		if len(raw) > 512 {
			raw = raw[:512]
		}
		DecodePacket2(raw)
		DecodePacket4(raw)
		DecodeSendName(raw)
		DecodeChallenge(raw)
		DecodeStatus(raw)
		DecodeComplement(raw)
		DecodeReply(raw)
		DecodeAcknowledgement(raw)
		return true
	}
	switch __gp_m8 := any(result.Of(true, quick.Check(law, &quick.Config{MaxCount: 2_000}))).(type) {
	case result.Err[bool, error]:
		cause := __gp_m8.Err
		t.Fatal(cause)
	case result.Ok[bool, error]:

	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestExactMessagesRejectTrailingBytes(t *testing.T) {
	switch __gp_m9 := any(EncodeComplement(Complement{FlagsHigh: 1, Creation: 2})).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m9.Err
		t.Fatal(Error(failure))
	case result.Ok[[]byte, Failure]:
		packet := __gp_m9.Value

		packet = append(packet, 0)
		packet[1]++
		switch any(DecodeComplement(packet)).(type) {
		case result.Err[Complement, Failure]:

		case result.Ok[Complement, Failure]:
			t.Fatal("extended complement was accepted")
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}
