// Code generated by goplus from format.gp. DO NOT EDIT.
//goplus:v v0.28.0

package release

import (
	"fmt"
	"math"
	"strconv"
	"strings"
	"unicode"

	"goforge.dev/gotp/term"
)

//goplus:enum FileOperation
type FileOperation interface{ isFileOperation() }

//goplus:variant (FileOperation) OpenFile()
type OpenFile struct{}

func (OpenFile) isFileOperation() {}

//goplus:variant (FileOperation) ReadFile()
type ReadFile struct{}

func (ReadFile) isFileOperation() {}

//goplus:variant (FileOperation) ParseFile()
type ParseFile struct{}

func (ParseFile) isFileOperation() {}

//goplus:variant (FileOperation) CloseFile()
type CloseFile struct{}

func (CloseFile) isFileOperation() {}

// FileOperationCases selects one handler per FileOperation variant for FileOperationFold.
type FileOperationCases[R any] struct {
	OpenFile  func() R
	ReadFile  func() R
	ParseFile func() R
	CloseFile func() R
}

// FileOperationFold reduces FileOperation by one-level case analysis.
func FileOperationFold[R any](f FileOperation, cs FileOperationCases[R]) R {
	switch any(f).(type) {
	case OpenFile:
		return cs.OpenFile()
	case ReadFile:
		return cs.ReadFile()
	case ParseFile:
		return cs.ParseFile()
	case CloseFile:
		return cs.CloseFile()
	default:
		panic("goplus: impossible enum value in FileOperationFold")
	}
}

// FileOperationEqOverrides carries optional per-variant hooks for FileOperationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FileOperationEqOverrides struct {
	OpenFile  func(x, y OpenFile) (eq, handled bool)
	ReadFile  func(x, y ReadFile) (eq, handled bool)
	ParseFile func(x, y ParseFile) (eq, handled bool)
	CloseFile func(x, y CloseFile) (eq, handled bool)
}

// FileOperationEqualWith reports structural equality of a and b under ov.
func FileOperationEqualWith(a, b FileOperation, ov FileOperationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case OpenFile:
		y, ok := any(b).(OpenFile)
		if !ok {
			return false
		}
		if ov.OpenFile != nil {
			if eq, handled := ov.OpenFile(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ReadFile:
		y, ok := any(b).(ReadFile)
		if !ok {
			return false
		}
		if ov.ReadFile != nil {
			if eq, handled := ov.ReadFile(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ParseFile:
		y, ok := any(b).(ParseFile)
		if !ok {
			return false
		}
		if ov.ParseFile != nil {
			if eq, handled := ov.ParseFile(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CloseFile:
		y, ok := any(b).(CloseFile)
		if !ok {
			return false
		}
		if ov.CloseFile != nil {
			if eq, handled := ov.CloseFile(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// FileOperationEqual reports structural equality of a and b.
func FileOperationEqual(a, b FileOperation) bool {
	return FileOperationEqualWith(a, b, FileOperationEqOverrides{})
}

//goplus:enum RelupWarning
type RelupWarning interface{ isRelupWarning() }

//goplus:variant (RelupWarning) ERTSVersionChanged(From term.Term, To term.Term)
type ERTSVersionChanged struct {
	From term.Term
	To   term.Term
}

func (ERTSVersionChanged) isRelupWarning() {}

//goplus:variant (RelupWarning) PreR15EmulatorUpgrade()
type PreR15EmulatorUpgrade struct{}

func (PreR15EmulatorUpgrade) isRelupWarning() {}

//goplus:variant (RelupWarning) RawRelupWarning(Value term.Term)
type RawRelupWarning struct {
	Value term.Term
}

func (RawRelupWarning) isRelupWarning() {}

// RelupWarningCases selects one handler per RelupWarning variant for RelupWarningFold.
type RelupWarningCases[R any] struct {
	ERTSVersionChanged    func(From term.Term, To term.Term) R
	PreR15EmulatorUpgrade func() R
	RawRelupWarning       func(Value term.Term) R
}

// RelupWarningFold reduces RelupWarning by one-level case analysis.
func RelupWarningFold[R any](v RelupWarning, cs RelupWarningCases[R]) R {
	switch m := any(v).(type) {
	case ERTSVersionChanged:
		return cs.ERTSVersionChanged(m.From, m.To)
	case PreR15EmulatorUpgrade:
		return cs.PreR15EmulatorUpgrade()
	case RawRelupWarning:
		return cs.RawRelupWarning(m.Value)
	default:
		panic("goplus: impossible enum value in RelupWarningFold")
	}
}

// RelupWarningEqOverrides carries optional per-variant hooks for RelupWarningEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type RelupWarningEqOverrides struct {
	ERTSVersionChanged    func(x, y ERTSVersionChanged) (eq, handled bool)
	PreR15EmulatorUpgrade func(x, y PreR15EmulatorUpgrade) (eq, handled bool)
	RawRelupWarning       func(x, y RawRelupWarning) (eq, handled bool)
}

// RelupWarningEqualWith reports structural equality of a and b under ov.
func RelupWarningEqualWith(a, b RelupWarning, ov RelupWarningEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ERTSVersionChanged:
		y, ok := any(b).(ERTSVersionChanged)
		if !ok {
			return false
		}
		if ov.ERTSVersionChanged != nil {
			if eq, handled := ov.ERTSVersionChanged(x, y); handled {
				return eq
			}
		}
		if x.From != y.From {
			return false
		}
		if x.To != y.To {
			return false
		}
		return true
	case PreR15EmulatorUpgrade:
		y, ok := any(b).(PreR15EmulatorUpgrade)
		if !ok {
			return false
		}
		if ov.PreR15EmulatorUpgrade != nil {
			if eq, handled := ov.PreR15EmulatorUpgrade(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case RawRelupWarning:
		y, ok := any(b).(RawRelupWarning)
		if !ok {
			return false
		}
		if ov.RawRelupWarning != nil {
			if eq, handled := ov.RawRelupWarning(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	}
	return false
}

// RelupWarningEqual reports structural equality of a and b.
func RelupWarningEqual(a, b RelupWarning) bool {
	return RelupWarningEqualWith(a, b, RelupWarningEqOverrides{})
}

//goplus:enum RelupError
type RelupError interface{ isRelupError() }

//goplus:variant (RelupError) FileProblem(File string, Operation FileOperation)
type FileProblem struct {
	File      string
	Operation FileOperation
}

func (FileProblem) isRelupError() {}

//goplus:variant (RelupError) NoRelup(File string, Application ApplicationSpec, Version string)
type NoRelup struct {
	File        string
	Application ApplicationSpec
	Version     string
}

func (NoRelup) isRelupError() {}

//goplus:variant (RelupError) MissingSASL(Release ReleaseSpec)
type MissingSASL struct {
	Release ReleaseSpec
}

func (MissingSASL) isRelupError() {}

//goplus:variant (RelupError) WarningsTreatedAsErrors(Warnings []RelupWarning)
type WarningsTreatedAsErrors struct {
	Warnings []RelupWarning
}

func (WarningsTreatedAsErrors) isRelupError() {}

//goplus:variant (RelupError) RawRelupError(Value term.Term)
type RawRelupError struct {
	Value term.Term
}

func (RawRelupError) isRelupError() {}

// RelupErrorCases selects one handler per RelupError variant for RelupErrorFold.
type RelupErrorCases[R any] struct {
	FileProblem             func(File string, Operation FileOperation) R
	NoRelup                 func(File string, Application ApplicationSpec, Version string) R
	MissingSASL             func(Release ReleaseSpec) R
	WarningsTreatedAsErrors func(Warnings []RelupWarning) R
	RawRelupError           func(Value term.Term) R
}

// RelupErrorFold reduces RelupError by one-level case analysis.
func RelupErrorFold[R any](v RelupError, cs RelupErrorCases[R]) R {
	switch m := any(v).(type) {
	case FileProblem:
		return cs.FileProblem(m.File, m.Operation)
	case NoRelup:
		return cs.NoRelup(m.File, m.Application, m.Version)
	case MissingSASL:
		return cs.MissingSASL(m.Release)
	case WarningsTreatedAsErrors:
		return cs.WarningsTreatedAsErrors(m.Warnings)
	case RawRelupError:
		return cs.RawRelupError(m.Value)
	default:
		panic("goplus: impossible enum value in RelupErrorFold")
	}
}

// assayxport:unit gotp.otp.systools-relup-diagnostics
func FormatRelupError(failure RelupError) string {
	switch __gp_m0 := any(failure).(type) {
	case FileProblem:
		file := __gp_m0.File
		operation := __gp_m0.Operation

		return "Could not " + fileOperationText(operation) + " file " + file + "\n"
	case NoRelup:
		file := __gp_m0.File
		application := __gp_m0.Application
		version := __gp_m0.Version

		name := erlangAtomText(application.Name)
		return "No release upgrade script entry for " + name + "-" + application.Version +
			" to " + name + "-" + version + " in file " + file + "\n"
	case MissingSASL:
		release := __gp_m0.Release

		return "No sasl application in release " + release.Name + ", " + release.Version + ". Can not be upgraded."
	case WarningsTreatedAsErrors:
		warnings := __gp_m0.Warnings

		var text strings.Builder
		text.WriteString("Warnings being treated as errors:\n")
		for _, warning := range warnings {
			text.WriteString(formatRelupWarning("", warning))
		}
		return text.String()
	case RawRelupError:
		value := __gp_m0.Value

		return erlangTermText(value) + "\n"
	default:
		panic("goplus: impossible enum value in match")
	}
}

func FormatRelupWarning(warning RelupWarning) string {
	return formatRelupWarning("*WARNING* ", warning)
}

func formatRelupWarning(prefix string, warning RelupWarning) string {
	switch __gp_m1 := any(warning).(type) {
	case ERTSVersionChanged:
		from := __gp_m1.From
		to := __gp_m1.To

		return prefix + "The ERTS version changed between " + erlangTermText(from) + " and " + erlangTermText(to) + "\n"
	case PreR15EmulatorUpgrade:

		return prefix + "Upgrade from an OTP version earlier than R15. New code should be compiled with the old emulator.\n"
	case RawRelupWarning:
		value := __gp_m1.Value

		return prefix + erlangTermText(value) + "\n"
	default:
		panic("goplus: impossible enum value in match")
	}
}

func fileOperationText(operation FileOperation) string {
	switch any(operation).(type) {
	case OpenFile:
		return "open"
	case ReadFile:
		return "read"
	case ParseFile:
		return "parse"
	case CloseFile:
		return "close"
	default:
		panic("goplus: impossible enum value in match")
	}
}

func erlangTermText(value term.Term) string {
	switch __gp_m3 := any(value).(type) {
	case term.InvalidTerm:
		return "undefined"
	case term.IntegerTerm:
		integer := __gp_m3.Value
		return integer.String()
	case term.FloatTerm:
		bits := __gp_m3.Bits
		return fmt.Sprintf("%.17g", math.Float64frombits(bits))
	case term.AtomTerm:
		name := __gp_m3.Name
		return erlangAtomText(name)
	case term.BinaryTerm:
		raw := __gp_m3.Bytes
		return "<<" + byteText(raw) + ">>"
	case term.TupleTerm:
		elements := __gp_m3.Elements
		return "{" + termSequenceText(elements) + "}"
	case term.ProperListTerm:
		elements := __gp_m3.Elements
		return "[" + termSequenceText(elements) + "]"
	case term.ImproperListTerm:
		elements := __gp_m3.Elements
		tail := __gp_m3.Tail
		return "[" + termSequenceText(elements) + "|" + erlangTermText(tail) + "]"
	case term.MapTerm:
		entries := __gp_m3.Entries

		parts := make([]string, len(entries))
		for index, entry := range entries {
			parts[index] = erlangTermText(entry.Key) + "=>" + erlangTermText(entry.Value)
		}
		return "#{" + strings.Join(parts, ",") + "}"
	case term.PIDTerm:
		pid := __gp_m3.Value
		return fmt.Sprintf("<%d.%d.%d>", pid.Node, pid.Number, pid.Creation)
	case term.ReferenceTerm:
		reference := __gp_m3.Value
		return fmt.Sprintf("#Ref<%d.%d.%v>", reference.Node, reference.Creation, reference.Words[:int(reference.Length)])
	case term.FunTerm:
		function := __gp_m3.Value
		return "#Fun<" + erlangAtomText(function.Module) + "." + strconv.FormatUint(uint64(function.Index), 10) + ">"
	case term.PortTerm:
		port := __gp_m3.Value
		return fmt.Sprintf("#Port<%d.%d>", port.Node, port.ID)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func erlangAtomText(name string) string {
	valid := name != ""
	for index, character := range name {
		if index == 0 {
			valid = character >= 'a' && character <= 'z'
			continue
		}
		valid = valid && (unicode.IsLetter(character) || unicode.IsDigit(character) || character == '_' || character == '@')
	}
	if valid {
		return name
	}
	return "'" + strings.ReplaceAll(strings.ReplaceAll(name, "\\", "\\\\"), "'", "\\'") + "'"
}

func termSequenceText(values []term.Term) string {
	parts := make([]string, len(values))
	for index, value := range values {
		parts[index] = erlangTermText(value)
	}
	return strings.Join(parts, ",")
}

func byteText(values []byte) string {
	parts := make([]string, len(values))
	for index, value := range values {
		parts[index] = strconv.Itoa(int(value))
	}
	return strings.Join(parts, ",")
}
