// Code generated by goplus from script_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package release

import (
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/term"
)

func tuple(name string, values ...term.Term) term.Term {
	return term.Tuple(append([]term.Term{term.MustAtom(name)}, values...)...)
}
func atoms(values ...string) term.Term {
	items := make([]term.Term, len(values))
	for index, value := range values {
		items[index] = term.MustAtom(value)
	}
	return term.List(items...)
}

// assayxport:law gotp.otp.release-script-laws
func TestPinnedReleaseScriptVocabularyAndTransactionSplit(t *testing.T) {
	encoded := term.List(
		tuple("load_object_code", term.Tuple(term.MustAtom("sample"), term.Binary([]byte("2.0")), atoms("alpha", "beta"))),
		term.MustAtom("point_of_no_return"),
		tuple("suspend", term.List(term.MustAtom("alpha"), term.Tuple(term.MustAtom("beta"), term.MustAtom("infinity")))),
		tuple("load", term.Tuple(term.MustAtom("alpha"), term.MustAtom("soft_purge"), term.MustAtom("brutal_purge"))),
		tuple("code_change", term.MustAtom("up"), term.List(term.Tuple(term.MustAtom("alpha"), term.Tuple(term.MustAtom("extra"), term.Integer(1))))),
		tuple("resume", atoms("alpha", "beta")),
		tuple("sync_nodes", term.MustAtom("phase"), atoms("node1", "node2")),
		tuple("apply", term.Tuple(term.MustAtom("application"), term.MustAtom("start"), term.List(term.MustAtom("sample")))),
		term.MustAtom("restart_emulator"),
	)
	switch __gp_m0 := any(ParseScript(encoded)).(type) {
	case result.Err[Script, ScriptFailure]:
		failure := __gp_m0.Err
		t.Fatal(ScriptFailureError(failure))
	case result.Ok[Script, ScriptFailure]:
		script := __gp_m0.Value

		if script.CommitIndex != 1 || len(script.Preflight()) != 1 || len(script.Commit()) != 8 {
			t.Fatalf("split = %d/%d/%d", script.CommitIndex, len(script.Preflight()), len(script.Commit()))
		}
		staged := StagedModules(script)
		if len(staged) != 2 || staged[0] != "alpha" || staged[1] != "beta" {
			t.Fatalf("staged = %v", staged)
		}
		{
			__gp_m1 := any(script.Instructions[4])
			{
				__gp_a0, __gp_k0 := any(__gp_m1).(ChangeCode)
				if __gp_k0 {
					_, __gp_k1 := any(__gp_a0.Mode).(Upgrade)
					if __gp_k1 {
						targets := __gp_a0.Targets
						if len(targets) != 1 || targets[0].Module != "alpha" {
							t.Fatalf("change targets = %v", targets)
						}
						goto __gp_match1_done
					}
				}
			}
			{
				t.Fatal("code_change differs")
				goto __gp_match1_done
			}
		__gp_match1_done:
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestReleaseScriptRejectsCommitAndStagingDrift(t *testing.T) {
	cases := []term.Term{
		term.List(tuple("load_object_code", term.Tuple(term.MustAtom("sample"), term.Binary([]byte("1")), atoms("alpha")))),
		term.List(term.MustAtom("point_of_no_return"), tuple("load_object_code", term.Tuple(term.MustAtom("sample"), term.Binary([]byte("1")), atoms("alpha")))),
		term.List(tuple("load_object_code", term.Tuple(term.MustAtom("sample"), term.Binary([]byte("1")), atoms("alpha"))), term.MustAtom("point_of_no_return"), tuple("load", term.Tuple(term.MustAtom("beta"), term.MustAtom("soft_purge"), term.MustAtom("soft_purge")))),
	}
	for index, encoded := range cases {
		switch any(ParseScript(encoded)).(type) {
		case result.Err[Script, ScriptFailure]:
		case result.Ok[Script, ScriptFailure]:
			t.Fatalf("invalid script %d was accepted", index)
		default:
			panic("goplus: impossible enum value in match")
		}
	}
}

func TestReleaseScriptParserNeverPanics(t *testing.T) {
	law := func(raw []byte) bool {
		if len(raw) > 4096 {
			raw = raw[:4096]
		}
		ParseScript(term.Binary(raw))
		return true
	}
	switch __gp_m3 := any(result.Of(true, quick.Check(law, &quick.Config{MaxCount: 2000}))).(type) {
	case result.Err[bool, error]:
		cause := __gp_m3.Err
		t.Fatal(cause)
	case result.Ok[bool, error]:
	default:
		panic("goplus: impossible enum value in match")
	}
}
