// Code generated by goplus from monitor_alias_laws_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package kernel

import (
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/term"
)

// assayxport:law gotp.kernel.monitor-alias-lifecycle
func TestMonitorAliasRoutesUntilDemonitor(t *testing.T) {
	property := func(message int64) bool {
		runtime := New(KernelConfig{})
		waiting := func(*Context) StepResult { return Wait{} }
		var owner, target term.PID
		switch __gp_m0 := any(runtime.Spawn(waiting, Unlinked{TrapExit: false})).(type) {
		case result.Err[term.PID, Failure]:
			return false
		case result.Ok[term.PID, Failure]:
			pid := __gp_m0.Value
			owner = pid
		default:
			panic("goplus: impossible enum value in match")
		}
		switch __gp_m1 := any(runtime.Spawn(waiting, Unlinked{TrapExit: false})).(type) {
		case result.Err[term.PID, Failure]:
			return false
		case result.Ok[term.PID, Failure]:
			pid := __gp_m1.Value
			target = pid
		default:
			panic("goplus: impossible enum value in match")
		}
		var reference term.Reference
		switch __gp_m2 := any(runtime.MonitorAlias(owner, target)).(type) {
		case result.Err[term.Reference, Failure]:
			return false
		case result.Ok[term.Reference, Failure]:
			found := __gp_m2.Value
			reference = found
		default:
			panic("goplus: impossible enum value in match")
		}
		switch any(runtime.SendAlias(owner, reference, term.Integer(message))).(type) {
		case NoProcess:
			return false
		case Delivered:
		default:
			panic("goplus: impossible enum value in match")
		}
		switch __gp_m4 := any(runtime.ProcessInfo(owner)).(type) {
		case option.None[ProcessInfo]:
			return false
		case option.Some[ProcessInfo]:
			info := __gp_m4.Value
			if info.MailboxLength != 1 {
				return false
			}
		default:
			panic("goplus: impossible enum value in match")
		}
		switch any(runtime.Demonitor(owner, reference, false)).(type) {
		case MonitorAbsent:
			return false
		case MonitorRemoved:
		default:
			panic("goplus: impossible enum value in match")
		}
		switch any(runtime.SendAlias(owner, reference, term.Integer(message))).(type) {
		case Delivered:
			return false
		case NoProcess:
		default:
			panic("goplus: impossible enum value in match")
		}
		switch __gp_m7 := any(runtime.ProcessInfo(owner)).(type) {
		case option.None[ProcessInfo]:
			return false
		case option.Some[ProcessInfo]:
			info := __gp_m7.Value
			return info.MailboxLength == 1
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	if cause := quick.Check(property, nil); cause != nil {
		t.Fatal(cause)
	}
}
