// Code generated by goplus from process_signals_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package kernel

import (
	"testing"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/term"
)

func waitingProcess(_ *Context) StepResult {
	return Wait{}
}

func exitReason(t *testing.T, runtime *Kernel, pid term.PID) option.Option[term.Term] {
	switch __gp_m0 := any(runtime.ProcessInfo(pid)).(type) {
	case option.None[ProcessInfo]:

		t.Fatal("process record is missing")
	case option.Some[ProcessInfo]:
		info := __gp_m0.Value

		return info.ExitReason
	default:
		panic("goplus: impossible enum value in match")
	}
	panic("unreachable")
}

// assayxport:law gotp.kernel.process-signal-laws
func TestKillIsUntrappableAndBecomesKilled(t *testing.T) {
	runtime := New(KernelConfig{})
	sender := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	target := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: true})
	switch any(runtime.SendExit(sender, target, term.MustAtom("kill"))).(type) {
	case Delivered:

	case NoProcess:

		t.Fatal("kill target was missing")
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m2 := any(exitReason(t, runtime, target)).(type) {
	case option.None[term.Term]:

		t.Fatal("kill did not terminate target")
	case option.Some[term.Term]:
		reason := __gp_m2.Value

		if !term.Equal(reason, term.MustAtom("killed")) {
			t.Fatalf("kill reason = %v", reason)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestNormalExitFromAnotherProcessIsIgnored(t *testing.T) {
	runtime := New(KernelConfig{})
	sender := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	target := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	runtime.SendExit(sender, target, term.MustAtom("normal"))
	switch __gp_m3 := any(exitReason(t, runtime, target)).(type) {
	case option.None[term.Term]:

	case option.Some[term.Term]:
		reason := __gp_m3.Value

		t.Fatalf("normal exit terminated target: %v", reason)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestTrappedExitIsOrdinaryMailboxTuple(t *testing.T) {
	runtime := New(KernelConfig{})
	sender := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	var received option.Option[term.Term] = option.None[term.Term]{}
	target := mustSpawn(t, runtime, func(context *Context) StepResult {
		switch __gp_m4 := any(context.ReceiveMessage(nil)).(type) {
		case option.None[MessageEnvelope]:

			return Wait{}
		case option.Some[MessageEnvelope]:
			envelope := __gp_m4.Value

			received = option.Some[term.Term]{Value: envelope.Message}
			return Stop{Reason: term.MustAtom("normal")}
		default:
			panic("goplus: impossible enum value in match")
		}
	}, Unlinked{TrapExit: true})
	runtime.SendExit(sender, target, term.MustAtom("shutdown"))
	runtime.Run(10)
	want := term.Tuple(term.MustAtom("EXIT"), term.PIDTerm{Value: sender}, term.MustAtom("shutdown"))
	switch __gp_m5 := any(received).(type) {
	case option.None[term.Term]:

		t.Fatal("trapped exit was not received")
	case option.Some[term.Term]:
		message := __gp_m5.Value

		if !term.Equal(message, want) {
			t.Fatalf("trapped exit = %v, want %v", message, want)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestMonitorDownIsOrdinaryMailboxTuple(t *testing.T) {
	runtime := New(KernelConfig{})
	var received option.Option[term.Term] = option.None[term.Term]{}
	watcher := mustSpawn(t, runtime, func(context *Context) StepResult {
		switch __gp_m6 := any(context.ReceiveMessage(nil)).(type) {
		case option.None[MessageEnvelope]:

			return Wait{}
		case option.Some[MessageEnvelope]:
			envelope := __gp_m6.Value

			received = option.Some[term.Term]{Value: envelope.Message}
			return Stop{Reason: term.MustAtom("normal")}
		default:
			panic("goplus: impossible enum value in match")
		}
	}, Unlinked{TrapExit: false})
	target := mustSpawn(t, runtime, func(_ *Context) StepResult {
		return Stop{Reason: term.MustAtom("boom")}
	}, Unlinked{TrapExit: false})
	var monitored term.Reference
	switch __gp_m7 := any(runtime.Monitor(watcher, target)).(type) {
	case result.Err[term.Reference, Failure]:
		failure := __gp_m7.Err

		t.Fatal(failure)
	case result.Ok[term.Reference, Failure]:
		found := __gp_m7.Value

		monitored = found
	default:
		panic("goplus: impossible enum value in match")
	}
	runtime.Run(10)
	want := term.Tuple(
		term.MustAtom("DOWN"), term.ReferenceTerm{Value: monitored}, term.MustAtom("process"),
		term.PIDTerm{Value: target}, term.MustAtom("boom"),
	)
	switch __gp_m8 := any(received).(type) {
	case option.None[term.Term]:

		t.Fatal("DOWN was not received")
	case option.Some[term.Term]:
		message := __gp_m8.Value

		if !term.Equal(message, want) {
			t.Fatalf("DOWN = %v, want %v", message, want)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}
