// Code generated by goplus from process_aliases_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package kernel

import (
	"testing"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/term"
)

func mustAlias(t *testing.T, runtime *Kernel, owner term.PID) term.Reference {
	switch __gp_m0 := any(runtime.Alias(owner)).(type) {
	case result.Err[term.Reference, Failure]:
		failure := __gp_m0.Err

		t.Fatal(failure)
	case result.Ok[term.Reference, Failure]:
		reference := __gp_m0.Value

		return reference
	default:
		panic("goplus: impossible enum value in match")
	}
	panic("unreachable")
}

// assayxport:law gotp.kernel.process-alias-laws
func TestAliasRoutesMessagesAndPreservesSender(t *testing.T) {
	runtime := New(KernelConfig{})
	sender := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	var received option.Option[MessageEnvelope] = option.None[MessageEnvelope]{}
	owner := mustSpawn(t, runtime, func(context *Context) StepResult {
		switch __gp_m1 := any(context.ReceiveMessage(nil)).(type) {
		case option.None[MessageEnvelope]:

			return Wait{}
		case option.Some[MessageEnvelope]:
			envelope := __gp_m1.Value

			received = option.Some[MessageEnvelope]{Value: envelope}
			return Stop{Reason: term.MustAtom("normal")}
		default:
			panic("goplus: impossible enum value in match")
		}
	}, Unlinked{TrapExit: false})
	reference := mustAlias(t, runtime, owner)
	switch any(runtime.SendAlias(sender, reference, term.MustAtom("reply"))).(type) {
	case Delivered:

	case NoProcess:

		t.Fatal("live alias rejected message")
	default:
		panic("goplus: impossible enum value in match")
	}
	runtime.Run(10)
	switch __gp_m3 := any(received).(type) {
	case option.None[MessageEnvelope]:

		t.Fatal("alias message was not received")
	case option.Some[MessageEnvelope]:
		envelope := __gp_m3.Value

		if envelope.From != sender || !term.Equal(envelope.Message, term.MustAtom("reply")) {
			t.Fatalf("alias envelope = %#v", envelope)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestOnlyOwnerCanRevokeAlias(t *testing.T) {
	runtime := New(KernelConfig{})
	owner := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	other := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	reference := mustAlias(t, runtime, owner)
	switch any(runtime.Unalias(other, reference)).(type) {
	case AliasRemoved:

		t.Fatal("non-owner revoked alias")
	case AliasAbsent:

	default:
		panic("goplus: impossible enum value in match")
	}
	switch any(runtime.SendAlias(other, reference, term.MustAtom("still_live"))).(type) {
	case Delivered:

	case NoProcess:

		t.Fatal("non-owner revocation changed routing")
	default:
		panic("goplus: impossible enum value in match")
	}
	switch any(runtime.Unalias(owner, reference)).(type) {
	case AliasRemoved:

	case AliasAbsent:

		t.Fatal("owner could not revoke alias")
	default:
		panic("goplus: impossible enum value in match")
	}
	switch any(runtime.SendAlias(other, reference, term.MustAtom("stale"))).(type) {
	case Delivered:

		t.Fatal("revoked alias accepted message")
	case NoProcess:

	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestOwnerExitRevokesEveryAlias(t *testing.T) {
	runtime := New(KernelConfig{})
	owner := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	sender := mustSpawn(t, runtime, waitingProcess, Unlinked{TrapExit: false})
	aliases := []term.Reference{mustAlias(t, runtime, owner), mustAlias(t, runtime, owner)}
	runtime.Exit(owner, term.MustAtom("shutdown"))
	for _, reference := range aliases {
		switch any(runtime.SendAlias(sender, reference, term.MustAtom("stale"))).(type) {
		case Delivered:

			t.Fatal("dead owner's alias accepted message")
		case NoProcess:

		default:
			panic("goplus: impossible enum value in match")
		}
	}
}
