// Code generated by goplus from hot_code.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"fmt"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/kernel"
	"goforge.dev/gotp/term"
	"goforge.dev/gotp/vm"
)

//goplus:enum HotCodeExitCapability
type HotCodeExitCapability interface{ isHotCodeExitCapability() }

//goplus:variant (HotCodeExitCapability) HotCodeExitWith(Exit func(term.PID, term.Term) kernel.Delivery)
type HotCodeExitWith struct {
	Exit func(term.PID, term.Term) kernel.Delivery
}

func (HotCodeExitWith) isHotCodeExitCapability() {}

// HotCodeExitCapabilityCases selects one handler per HotCodeExitCapability variant for HotCodeExitCapabilityFold.
type HotCodeExitCapabilityCases[R any] struct {
	HotCodeExitWith func(Exit func(term.PID, term.Term) kernel.Delivery) R
}

// HotCodeExitCapabilityFold reduces HotCodeExitCapability by one-level case analysis.
func HotCodeExitCapabilityFold[R any](h HotCodeExitCapability, cs HotCodeExitCapabilityCases[R]) R {
	switch m := any(h).(type) {
	case HotCodeExitWith:
		return cs.HotCodeExitWith(m.Exit)
	default:
		panic("goplus: impossible enum value in HotCodeExitCapabilityFold")
	}
}

//goplus:enum HotCodeRuntimeFailure
type HotCodeRuntimeFailure interface{ isHotCodeRuntimeFailure() }

//goplus:variant (HotCodeRuntimeFailure) NilHotCodeKernel()
type NilHotCodeKernel struct{}

func (NilHotCodeKernel) isHotCodeRuntimeFailure() {}

//goplus:variant (HotCodeRuntimeFailure) NilHotCodeExit()
type NilHotCodeExit struct{}

func (NilHotCodeExit) isHotCodeRuntimeFailure() {}

//goplus:variant (HotCodeRuntimeFailure) NilLoadedHotCodeModule()
type NilLoadedHotCodeModule struct{}

func (NilLoadedHotCodeModule) isHotCodeRuntimeFailure() {}

//goplus:variant (HotCodeRuntimeFailure) HotCodeStateFailure(Cause beam.HotCodeFailure)
type HotCodeStateFailure struct {
	Cause beam.HotCodeFailure
}

func (HotCodeStateFailure) isHotCodeRuntimeFailure() {}

//goplus:variant (HotCodeRuntimeFailure) CodeReferenceNotOwned(Owner term.PID, Generation uint64)
type CodeReferenceNotOwned struct {
	Owner      term.PID
	Generation uint64
}

func (CodeReferenceNotOwned) isHotCodeRuntimeFailure() {}

// HotCodeRuntimeFailureCases selects one handler per HotCodeRuntimeFailure variant for HotCodeRuntimeFailureFold.
type HotCodeRuntimeFailureCases[R any] struct {
	NilHotCodeKernel       func() R
	NilHotCodeExit         func() R
	NilLoadedHotCodeModule func() R
	HotCodeStateFailure    func(Cause beam.HotCodeFailure) R
	CodeReferenceNotOwned  func(Owner term.PID, Generation uint64) R
}

// HotCodeRuntimeFailureFold reduces HotCodeRuntimeFailure by one-level case analysis.
func HotCodeRuntimeFailureFold[R any](h HotCodeRuntimeFailure, cs HotCodeRuntimeFailureCases[R]) R {
	switch m := any(h).(type) {
	case NilHotCodeKernel:
		return cs.NilHotCodeKernel()
	case NilHotCodeExit:
		return cs.NilHotCodeExit()
	case NilLoadedHotCodeModule:
		return cs.NilLoadedHotCodeModule()
	case HotCodeStateFailure:
		return cs.HotCodeStateFailure(m.Cause)
	case CodeReferenceNotOwned:
		return cs.CodeReferenceNotOwned(m.Owner, m.Generation)
	default:
		panic("goplus: impossible enum value in HotCodeRuntimeFailureFold")
	}
}

// HotCodeRuntimeFailureEqOverrides carries optional per-variant hooks for HotCodeRuntimeFailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type HotCodeRuntimeFailureEqOverrides struct {
	NilHotCodeKernel       func(x, y NilHotCodeKernel) (eq, handled bool)
	NilHotCodeExit         func(x, y NilHotCodeExit) (eq, handled bool)
	NilLoadedHotCodeModule func(x, y NilLoadedHotCodeModule) (eq, handled bool)
	HotCodeStateFailure    func(x, y HotCodeStateFailure) (eq, handled bool)
	CodeReferenceNotOwned  func(x, y CodeReferenceNotOwned) (eq, handled bool)
}

// HotCodeRuntimeFailureEqualWith reports structural equality of a and b under ov.
func HotCodeRuntimeFailureEqualWith(a, b HotCodeRuntimeFailure, ov HotCodeRuntimeFailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case NilHotCodeKernel:
		y, ok := any(b).(NilHotCodeKernel)
		if !ok {
			return false
		}
		if ov.NilHotCodeKernel != nil {
			if eq, handled := ov.NilHotCodeKernel(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case NilHotCodeExit:
		y, ok := any(b).(NilHotCodeExit)
		if !ok {
			return false
		}
		if ov.NilHotCodeExit != nil {
			if eq, handled := ov.NilHotCodeExit(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case NilLoadedHotCodeModule:
		y, ok := any(b).(NilLoadedHotCodeModule)
		if !ok {
			return false
		}
		if ov.NilLoadedHotCodeModule != nil {
			if eq, handled := ov.NilLoadedHotCodeModule(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case HotCodeStateFailure:
		y, ok := any(b).(HotCodeStateFailure)
		if !ok {
			return false
		}
		if ov.HotCodeStateFailure != nil {
			if eq, handled := ov.HotCodeStateFailure(x, y); handled {
				return eq
			}
		}
		if x.Cause != y.Cause {
			return false
		}
		return true
	case CodeReferenceNotOwned:
		y, ok := any(b).(CodeReferenceNotOwned)
		if !ok {
			return false
		}
		if ov.CodeReferenceNotOwned != nil {
			if eq, handled := ov.CodeReferenceNotOwned(x, y); handled {
				return eq
			}
		}
		if x.Owner != y.Owner {
			return false
		}
		if x.Generation != y.Generation {
			return false
		}
		return true
	}
	return false
}

// HotCodeRuntimeFailureEqual reports structural equality of a and b.
func HotCodeRuntimeFailureEqual(a, b HotCodeRuntimeFailure) bool {
	return HotCodeRuntimeFailureEqualWith(a, b, HotCodeRuntimeFailureEqOverrides{})
}

//goplus:method (HotCodeRuntimeFailure) Error
func HotCodeRuntimeFailureError(failure HotCodeRuntimeFailure) string {
	switch __gp_m0 := any(failure).(type) {
	case NilHotCodeKernel:
		return "gotp/erts: hot-code kernel is nil"
	case NilHotCodeExit:
		return "gotp/erts: hot-code exit capability is nil"
	case NilLoadedHotCodeModule:
		return "gotp/erts: loaded hot-code module is nil"
	case HotCodeStateFailure:
		cause := __gp_m0.Cause
		return beam.HotCodeFailureError(cause)
	case CodeReferenceNotOwned:
		generation := __gp_m0.Generation
		return "gotp/erts: code reference is not owned for generation " + fmt.Sprint(generation)
	default:
		panic("goplus: impossible enum value in match")
	}
}

type HotCodeEntry struct {
	Handle    beam.CodeHandle
	Reference beam.CodeReference
}

type HotCodePurgeReport struct {
	State  beam.CodePurgeState
	Exited int
}

type HotCodeRuntime struct {
	store  beam.CodeStore
	owners map[uint64]map[term.PID]int
	images map[uint64]vm.ModuleImage
	exits  HotCodeExitCapability
}

func HotCodeExits(kernelRuntime *kernel.Kernel) result.Result[HotCodeExitCapability, HotCodeRuntimeFailure] {
	if kernelRuntime == nil {
		return result.Err[HotCodeExitCapability, HotCodeRuntimeFailure]{Err: NilHotCodeKernel{}}
	}
	return result.Ok[HotCodeExitCapability, HotCodeRuntimeFailure]{Value: HotCodeExitWith{Exit: kernelRuntime.Exit}}
}

func NewHotCodeRuntime(exits HotCodeExitCapability) result.Result[*HotCodeRuntime, HotCodeRuntimeFailure] {
	switch __gp_m1 := any(exits).(type) {
	case HotCodeExitWith:
		exit := __gp_m1.Exit
		if exit == nil {
			return result.Err[*HotCodeRuntime, HotCodeRuntimeFailure]{Err: NilHotCodeExit{}}
		}
	default:
		panic("goplus: impossible enum value in match")
	}
	return result.Ok[*HotCodeRuntime, HotCodeRuntimeFailure]{Value: &HotCodeRuntime{store: beam.NewCodeStore(), owners: map[uint64]map[term.PID]int{}, images: map[uint64]vm.ModuleImage{}, exits: exits}}
}

func (runtime *HotCodeRuntime) InstallLoaded(module *LoadedModule) result.Result[beam.CodeHandle, HotCodeRuntimeFailure] {
	if module == nil {
		return result.Err[beam.CodeHandle, HotCodeRuntimeFailure]{Err: NilLoadedHotCodeModule{}}
	}
	switch __gp_m2 := any(runtime.Install(&beam.Module{Name: module.name, Digest: module.digest})).(type) {
	case result.Err[beam.CodeHandle, HotCodeRuntimeFailure]:
		failure := __gp_m2.Err
		return result.Err[beam.CodeHandle, HotCodeRuntimeFailure]{Err: failure}
	case result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]:
		handle := __gp_m2.Value
		runtime.images[handle.Generation] = module.image()
		return result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]{Value: handle}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (runtime *HotCodeRuntime) LinkedCode(owner term.PID) vm.LinkedCodeEffect {
	return func(target vm.ExternalFunction) vm.LinkedCodeOutcome {
		switch __gp_m3 := any(runtime.Enter(owner, target.Module)).(type) {
		case result.Err[HotCodeEntry, HotCodeRuntimeFailure]:
			failure := __gp_m3.Err
			return vm.LinkedCodeRejected{Detail: HotCodeRuntimeFailureError(failure)}
		case result.Ok[HotCodeEntry, HotCodeRuntimeFailure]:
			entry := __gp_m3.Value

			image, present := runtime.images[entry.Reference.Generation]
			switch __gp_m4 := any(option.Of(image, present)).(type) {
			case option.None[vm.ModuleImage]:

				runtime.Leave(owner, entry.Reference)
				return vm.LinkedCodeRejected{Detail: "loaded generation has no VM image"}
			case option.Some[vm.ModuleImage]:
				image := __gp_m4.Value

				released := false
				return vm.LinkedCodeResolved{Image: image, Leave: func() {
					if released {
						return
					}
					released = true
					runtime.Leave(owner, entry.Reference)
				}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	}
}

// assayxport:unit gotp.erts.hot-code
func (runtime *HotCodeRuntime) Install(image *beam.Module) result.Result[beam.CodeHandle, HotCodeRuntimeFailure] {
	switch __gp_m5 := any(runtime.store.Install(image)).(type) {
	case result.Err[beam.CodeInstallTransition, beam.HotCodeFailure]:
		cause := __gp_m5.Err
		return result.Err[beam.CodeHandle, HotCodeRuntimeFailure]{Err: HotCodeStateFailure{Cause: cause}}
	case result.Ok[beam.CodeInstallTransition, beam.HotCodeFailure]:
		transition := __gp_m5.Value
		runtime.store = transition.Store
		return result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]{Value: transition.Current}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (runtime *HotCodeRuntime) Enter(owner term.PID, module string) result.Result[HotCodeEntry, HotCodeRuntimeFailure] {
	switch __gp_m6 := any(runtime.store.EnterCurrent(module)).(type) {
	case result.Err[beam.CodeEnterTransition, beam.HotCodeFailure]:
		cause := __gp_m6.Err
		return result.Err[HotCodeEntry, HotCodeRuntimeFailure]{Err: HotCodeStateFailure{Cause: cause}}
	case result.Ok[beam.CodeEnterTransition, beam.HotCodeFailure]:
		transition := __gp_m6.Value

		runtime.store = transition.Store
		owners, present := runtime.owners[transition.Reference.Generation]
		if !present {
			owners = map[term.PID]int{}
			runtime.owners[transition.Reference.Generation] = owners
		}
		owners[owner]++
		return result.Ok[HotCodeEntry, HotCodeRuntimeFailure]{Value: HotCodeEntry{Handle: transition.Handle, Reference: transition.Reference}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (runtime *HotCodeRuntime) Leave(owner term.PID, reference beam.CodeReference) result.Result[bool, HotCodeRuntimeFailure] {
	owners, present := runtime.owners[reference.Generation]
	count := owners[owner]
	if !present || count < 1 {
		return result.Err[bool, HotCodeRuntimeFailure]{Err: CodeReferenceNotOwned{Owner: owner, Generation: reference.Generation}}
	}
	switch __gp_m7 := any(runtime.store.Leave(reference)).(type) {
	case result.Err[beam.CodeStore, beam.HotCodeFailure]:
		cause := __gp_m7.Err
		return result.Err[bool, HotCodeRuntimeFailure]{Err: HotCodeStateFailure{Cause: cause}}
	case result.Ok[beam.CodeStore, beam.HotCodeFailure]:
		store := __gp_m7.Value
		runtime.store = store
	default:
		panic("goplus: impossible enum value in match")
	}
	if count == 1 {
		delete(owners, owner)
	} else {
		owners[owner] = count - 1
	}
	if len(owners) == 0 {
		delete(runtime.owners, reference.Generation)
	}
	return result.Ok[bool, HotCodeRuntimeFailure]{Value: true}
}

func (runtime *HotCodeRuntime) SoftPurge(module string) HotCodePurgeReport {
	old := runtime.store.Old(module)
	transition := runtime.store.SoftPurge(module)
	runtime.store = transition.Store
	switch any(transition.State).(type) {
	case beam.OldCodeVersionPurged:
		switch __gp_m9 := any(old).(type) {
		case option.Some[beam.CodeHandle]:
			handle := __gp_m9.Value
			delete(runtime.images, handle.Generation)
		case option.None[beam.CodeHandle]:
		default:
			panic("goplus: impossible enum value in match")
		}
	case beam.NoOldCodeVersion, beam.OldCodeVersionBusy:

	default:
		panic("goplus: impossible enum value in match")
	}
	return HotCodePurgeReport{State: transition.State}
}

func (runtime *HotCodeRuntime) Purge(module string) HotCodePurgeReport {
	old := runtime.store.Old(module)
	transition := runtime.store.Purge(module)
	runtime.store = transition.Store
	exited := 0
	switch __gp_m10 := any(old).(type) {
	case option.None[beam.CodeHandle]:

	case option.Some[beam.CodeHandle]:
		handle := __gp_m10.Value

		owners := runtime.owners[handle.Generation]
		switch __gp_m11 := any(runtime.exits).(type) {
		case HotCodeExitWith:
			exit := __gp_m11.Exit

			for owner := range owners {
				exit(owner, term.MustAtom("killed"))
				exited++
			}
		default:
			panic("goplus: impossible enum value in match")
		}
		delete(runtime.owners, handle.Generation)
		delete(runtime.images, handle.Generation)
	default:
		panic("goplus: impossible enum value in match")
	}
	return HotCodePurgeReport{State: transition.State, Exited: exited}
}
