// Code generated by goplus from hot_code_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"math/big"
	"testing"

	"goforge.dev/goplus/std/memory"
	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/kernel"
	"goforge.dev/gotp/term"
	"goforge.dev/gotp/vm"
)

func hotCodeModule(digest string) *beam.Module { return &beam.Module{Name: "sample", Digest: digest} }

var _ memory.Handle

// assayxport:unit gotp.erts.hot-code-laws
func TestForcedHotCodePurgeExitsEachOldCodeProcessOnce(t *testing.T) {
	exits := map[term.PID]int{}
	capability := HotCodeExitWith{Exit: func(pid term.PID, reason term.Term) kernel.Delivery {
		if !term.Equal(reason, term.MustAtom("killed")) {
			t.Fatalf("reason = %v", reason)
		}
		exits[pid]++
		return kernel.Delivered{}
	}}
	var runtime *HotCodeRuntime
	switch __gp_m0 := any(NewHotCodeRuntime(capability)).(type) {
	case result.Err[*HotCodeRuntime, HotCodeRuntimeFailure]:
		failure := __gp_m0.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[*HotCodeRuntime, HotCodeRuntimeFailure]:
		created := __gp_m0.Value
		runtime = created
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m1 := any(runtime.Install(hotCodeModule("v1"))).(type) {
	case result.Err[beam.CodeHandle, HotCodeRuntimeFailure]:
		failure := __gp_m1.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	first := term.PID{Node: 1, Number: 1, Creation: 1}
	second := term.PID{Node: 1, Number: 2, Creation: 1}
	switch __gp_m2 := any(runtime.Enter(first, "sample")).(type) {
	case result.Err[HotCodeEntry, HotCodeRuntimeFailure]:
		failure := __gp_m2.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[HotCodeEntry, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m3 := any(runtime.Enter(first, "sample")).(type) {
	case result.Err[HotCodeEntry, HotCodeRuntimeFailure]:
		failure := __gp_m3.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[HotCodeEntry, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m4 := any(runtime.Enter(second, "sample")).(type) {
	case result.Err[HotCodeEntry, HotCodeRuntimeFailure]:
		failure := __gp_m4.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[HotCodeEntry, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m5 := any(runtime.Install(hotCodeModule("v2"))).(type) {
	case result.Err[beam.CodeHandle, HotCodeRuntimeFailure]:
		failure := __gp_m5.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	soft := runtime.SoftPurge("sample")
	switch __gp_m6 := any(soft.State).(type) {
	case beam.OldCodeVersionBusy:
		references := __gp_m6.References
		if references != 3 {
			t.Fatalf("references = %d", references)
		}
	default:
		t.Fatalf("soft purge state = %v", soft.State)
	}
	if len(exits) != 0 {
		t.Fatalf("soft purge exited processes: %v", exits)
	}
	forced := runtime.Purge("sample")
	if forced.Exited != 2 || exits[first] != 1 || exits[second] != 1 {
		t.Fatalf("forced purge exits = %v, report = %d", exits, forced.Exited)
	}
}

func TestHotCodeLeaveRequiresReferenceOwnership(t *testing.T) {
	var runtime *HotCodeRuntime
	switch __gp_m7 := any(NewHotCodeRuntime(HotCodeExitWith{Exit: func(term.PID, term.Term) kernel.Delivery { return kernel.Delivered{} }})).(type) {
	case result.Err[*HotCodeRuntime, HotCodeRuntimeFailure]:
		failure := __gp_m7.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[*HotCodeRuntime, HotCodeRuntimeFailure]:
		created := __gp_m7.Value
		runtime = created
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m8 := any(runtime.Install(hotCodeModule("v1"))).(type) {
	case result.Err[beam.CodeHandle, HotCodeRuntimeFailure]:
		failure := __gp_m8.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	owner := term.PID{Node: 1, Number: 1, Creation: 1}
	other := term.PID{Node: 1, Number: 2, Creation: 1}
	switch __gp_m9 := any(runtime.Enter(owner, "sample")).(type) {
	case result.Err[HotCodeEntry, HotCodeRuntimeFailure]:
		failure := __gp_m9.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[HotCodeEntry, HotCodeRuntimeFailure]:
		entry := __gp_m9.Value

		switch __gp_m10 := any(runtime.Leave(other, entry.Reference)).(type) {
		case result.Err[bool, HotCodeRuntimeFailure]:
			failure := __gp_m10.Err
			switch __gp_m11 := any(failure).(type) {
			case CodeReferenceNotOwned:
				pid := __gp_m11.Owner
				if pid != other {
					t.Fatalf("owner = %v", pid)
				}
			default:
				t.Fatalf("failure = %s", HotCodeRuntimeFailureError(failure))
			}
		case result.Ok[bool, HotCodeRuntimeFailure]:
			t.Fatal("foreign owner released reference")
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestHotCodeRejectsNilExitCapability(t *testing.T) {
	switch __gp_m12 := any(NewHotCodeRuntime(HotCodeExitWith{Exit: nil})).(type) {
	case result.Err[*HotCodeRuntime, HotCodeRuntimeFailure]:
		failure := __gp_m12.Err
		switch any(failure).(type) {
		case NilHotCodeExit:
		default:
			t.Fatalf("failure = %s", HotCodeRuntimeFailureError(failure))
		}
	case result.Ok[*HotCodeRuntime, HotCodeRuntimeFailure]:
		t.Fatal("nil exit capability was accepted")
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestHotCodeResolverLeasesCurrentVMGeneration(t *testing.T) {
	var runtime *HotCodeRuntime
	switch __gp_m14 := any(NewHotCodeRuntime(HotCodeExitWith{Exit: func(term.PID, term.Term) kernel.Delivery { return kernel.Delivered{} }})).(type) {
	case result.Err[*HotCodeRuntime, HotCodeRuntimeFailure]:
		failure := __gp_m14.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[*HotCodeRuntime, HotCodeRuntimeFailure]:
		created := __gp_m14.Value
		runtime = created
	default:
		panic("goplus: impossible enum value in match")
	}
	target := vm.ExternalFunction{Module: "sample", Function: "run", Arity: 0}
	loaded := &LoadedModule{name: "sample", digest: "v1", config: vm.MachineConfig{Exports: map[vm.ExternalFunction]uint64{target: 1}}, instructions: []beam.Instruction{{Opcode: beam.Opcode{Name: "label", Arity: 1}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(1)}}}}}
	switch __gp_m15 := any(runtime.InstallLoaded(loaded)).(type) {
	case result.Err[beam.CodeHandle, HotCodeRuntimeFailure]:
		failure := __gp_m15.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	owner := term.PID{Node: 1, Number: 9, Creation: 1}
	switch __gp_m16 := any(runtime.LinkedCode(owner)(target)).(type) {
	case vm.LinkedCodeRejected:
		detail := __gp_m16.Detail
		t.Fatal(detail)
	case vm.LinkedCodeUnchanged:
		t.Fatal("resolver left code unchanged")
	case vm.LinkedCodeResolved:
		image := __gp_m16.Image
		leave := __gp_m16.Leave

		if image.Name != "sample" {
			t.Fatalf("image = %s", image.Name)
		}
		switch __gp_m17 := any(runtime.InstallLoaded(&LoadedModule{name: "sample", digest: "v2"})).(type) {
		case result.Err[beam.CodeHandle, HotCodeRuntimeFailure]:
			failure := __gp_m17.Err
			t.Fatal(HotCodeRuntimeFailureError(failure))
		case result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]:
		default:
			panic("goplus: impossible enum value in match")
		}
		switch __gp_m18 := any(runtime.SoftPurge("sample").State).(type) {
		case beam.OldCodeVersionBusy:
			count := __gp_m18.References
			if count != 1 {
				t.Fatalf("references = %d", count)
			}
		default:
			t.Fatal("soft purge did not report busy old code")
		}
		leave()
		leave()
		switch __gp_m19 := any(runtime.SoftPurge("sample").State).(type) {
		case beam.OldCodeVersionPurged:
			count := __gp_m19.InvalidatedReferences
			if count != 0 {
				t.Fatalf("invalidated = %d", count)
			}
		default:
			t.Fatal("soft purge did not remove old code")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestHotCodePurgeReclaimsLiteralGenerationAfterLease(t *testing.T) {
	var runtime *HotCodeRuntime
	switch __gp_m20 := any(NewHotCodeRuntime(HotCodeExitWith{Exit: func(term.PID, term.Term) kernel.Delivery { return kernel.Delivered{} }})).(type) {
	case result.Err[*HotCodeRuntime, HotCodeRuntimeFailure]:
		failure := __gp_m20.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[*HotCodeRuntime, HotCodeRuntimeFailure]:
		created := __gp_m20.Value
		runtime = created
	default:
		panic("goplus: impossible enum value in match")
	}
	literals := requireLiteralArena(t)
	switch __gp_m21 := any(literals.Store(0, []byte("old literal"))).(type) {
	case result.Err[memory.Handle, LiteralArenaFailure]:
		failure := __gp_m21.Err
		t.Fatal(failure)
	case result.Ok[memory.Handle, LiteralArenaFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m22 := any(runtime.InstallLoaded(&LoadedModule{name: "sample", digest: "literal-v1", literalArena: literals})).(type) {
	case result.Err[beam.CodeHandle, HotCodeRuntimeFailure]:
		failure := __gp_m22.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	owner := term.PID{Node: 1, Number: 17, Creation: 1}
	var reference beam.CodeReference
	switch __gp_m23 := any(runtime.Enter(owner, "sample")).(type) {
	case result.Err[HotCodeEntry, HotCodeRuntimeFailure]:
		failure := __gp_m23.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[HotCodeEntry, HotCodeRuntimeFailure]:
		entry := __gp_m23.Value
		reference = entry.Reference
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m24 := any(runtime.InstallLoaded(&LoadedModule{name: "sample", digest: "literal-v2"})).(type) {
	case result.Err[beam.CodeHandle, HotCodeRuntimeFailure]:
		failure := __gp_m24.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[beam.CodeHandle, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	busy := runtime.SoftPurge("sample")
	if busy.ReclaimedLiterals != 0 || literals.Stats().Closed {
		t.Fatal("busy purge reclaimed leased literals")
	}
	switch __gp_m25 := any(runtime.Leave(owner, reference)).(type) {
	case result.Err[bool, HotCodeRuntimeFailure]:
		failure := __gp_m25.Err
		t.Fatal(HotCodeRuntimeFailureError(failure))
	case result.Ok[bool, HotCodeRuntimeFailure]:
	default:
		panic("goplus: impossible enum value in match")
	}
	purged := runtime.SoftPurge("sample")
	if purged.ReclaimedLiterals != 1 || !literals.Stats().Closed {
		t.Fatalf("purge = %d/%v", purged.ReclaimedLiterals, literals.Stats().Closed)
	}
	switch __gp_m26 := any(purged.ReleaseFailure).(type) {
	case option.None[LiteralArenaFailure]:
	case option.Some[LiteralArenaFailure]:
		failure := __gp_m26.Value
		t.Fatal(failure)
	default:
		panic("goplus: impossible enum value in match")
	}
}
