// Code generated by goplus from module_invocation_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"testing"

	"goforge.dev/goplus/std/clock"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/kernel"
	"goforge.dev/gotp/term"
)

func pinnedListsModule(t *testing.T) *LoadedModule {
	var read beam.ReadFileCapability = beam.OperatingSystemFiles{}
	switch __gp_m0 := any(LoadModuleFile(read, "../beam/testdata/otp-29.0.4/lists.beam", ModuleLoaderConfig{})).(type) {
	case result.Err[*LoadedModule, ModuleLoadFailure]:
		failure := __gp_m0.Err

		t.Fatal(failure)
	case result.Ok[*LoadedModule, ModuleLoadFailure]:
		module := __gp_m0.Value

		return module
	default:
		panic("goplus: impossible enum value in match")
	}
	panic("unreachable")
}

func completedInvocation(t *testing.T, process *VMProcess) term.Term {
	runtime := kernel.New(kernel.KernelConfig{})
	switch __gp_m1 := any(runtime.Spawn(process.Behavior(), kernel.Unlinked{TrapExit: false})).(type) {
	case result.Err[term.PID, kernel.Failure]:
		failure := __gp_m1.Err

		t.Fatal(failure)
	case result.Ok[term.PID, kernel.Failure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	runtime.Run(100)
	var state VMProcessState = process.State()
	switch __gp_m2 := any(state).(type) {
	case VMProcessCompleted:
		value := __gp_m2.Value

		return value
	case VMProcessRunning, VMProcessSuspended, VMProcessWaiting, VMProcessRaised, VMProcessFailed:

		t.Fatalf("invocation state = %T: %v", state, state)
	default:
		panic("goplus: impossible enum value in match")
	}
	panic("unreachable")
}

func otpRegistryForInvocation(t *testing.T) *CallRegistry {
	switch __gp_m3 := any(NewOTPCallRegistry()).(type) {
	case result.Err[*CallRegistry, CallRegistryFailure]:
		failure := __gp_m3.Err

		t.Fatal(failure)
	case result.Ok[*CallRegistry, CallRegistryFailure]:
		registry := __gp_m3.Value

		return registry
	default:
		panic("goplus: impossible enum value in match")
	}
	panic("unreachable")
}

// assayxport:law gotp.erts.module-invocation-laws
func TestLoadedModuleInvocationUsesNativeExportOverride(t *testing.T) {
	module := pinnedListsModule(t)
	registry := otpRegistryForInvocation(t)
	values := term.List(term.Float(1), term.Integer(2))
	switch __gp_m4 := any(module.Invoke("member", []term.Term{term.Integer(1), values}, clock.Real{}, registry)).(type) {
	case result.Err[*VMProcess, ModuleLoadFailure]:
		failure := __gp_m4.Err

		t.Fatal(failure)
	case result.Ok[*VMProcess, ModuleLoadFailure]:
		process := __gp_m4.Value

		value := completedInvocation(t, process)
		if !term.Equal(value, term.MustAtom("false")) {
			t.Fatalf("lists:member(1, [1.0, 2]) = %v", value)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m5 := any(module.Invoke("member", []term.Term{term.Integer(2), values}, clock.Real{}, registry)).(type) {
	case result.Err[*VMProcess, ModuleLoadFailure]:
		failure := __gp_m5.Err

		t.Fatal(failure)
	case result.Ok[*VMProcess, ModuleLoadFailure]:
		process := __gp_m5.Value

		value := completedInvocation(t, process)
		if !term.Equal(value, term.MustAtom("true")) {
			t.Fatalf("lists:member(2, [1.0, 2]) = %v", value)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestLoadedModuleInvocationFallsBackToBEAMExport(t *testing.T) {
	module := pinnedListsModule(t)
	values := term.List(term.Integer(1), term.Integer(2), term.Integer(3))
	switch __gp_m6 := any(module.Invoke("last", []term.Term{values}, clock.Real{}, otpRegistryForInvocation(t))).(type) {
	case result.Err[*VMProcess, ModuleLoadFailure]:
		failure := __gp_m6.Err

		t.Fatal(failure)
	case result.Ok[*VMProcess, ModuleLoadFailure]:
		process := __gp_m6.Value

		value := completedInvocation(t, process)
		if !term.Equal(value, term.Integer(3)) {
			t.Fatalf("lists:last/1 = %v", value)
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestModuleSetInvocationUsesSameRootDispatch(t *testing.T) {
	module := pinnedListsModule(t)
	switch __gp_m7 := any(NewModuleSet([]*LoadedModule{module})).(type) {
	case result.Err[*ModuleSet, ModuleLoadFailure]:
		failure := __gp_m7.Err

		t.Fatal(failure)
	case result.Ok[*ModuleSet, ModuleLoadFailure]:
		modules := __gp_m7.Value

		switch __gp_m8 := any(modules.Invoke(
			"lists",
			"member",
			[]term.Term{term.MustAtom("needle"), term.List(term.MustAtom("needle"))},
			clock.Real{},
			otpRegistryForInvocation(t),
		)).(type) {
		case result.Err[*VMProcess, ModuleLoadFailure]:
			failure := __gp_m8.Err

			t.Fatal(failure)
		case result.Ok[*VMProcess, ModuleLoadFailure]:
			process := __gp_m8.Value

			value := completedInvocation(t, process)
			if !term.Equal(value, term.MustAtom("true")) {
				t.Fatalf("module-set lists:member/2 = %v", value)
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}
