// Code generated by goplus from module_invocation.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"math"
	"math/big"

	"goforge.dev/goplus/std/clock"
	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/kernel"
	"goforge.dev/gotp/term"
	"goforge.dev/gotp/vm"
)

func invocationInstruction(name string, operands ...beam.Operand) beam.Instruction {
	return beam.Instruction{
		Opcode:   beam.Opcode{Name: name, Arity: len(operands)},
		Operands: operands,
	}
}

func invocationProgram(arity uint32) []beam.Instruction {
	return []beam.Instruction{
		invocationInstruction("label", beam.LabelOperand{Index: big.NewInt(1)}),
		invocationInstruction(
			"call_ext_only",
			beam.UnsignedOperand{Value: new(big.Int).SetUint64(uint64(arity))},
			beam.UnsignedOperand{Value: big.NewInt(0)},
		),
	}
}

func invokeLinkedModule(
	target vm.ExternalFunction,
	arguments []term.Term,
	linked map[string]vm.ModuleImage,
	configuredXRegisters int,
	stepLimit int,
	source clock.Clock,
	registry *CallRegistry,
) result.Result[*VMProcess, ModuleLoadFailure] {
	if uint64(len(arguments)) > uint64(math.MaxUint32) {
		return result.Err[*VMProcess, ModuleLoadFailure]{Err: InvocationArityOutOfRange{Arity: len(arguments)}}
	}
	xRegisters := configuredXRegisters
	if xRegisters > 0 && xRegisters < len(arguments) {
		xRegisters = len(arguments)
	}
	config := vm.MachineConfig{
		XRegisters:    xRegisters,
		StepLimit:     stepLimit,
		Imports:       map[uint64]vm.ExternalFunction{0: target},
		ModuleName:    "$invoke",
		LinkedModules: linked,
	}
	var machine *vm.Machine
	switch __gp_m0 := any(vm.NewMachine(invocationProgram(target.Arity), config)).(type) {
	case result.Err[*vm.Machine, vm.Failure]:
		failure := __gp_m0.Err

		return result.Err[*VMProcess, ModuleLoadFailure]{Err: MachineLoadFailure{Cause: failure}}
	case result.Ok[*vm.Machine, vm.Failure]:
		created := __gp_m0.Value

		machine = created
	default:
		panic("goplus: impossible enum value in match")
	}
	for index, argument := range arguments {
		switch __gp_m1 := any(machine.SetX(index, argument)).(type) {
		case result.Err[vm.MachineMutation, vm.Failure]:
			failure := __gp_m1.Err

			return result.Err[*VMProcess, ModuleLoadFailure]{Err: MachineLoadFailure{Cause: failure}}
		case result.Ok[vm.MachineMutation, vm.Failure]:

		default:
			panic("goplus: impossible enum value in match")
		}
	}
	switch __gp_m2 := any(NewVMProcessWithRegistry(machine, 1, source, registry)).(type) {
	case result.Err[*VMProcess, AdapterFailure]:
		failure := __gp_m2.Err

		return result.Err[*VMProcess, ModuleLoadFailure]{Err: ProcessLoadFailure{Cause: failure}}
	case result.Ok[*VMProcess, AdapterFailure]:
		process := __gp_m2.Value

		return result.Ok[*VMProcess, ModuleLoadFailure]{Value: process}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// assayxport:unit gotp.erts.module-invocation
func (module *LoadedModule) Invoke(
	function string,
	arguments []term.Term,
	source clock.Clock,
	registry *CallRegistry,
) result.Result[*VMProcess, ModuleLoadFailure] {
	if module == nil {
		return result.Err[*VMProcess, ModuleLoadFailure]{Err: NilModule{}}
	}
	if uint64(len(arguments)) > uint64(math.MaxUint32) {
		return result.Err[*VMProcess, ModuleLoadFailure]{Err: InvocationArityOutOfRange{Arity: len(arguments)}}
	}
	arity := uint32(len(arguments))
	switch __gp_m3 := any(module.Entry(function, arity)).(type) {
	case result.Err[uint64, ModuleLoadFailure]:
		failure := __gp_m3.Err

		return result.Err[*VMProcess, ModuleLoadFailure]{Err: failure}
	case result.Ok[uint64, ModuleLoadFailure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	target := vm.ExternalFunction{Module: module.name, Function: function, Arity: arity}
	return invokeLinkedModule(
		target,
		arguments,
		map[string]vm.ModuleImage{module.name: module.image()},
		module.config.XRegisters,
		module.config.StepLimit,
		source,
		registryWithModuleInfo(registry, map[string]*LoadedModule{module.name: module}),
	)
}

func (modules *ModuleSet) Invoke(
	moduleName string,
	function string,
	arguments []term.Term,
	source clock.Clock,
	registry *CallRegistry,
) result.Result[*VMProcess, ModuleLoadFailure] {
	if modules == nil {
		return result.Err[*VMProcess, ModuleLoadFailure]{Err: NilModuleSet{}}
	}
	root, present := modules.modules[moduleName]
	switch __gp_m4 := any(option.Of(root, present)).(type) {
	case option.None[*LoadedModule]:

		return result.Err[*VMProcess, ModuleLoadFailure]{Err: MissingModule{Name: moduleName}}
	case option.Some[*LoadedModule]:
		module := __gp_m4.Value

		if uint64(len(arguments)) > uint64(math.MaxUint32) {
			return result.Err[*VMProcess, ModuleLoadFailure]{Err: InvocationArityOutOfRange{Arity: len(arguments)}}
		}
		arity := uint32(len(arguments))
		switch __gp_m5 := any(module.Entry(function, arity)).(type) {
		case result.Err[uint64, ModuleLoadFailure]:
			failure := __gp_m5.Err

			return result.Err[*VMProcess, ModuleLoadFailure]{Err: failure}
		case result.Ok[uint64, ModuleLoadFailure]:

		default:
			panic("goplus: impossible enum value in match")
		}
		linked := make(map[string]vm.ModuleImage, len(modules.modules))
		for name, loaded := range modules.modules {
			linked[name] = loaded.image()
		}
		created := invokeLinkedModule(
			vm.ExternalFunction{Module: moduleName, Function: function, Arity: arity},
			arguments,
			linked,
			module.config.XRegisters,
			module.config.StepLimit,
			source,
			registryWithModuleInfo(registry, modules.modules),
		)
		switch __gp_m6 := any(created).(type) {
		case result.Err[*VMProcess, ModuleLoadFailure]:
			failure := __gp_m6.Err
			return result.Err[*VMProcess, ModuleLoadFailure]{Err: failure}
		case result.Ok[*VMProcess, ModuleLoadFailure]:
			process := __gp_m6.Value
			modules.grantProcessSpawning(process, source, registry)
			return result.Ok[*VMProcess, ModuleLoadFailure]{Value: process}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (modules *ModuleSet) grantProcessSpawning(process *VMProcess, source clock.Clock, registry *CallRegistry) {
	process.grantMFASpawning(func(context *kernel.Context, module string, function string, arguments []term.Term, link bool, monitor bool) vm.ExternalCallOutcome {
		return modules.spawnModuleProcess(context, module, function, arguments, link, monitor, source, registry)
	})
}

func (modules *ModuleSet) spawnModuleProcess(context *kernel.Context, module string, function string, arguments []term.Term, link bool, monitor bool, source clock.Clock, registry *CallRegistry) vm.ExternalCallOutcome {
	switch __gp_m7 := any(modules.Invoke(module, function, arguments, source, registry)).(type) {
	case result.Err[*VMProcess, ModuleLoadFailure]:
		failure := __gp_m7.Err
		return vm.ExternalCallRejected{Detail: ModuleLoadFailureError(failure)}
	case result.Ok[*VMProcess, ModuleLoadFailure]:
		child := __gp_m7.Value
		return spawnLoadedProcess(context, child, link, monitor)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func spawnLoadedProcess(context *kernel.Context, child *VMProcess, link bool, monitor bool) vm.ExternalCallOutcome {
	var policy kernel.SpawnPolicy = kernel.Unlinked{TrapExit: false}
	if link {
		policy = kernel.Linked{To: context.Self(), TrapExit: false}
	}
	spawned := context.SpawnResult(child.Behavior(), policy)
	if !spawned.Accepted {
		return vm.ExternalCallRejected{Detail: spawned.Detail}
	}
	if !monitor {
		return vm.ExternalCallReturned{Value: term.PIDValue(spawned.PID)}
	}
	return monitorSpawnedProcess(context, spawned.PID)
}

func monitorSpawnedProcess(context *kernel.Context, pid term.PID) vm.ExternalCallOutcome {
	monitored := context.MonitorResult(pid)
	if !monitored.Accepted {
		return vm.ExternalCallRejected{Detail: monitored.Detail}
	}
	return vm.ExternalCallReturned{Value: term.Tuple(term.PIDValue(pid), term.ReferenceValue(monitored.Reference))}
}
