// Code generated by goplus from otp_pure_bifs.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"math"
	"math/big"
	"strconv"
	"strings"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/term"
	"goforge.dev/gotp/vm"
)

//goplus:enum otpNumber
type otpNumber interface{ isOtpNumber() }

//goplus:variant (otpNumber) otpInteger(Value *big.Int)
type otpInteger struct {
	value *big.Int
}

func (otpInteger) isOtpNumber() {}

//goplus:variant (otpNumber) otpFloat(Value float64)
type otpFloat struct {
	value float64
}

func (otpFloat) isOtpNumber() {}

// otpNumberCases selects one handler per otpNumber variant for otpNumberFold.
type otpNumberCases[R any] struct {
	otpInteger func(Value *big.Int) R
	otpFloat   func(Value float64) R
}

// otpNumberFold reduces otpNumber by one-level case analysis.
func otpNumberFold[R any](o otpNumber, cs otpNumberCases[R]) R {
	switch m := any(o).(type) {
	case otpInteger:
		return cs.otpInteger(m.value)
	case otpFloat:
		return cs.otpFloat(m.value)
	default:
		panic("goplus: impossible enum value in otpNumberFold")
	}
}

// otpNumberEqOverrides carries optional per-variant hooks for otpNumberEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type otpNumberEqOverrides struct {
	otpInteger func(x, y otpInteger) (eq, handled bool)
	otpFloat   func(x, y otpFloat) (eq, handled bool)
}

// otpNumberEqualWith reports structural equality of a and b under ov.
func otpNumberEqualWith(a, b otpNumber, ov otpNumberEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case otpInteger:
		y, ok := any(b).(otpInteger)
		if !ok {
			return false
		}
		if ov.otpInteger != nil {
			if eq, handled := ov.otpInteger(x, y); handled {
				return eq
			}
		}
		if x.value != y.value {
			return false
		}
		return true
	case otpFloat:
		y, ok := any(b).(otpFloat)
		if !ok {
			return false
		}
		if ov.otpFloat != nil {
			if eq, handled := ov.otpFloat(x, y); handled {
				return eq
			}
		}
		if x.value != y.value {
			return false
		}
		return true
	}
	return false
}

// otpNumberEqual reports structural equality of a and b.
func otpNumberEqual(a, b otpNumber) bool {
	return otpNumberEqualWith(a, b, otpNumberEqOverrides{})
}

//goplus:enum otpArithmeticOperation
type otpArithmeticOperation interface{ isOtpArithmeticOperation() }

//goplus:variant (otpArithmeticOperation) otpAdd()
type otpAdd struct{}

func (otpAdd) isOtpArithmeticOperation() {}

//goplus:variant (otpArithmeticOperation) otpSubtract()
type otpSubtract struct{}

func (otpSubtract) isOtpArithmeticOperation() {}

//goplus:variant (otpArithmeticOperation) otpMultiply()
type otpMultiply struct{}

func (otpMultiply) isOtpArithmeticOperation() {}

// otpArithmeticOperationCases selects one handler per otpArithmeticOperation variant for otpArithmeticOperationFold.
type otpArithmeticOperationCases[R any] struct {
	otpAdd      func() R
	otpSubtract func() R
	otpMultiply func() R
}

// otpArithmeticOperationFold reduces otpArithmeticOperation by one-level case analysis.
func otpArithmeticOperationFold[R any](o otpArithmeticOperation, cs otpArithmeticOperationCases[R]) R {
	switch any(o).(type) {
	case otpAdd:
		return cs.otpAdd()
	case otpSubtract:
		return cs.otpSubtract()
	case otpMultiply:
		return cs.otpMultiply()
	default:
		panic("goplus: impossible enum value in otpArithmeticOperationFold")
	}
}

// otpArithmeticOperationEqOverrides carries optional per-variant hooks for otpArithmeticOperationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type otpArithmeticOperationEqOverrides struct {
	otpAdd      func(x, y otpAdd) (eq, handled bool)
	otpSubtract func(x, y otpSubtract) (eq, handled bool)
	otpMultiply func(x, y otpMultiply) (eq, handled bool)
}

// otpArithmeticOperationEqualWith reports structural equality of a and b under ov.
func otpArithmeticOperationEqualWith(a, b otpArithmeticOperation, ov otpArithmeticOperationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case otpAdd:
		y, ok := any(b).(otpAdd)
		if !ok {
			return false
		}
		if ov.otpAdd != nil {
			if eq, handled := ov.otpAdd(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case otpSubtract:
		y, ok := any(b).(otpSubtract)
		if !ok {
			return false
		}
		if ov.otpSubtract != nil {
			if eq, handled := ov.otpSubtract(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case otpMultiply:
		y, ok := any(b).(otpMultiply)
		if !ok {
			return false
		}
		if ov.otpMultiply != nil {
			if eq, handled := ov.otpMultiply(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// otpArithmeticOperationEqual reports structural equality of a and b.
func otpArithmeticOperationEqual(a, b otpArithmeticOperation) bool {
	return otpArithmeticOperationEqualWith(a, b, otpArithmeticOperationEqOverrides{})
}

func otpBadarg() vm.ExternalCallOutcome {
	return vm.ExternalCallRejected{Detail: "badarg"}
}

func otpBadarith() vm.ExternalCallOutcome {
	return vm.ExternalCallRejected{Detail: "badarith"}
}

// assayxport:unit gotp.erts.otp-exception-bifs
func otpError(arguments []term.Term) vm.ExternalCallOutcome {
	return vm.ExternalCallRaised{Class: term.MustAtom("error"), Reason: term.Clone(arguments[0])}
}

func otpThrow(arguments []term.Term) vm.ExternalCallOutcome {
	return vm.ExternalCallRaised{Class: term.MustAtom("throw"), Reason: term.Clone(arguments[0])}
}

func otpExit(arguments []term.Term) vm.ExternalCallOutcome {
	return vm.ExternalCallRaised{Class: term.MustAtom("exit"), Reason: term.Clone(arguments[0])}
}

func otpRaise(arguments []term.Term) vm.ExternalCallOutcome {
	switch __gp_m0 := any(term.AtomName(arguments[0])).(type) {
	case option.Some[string]:
		class := __gp_m0.Value

		switch class {
		case "error", "exit", "throw":
			return vm.ExternalCallRaised{Class: term.Clone(arguments[0]), Reason: term.Clone(arguments[1])}
		default:
			return vm.ExternalCallRaised{Class: term.MustAtom("error"), Reason: term.MustAtom("badarg")}
		}
	case option.None[string]:

		return vm.ExternalCallRaised{Class: term.MustAtom("error"), Reason: term.MustAtom("badarg")}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpNumberOf(value term.Term) option.Option[otpNumber] {
	switch __gp_m1 := any(term.IntegerValue(value)).(type) {
	case option.Some[*big.Int]:
		integer := __gp_m1.Value

		return option.Some[otpNumber]{Value: otpInteger{value: integer}}
	case option.None[*big.Int]:

	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m2 := any(term.FloatValue(value)).(type) {
	case option.Some[float64]:
		float := __gp_m2.Value

		return option.Some[otpNumber]{Value: otpFloat{value: float}}
	case option.None[float64]:

		return option.None[otpNumber]{}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpFloatOf(value otpNumber) option.Option[float64] {
	switch __gp_m3 := any(value).(type) {
	case otpFloat:
		float := __gp_m3.value

		return option.Some[float64]{Value: float}
	case otpInteger:
		integer := __gp_m3.value

		float, _ := integer.Float64()
		if math.IsInf(float, 0) {
			return option.None[float64]{}
		}
		return option.Some[float64]{Value: float}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpArithmetic(arguments []term.Term, operation otpArithmeticOperation) vm.ExternalCallOutcome {
	var left otpNumber
	switch __gp_m4 := any(otpNumberOf(arguments[0])).(type) {
	case option.None[otpNumber]:

		return otpBadarith()
	case option.Some[otpNumber]:
		number := __gp_m4.Value

		left = number
	default:
		panic("goplus: impossible enum value in match")
	}
	var right otpNumber
	switch __gp_m5 := any(otpNumberOf(arguments[1])).(type) {
	case option.None[otpNumber]:

		return otpBadarith()
	case option.Some[otpNumber]:
		number := __gp_m5.Value

		right = number
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m6 := any(left).(type) {
	case otpInteger:
		leftInteger := __gp_m6.value

		switch __gp_m7 := any(right).(type) {
		case otpInteger:
			rightInteger := __gp_m7.value

			value := new(big.Int)
			switch any(operation).(type) {
			case otpAdd:

				value.Add(leftInteger, rightInteger)
			case otpSubtract:

				value.Sub(leftInteger, rightInteger)
			case otpMultiply:

				value.Mul(leftInteger, rightInteger)
			default:
				panic("goplus: impossible enum value in match")
			}
			return vm.ExternalCallReturned{Value: term.MustBigInteger(value)}
		case otpFloat:

		default:
			panic("goplus: impossible enum value in match")
		}
	case otpFloat:

	default:
		panic("goplus: impossible enum value in match")
	}
	var leftFloat float64
	switch __gp_m9 := any(otpFloatOf(left)).(type) {
	case option.None[float64]:

		return otpBadarith()
	case option.Some[float64]:
		value := __gp_m9.Value

		leftFloat = value
	default:
		panic("goplus: impossible enum value in match")
	}
	var rightFloat float64
	switch __gp_m10 := any(otpFloatOf(right)).(type) {
	case option.None[float64]:

		return otpBadarith()
	case option.Some[float64]:
		value := __gp_m10.Value

		rightFloat = value
	default:
		panic("goplus: impossible enum value in match")
	}
	switch any(operation).(type) {
	case otpAdd:

		return vm.ExternalCallReturned{Value: term.Float(leftFloat + rightFloat)}
	case otpSubtract:

		return vm.ExternalCallReturned{Value: term.Float(leftFloat - rightFloat)}
	case otpMultiply:

		return vm.ExternalCallReturned{Value: term.Float(leftFloat * rightFloat)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpIntegerDivide(arguments []term.Term) vm.ExternalCallOutcome {
	var left *big.Int
	switch __gp_m12 := any(term.IntegerValue(arguments[0])).(type) {
	case option.None[*big.Int]:

		return otpBadarith()
	case option.Some[*big.Int]:
		value := __gp_m12.Value

		left = value
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m13 := any(term.IntegerValue(arguments[1])).(type) {
	case option.None[*big.Int]:

		return otpBadarith()
	case option.Some[*big.Int]:
		right := __gp_m13.Value

		if right.Sign() == 0 {
			return otpBadarith()
		}
		return vm.ExternalCallReturned{Value: term.MustBigInteger(new(big.Int).Quo(left, right))}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpProperElements(value term.Term) option.Option[[]term.Term] {
	var kind term.Kind = term.TermKind(value)
	switch any(kind).(type) {
	case term.ListKind:

		switch any(term.ImproperTail(value)).(type) {
		case option.Some[term.Term]:

			return option.None[[]term.Term]{}
		case option.None[term.Term]:

			return term.Elements(value)
		default:
			panic("goplus: impossible enum value in match")
		}
	case term.InvalidKind, term.IntegerKind, term.FloatKind, term.AtomKind, term.BinaryKind, term.TupleKind, term.MapKind, term.PIDKind, term.ReferenceKind, term.FunKind, term.PortKind:

		return option.None[[]term.Term]{}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpTupleElements(value term.Term) option.Option[[]term.Term] {
	var kind term.Kind = term.TermKind(value)
	switch any(kind).(type) {
	case term.TupleKind:

		return term.Elements(value)
	case term.InvalidKind, term.IntegerKind, term.FloatKind, term.AtomKind, term.BinaryKind, term.ListKind, term.MapKind, term.PIDKind, term.ReferenceKind, term.FunKind, term.PortKind:

		return option.None[[]term.Term]{}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpListAppend(arguments []term.Term) vm.ExternalCallOutcome {
	switch __gp_m17 := any(otpProperElements(arguments[0])).(type) {
	case option.None[[]term.Term]:

		return otpBadarg()
	case option.Some[[]term.Term]:
		left := __gp_m17.Value

		if len(left) == 0 {
			return vm.ExternalCallReturned{Value: term.Clone(arguments[1])}
		}
		switch __gp_m18 := any(otpProperElements(arguments[1])).(type) {
		case option.None[[]term.Term]:

			return vm.ExternalCallReturned{Value: term.ImproperList(left, arguments[1])}
		case option.Some[[]term.Term]:
			right := __gp_m18.Value

			joined := make([]term.Term, 0, len(left)+len(right))
			joined = append(joined, left...)
			joined = append(joined, right...)
			return vm.ExternalCallReturned{Value: term.List(joined...)}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpListSubtract(arguments []term.Term) vm.ExternalCallOutcome {
	var left []term.Term
	switch __gp_m19 := any(otpProperElements(arguments[0])).(type) {
	case option.None[[]term.Term]:

		return otpBadarg()
	case option.Some[[]term.Term]:
		elements := __gp_m19.Value

		left = append([]term.Term(nil), elements...)
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m20 := any(otpProperElements(arguments[1])).(type) {
	case option.None[[]term.Term]:

		return otpBadarg()
	case option.Some[[]term.Term]:
		right := __gp_m20.Value

		for _, remove := range right {
			for index, candidate := range left {
				if term.Equal(candidate, remove) {
					left = append(left[:index], left[index+1:]...)
					break
				}
			}
		}
		return vm.ExternalCallReturned{Value: term.List(left...)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpLength(arguments []term.Term) vm.ExternalCallOutcome {
	switch __gp_m21 := any(otpProperElements(arguments[0])).(type) {
	case option.None[[]term.Term]:

		return otpBadarg()
	case option.Some[[]term.Term]:
		elements := __gp_m21.Value

		return vm.ExternalCallReturned{Value: term.MustBigInteger(new(big.Int).SetUint64(uint64(len(elements))))}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpMember(arguments []term.Term) vm.ExternalCallOutcome {
	switch __gp_m22 := any(otpProperElements(arguments[1])).(type) {
	case option.None[[]term.Term]:

		return otpBadarg()
	case option.Some[[]term.Term]:
		elements := __gp_m22.Value

		for _, candidate := range elements {
			if term.Equal(arguments[0], candidate) {
				return vm.ExternalCallReturned{Value: term.MustAtom("true")}
			}
		}
		return vm.ExternalCallReturned{Value: term.MustAtom("false")}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpKeyPosition(value term.Term) option.Option[int] {
	switch __gp_m23 := any(term.IntegerValue(value)).(type) {
	case option.None[*big.Int]:

		return option.None[int]{}
	case option.Some[*big.Int]:
		integer := __gp_m23.Value

		if !integer.IsInt64() || integer.Sign() <= 0 {
			return option.None[int]{}
		}
		position := integer.Int64() - 1
		if uint64(position) > uint64(^uint(0)>>1) {
			return option.None[int]{}
		}
		return option.Some[int]{Value: int(position)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpComparesEqual(left term.Term, right term.Term) (bool, bool) {
	switch __gp_m24 := any(term.Compare(left, right)).(type) {
	case result.Err[term.Ordering, term.OrderFailure]:

		return false, false
	case result.Ok[term.Ordering, term.OrderFailure]:
		order := __gp_m24.Value

		var checked term.Ordering = order
		switch any(checked).(type) {
		case term.TermEqual:

			return true, true
		case term.TermLess, term.TermGreater:

			return false, true
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpFindKey(arguments []term.Term) (term.Term, bool, bool) {
	var position int
	switch __gp_m26 := any(otpKeyPosition(arguments[1])).(type) {
	case option.None[int]:

		return term.InvalidValue(), false, false
	case option.Some[int]:
		value := __gp_m26.Value

		position = value
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m27 := any(otpProperElements(arguments[2])).(type) {
	case option.None[[]term.Term]:

		return term.InvalidValue(), false, false
	case option.Some[[]term.Term]:
		elements := __gp_m27.Value

		for _, candidate := range elements {
			switch __gp_m28 := any(otpTupleElements(candidate)).(type) {
			case option.None[[]term.Term]:

			case option.Some[[]term.Term]:
				tuple := __gp_m28.Value

				if position < len(tuple) {
					equal, valid := otpComparesEqual(arguments[0], tuple[position])
					if !valid {
						return term.InvalidValue(), false, false
					}
					if equal {
						return term.Clone(candidate), true, true
					}
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		return term.InvalidValue(), false, true
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpKeyFind(arguments []term.Term) vm.ExternalCallOutcome {
	value, found, valid := otpFindKey(arguments)
	if !valid {
		return otpBadarg()
	}
	if !found {
		return vm.ExternalCallReturned{Value: term.MustAtom("false")}
	}
	return vm.ExternalCallReturned{Value: value}
}

func otpKeyMember(arguments []term.Term) vm.ExternalCallOutcome {
	_, found, valid := otpFindKey(arguments)
	if !valid {
		return otpBadarg()
	}
	if found {
		return vm.ExternalCallReturned{Value: term.MustAtom("true")}
	}
	return vm.ExternalCallReturned{Value: term.MustAtom("false")}
}

func otpKeySearch(arguments []term.Term) vm.ExternalCallOutcome {
	value, found, valid := otpFindKey(arguments)
	if !valid {
		return otpBadarg()
	}
	if !found {
		return vm.ExternalCallReturned{Value: term.MustAtom("false")}
	}
	return vm.ExternalCallReturned{Value: term.Tuple(term.MustAtom("value"), value)}
}

func otpCharacters(value string) term.Term {
	characters := make([]term.Term, 0, len(value))
	for _, character := range value {
		characters = append(characters, term.Integer(int64(character)))
	}
	return term.List(characters...)
}

func otpIntegerToList(arguments []term.Term) vm.ExternalCallOutcome {
	switch __gp_m29 := any(term.IntegerValue(arguments[0])).(type) {
	case option.None[*big.Int]:

		return otpBadarg()
	case option.Some[*big.Int]:
		value := __gp_m29.Value

		return vm.ExternalCallReturned{Value: otpCharacters(value.String())}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpFloatToList(arguments []term.Term) vm.ExternalCallOutcome {
	switch __gp_m30 := any(term.FloatValue(arguments[0])).(type) {
	case option.None[float64]:

		return otpBadarg()
	case option.Some[float64]:
		value := __gp_m30.Value

		text := strconv.FormatFloat(value, 'g', -1, 64)
		if !strings.ContainsAny(text, ".eE") {
			text += ".0"
		}
		return vm.ExternalCallReturned{Value: otpCharacters(text)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpAtomToList(arguments []term.Term) vm.ExternalCallOutcome {
	switch __gp_m31 := any(term.AtomName(arguments[0])).(type) {
	case option.None[string]:

		return otpBadarg()
	case option.Some[string]:
		value := __gp_m31.Value

		return vm.ExternalCallReturned{Value: otpCharacters(value)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpElement(arguments []term.Term) vm.ExternalCallOutcome {
	var index *big.Int
	switch __gp_m32 := any(term.IntegerValue(arguments[0])).(type) {
	case option.None[*big.Int]:

		return otpBadarg()
	case option.Some[*big.Int]:
		value := __gp_m32.Value

		index = value
	default:
		panic("goplus: impossible enum value in match")
	}
	if !index.IsInt64() || index.Sign() <= 0 {
		return otpBadarg()
	}
	switch __gp_m33 := any(otpTupleElements(arguments[1])).(type) {
	case option.None[[]term.Term]:

		return otpBadarg()
	case option.Some[[]term.Term]:
		elements := __gp_m33.Value

		position := index.Int64() - 1
		if position >= int64(len(elements)) {
			return otpBadarg()
		}
		return vm.ExternalCallReturned{Value: term.Clone(elements[position])}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func otpSetElement(arguments []term.Term) vm.ExternalCallOutcome {
	var index *big.Int
	switch __gp_m34 := any(term.IntegerValue(arguments[0])).(type) {
	case option.None[*big.Int]:

		return otpBadarg()
	case option.Some[*big.Int]:
		value := __gp_m34.Value

		index = value
	default:
		panic("goplus: impossible enum value in match")
	}
	if !index.IsInt64() || index.Sign() <= 0 {
		return otpBadarg()
	}
	switch __gp_m35 := any(otpTupleElements(arguments[1])).(type) {
	case option.None[[]term.Term]:

		return otpBadarg()
	case option.Some[[]term.Term]:
		elements := __gp_m35.Value

		position := index.Int64() - 1
		if position >= int64(len(elements)) {
			return otpBadarg()
		}
		updated := append([]term.Term(nil), elements...)
		updated[position] = term.Clone(arguments[2])
		return vm.ExternalCallReturned{Value: term.Tuple(updated...)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

// assayxport:unit gotp.erts.otp-pure-bifs
func otpPureBindings() []CallBinding {
	return []CallBinding{
		{Target: vm.ExternalFunction{Module: "erlang", Function: "++", Arity: 2}, Implementation: otpListAppend},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "--", Arity: 2}, Implementation: otpListSubtract},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "-", Arity: 2}, Implementation: func(arguments []term.Term) vm.ExternalCallOutcome { return otpArithmetic(arguments, otpSubtract{}) }},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "length", Arity: 1}, Implementation: otpLength},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "=:=", Arity: 2}, Implementation: func(arguments []term.Term) vm.ExternalCallOutcome {
			if term.Equal(arguments[0], arguments[1]) {
				return vm.ExternalCallReturned{Value: term.MustAtom("true")}
			}
			return vm.ExternalCallReturned{Value: term.MustAtom("false")}
		}},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "+", Arity: 2}, Implementation: func(arguments []term.Term) vm.ExternalCallOutcome { return otpArithmetic(arguments, otpAdd{}) }},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "div", Arity: 2}, Implementation: otpIntegerDivide},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "*", Arity: 2}, Implementation: func(arguments []term.Term) vm.ExternalCallOutcome { return otpArithmetic(arguments, otpMultiply{}) }},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "integer_to_list", Arity: 1}, Implementation: otpIntegerToList},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "float_to_list", Arity: 1}, Implementation: otpFloatToList},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "atom_to_list", Arity: 1}, Implementation: otpAtomToList},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "element", Arity: 2}, Implementation: otpElement},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "setelement", Arity: 3}, Implementation: otpSetElement},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "error", Arity: 1}, Implementation: otpError},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "error", Arity: 2}, Implementation: otpError},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "error", Arity: 3}, Implementation: otpError},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "throw", Arity: 1}, Implementation: otpThrow},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "exit", Arity: 1}, Implementation: otpExit},
		{Target: vm.ExternalFunction{Module: "erlang", Function: "raise", Arity: 3}, Implementation: otpRaise},
		{Target: vm.ExternalFunction{Module: "lists", Function: "member", Arity: 2}, Implementation: otpMember},
		{Target: vm.ExternalFunction{Module: "lists", Function: "keyfind", Arity: 3}, Implementation: otpKeyFind},
		{Target: vm.ExternalFunction{Module: "lists", Function: "keymember", Arity: 3}, Implementation: otpKeyMember},
		{Target: vm.ExternalFunction{Module: "lists", Function: "keysearch", Arity: 3}, Implementation: otpKeySearch},
	}
}
