// Code generated by goplus from otp_lists_conformance_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"testing"

	"goforge.dev/goplus/std/clock"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/kernel"
	"goforge.dev/gotp/term"
	"goforge.dev/gotp/vm"
)

func runPinnedLists(t *testing.T, function string, arguments []term.Term) term.Term {
	var read beam.ReadFileCapability = beam.OperatingSystemFiles{}
	var module *LoadedModule
	switch __gp_m0 := any(LoadModuleFile(read, "../beam/testdata/otp-29.0.4/lists.beam", ModuleLoaderConfig{})).(type) {
	case result.Err[*LoadedModule, ModuleLoadFailure]:
		failure := __gp_m0.Err

		t.Fatal(failure)
	case result.Ok[*LoadedModule, ModuleLoadFailure]:
		loaded := __gp_m0.Value

		module = loaded
	default:
		panic("goplus: impossible enum value in match")
	}
	var machine *vm.Machine
	switch __gp_m1 := any(module.NewMachine()).(type) {
	case result.Err[*vm.Machine, ModuleLoadFailure]:
		failure := __gp_m1.Err

		t.Fatal(failure)
	case result.Ok[*vm.Machine, ModuleLoadFailure]:
		loaded := __gp_m1.Value

		machine = loaded
	default:
		panic("goplus: impossible enum value in match")
	}
	for index, argument := range arguments {
		switch __gp_m2 := any(machine.SetX(index, argument)).(type) {
		case result.Err[vm.MachineMutation, vm.Failure]:
			failure := __gp_m2.Err

			t.Fatal(failure)
		case result.Ok[vm.MachineMutation, vm.Failure]:

		default:
			panic("goplus: impossible enum value in match")
		}
	}
	var entry uint64
	switch __gp_m3 := any(module.Entry(function, uint32(len(arguments)))).(type) {
	case result.Err[uint64, ModuleLoadFailure]:
		failure := __gp_m3.Err

		t.Fatal(failure)
	case result.Ok[uint64, ModuleLoadFailure]:
		label := __gp_m3.Value

		entry = label
	default:
		panic("goplus: impossible enum value in match")
	}
	var registry *CallRegistry
	switch __gp_m4 := any(NewOTPCallRegistry()).(type) {
	case result.Err[*CallRegistry, CallRegistryFailure]:
		failure := __gp_m4.Err

		t.Fatal(failure)
	case result.Ok[*CallRegistry, CallRegistryFailure]:
		loaded := __gp_m4.Value

		registry = loaded
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m5 := any(NewVMProcessWithRegistry(machine, entry, clock.Real{}, registry)).(type) {
	case result.Err[*VMProcess, AdapterFailure]:
		failure := __gp_m5.Err

		t.Fatal(failure)
	case result.Ok[*VMProcess, AdapterFailure]:
		process := __gp_m5.Value

		runtime := kernel.New(kernel.KernelConfig{})
		switch __gp_m6 := any(runtime.Spawn(process.Behavior(), kernel.Unlinked{TrapExit: false})).(type) {
		case result.Err[term.PID, kernel.Failure]:
			failure := __gp_m6.Err

			t.Fatal(failure)
		case result.Ok[term.PID, kernel.Failure]:

		default:
			panic("goplus: impossible enum value in match")
		}
		runtime.Run(100)
		var state VMProcessState = process.State()
		switch __gp_m7 := any(state).(type) {
		case VMProcessCompleted:
			value := __gp_m7.Value

			return value
		case VMProcessRunning, VMProcessSuspended, VMProcessWaiting, VMProcessRaised, VMProcessFailed:

			t.Fatalf("lists:%s/%d state = %T: %v", function, len(arguments), state, state)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
	panic("unreachable")
}

// assayxport:law gotp.erts.pinned-otp-lists-laws
func TestPinnedOTPListsPureBIFPaths(t *testing.T) {
	values := term.List(term.Integer(1), term.Integer(2), term.Integer(3), term.Integer(4))
	if got := runPinnedLists(t, "sum", []term.Term{values}); !term.Equal(got, term.Integer(10)) {
		t.Fatalf("lists:sum/1 = %v", got)
	}
	appended := runPinnedLists(t, "append", []term.Term{
		term.List(term.Integer(1), term.Integer(2)),
		term.List(term.Integer(3), term.Integer(4)),
	})
	want := term.List(term.Integer(1), term.Integer(2), term.Integer(3), term.Integer(4))
	if !term.Equal(appended, want) {
		t.Fatalf("lists:append/2 = %v", appended)
	}
}

func TestPinnedOTPListsTermOrderPaths(t *testing.T) {
	sequence := runPinnedLists(t, "seq", []term.Term{term.Integer(1), term.Integer(3)})
	if !term.Equal(sequence, term.List(term.Integer(1), term.Integer(2), term.Integer(3))) {
		t.Fatalf("lists:seq/2 = %v", sequence)
	}
	duplicated := runPinnedLists(t, "duplicate", []term.Term{term.Integer(3), term.MustAtom("a")})
	if !term.Equal(duplicated, term.List(term.MustAtom("a"), term.MustAtom("a"), term.MustAtom("a"))) {
		t.Fatalf("lists:duplicate/2 = %v", duplicated)
	}
	values := term.List(term.Integer(3), term.Integer(1), term.Integer(2))
	if got := runPinnedLists(t, "min", []term.Term{values}); !term.Equal(got, term.Integer(1)) {
		t.Fatalf("lists:min/1 = %v", got)
	}
	if got := runPinnedLists(t, "max", []term.Term{values}); !term.Equal(got, term.Integer(3)) {
		t.Fatalf("lists:max/1 = %v", got)
	}
	if got := runPinnedLists(t, "nth", []term.Term{term.Integer(2), values}); !term.Equal(got, term.Integer(1)) {
		t.Fatalf("lists:nth/2 = %v", got)
	}
}
