// Code generated by goplus from otp_gb_sets_callbacks_differential_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"os"
	"strconv"
	"strings"
	"testing"

	"goforge.dev/goplus/std/clock"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/term"
)

// assayxport:law gotp.erts.otp29-gb_sets-callback-differential
func TestPinnedOTPGbSetsCallbackDifferentialCorpus(t *testing.T) {
	payload, cause := os.ReadFile("testdata/otp-29.0.4-gb_sets-callbacks.corpus")
	if cause != nil {
		t.Fatal(cause)
	}
	var read beam.ReadFileCapability = beam.OperatingSystemFiles{}
	var callback *LoadedModule
	switch __gp_m0 := any(LoadModuleFile(read, "testdata/otp-29.0.4/gb_sets_callbacks.beam", ModuleLoaderConfig{})).(type) {
	case result.Err[*LoadedModule, ModuleLoadFailure]:
		failure := __gp_m0.Err
		t.Fatal(failure)
	case result.Ok[*LoadedModule, ModuleLoadFailure]:
		found := __gp_m0.Value
		callback = found
	default:
		panic("goplus: impossible enum value in match")
	}
	var modules *ModuleSet
	switch __gp_m1 := any(NewModuleSet([]*LoadedModule{pinnedGbSetsModule(t), pinnedListsModule(t), pinnedStdlibDependency(t, "ordsets"), callback})).(type) {
	case result.Err[*ModuleSet, ModuleLoadFailure]:
		failure := __gp_m1.Err
		t.Fatal(failure)
	case result.Ok[*ModuleSet, ModuleLoadFailure]:
		found := __gp_m1.Value
		modules = found
	default:
		panic("goplus: impossible enum value in match")
	}
	registry := otpRegistryForInvocation(t)
	for lineNumber, line := range strings.Split(strings.TrimSpace(string(payload)), "\n") {
		if strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, "|")
		if len(fields) != 7 || fields[0] != "case" {
			t.Fatalf("line %d is malformed", lineNumber+1)
		}
		arity, cause := strconv.Atoi(fields[2])
		if cause != nil {
			t.Fatal(cause)
		}
		argumentsTerm := decodeGbSetsCorpusTerm(t, fields[5])
		var arguments []term.Term
		switch __gp_m2 := any(argumentsTerm).(type) {
		case term.ProperListTerm:
			found := __gp_m2.Elements
			arguments = found
		default:
			t.Fatalf("%s/%d arguments differ", fields[1], arity)
		}
		var process *VMProcess
		switch __gp_m3 := any(modules.Invoke("gb_sets_callbacks", fields[1], arguments, clock.Real{}, registry)).(type) {
		case result.Err[*VMProcess, ModuleLoadFailure]:
			failure := __gp_m3.Err
			t.Fatal(failure)
		case result.Ok[*VMProcess, ModuleLoadFailure]:
			found := __gp_m3.Value
			process = found
		default:
			panic("goplus: impossible enum value in match")
		}
		runGbSetsCorpusProcess(t, process)
		assertGbSetsCorpusOutcome(t, fields[3], arity, process.State(), decodeGbSetsCorpusTerm(t, fields[6]))
	}
}
