// Code generated by goplus from otp_gen_server_async_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"os"
	"strings"
	"testing"

	"goforge.dev/goplus/std/clock"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/kernel"
	"goforge.dev/gotp/term"
)

// assayxport:law gotp.erts.otp29-gen-server-async-requests
func TestPinnedOTPGenServerAsyncRequests(t *testing.T) {
	payload, cause := os.ReadFile("testdata/otp-29.0.4-gen_server-async.corpus")
	if cause != nil {
		t.Fatal(cause)
	}
	var read beam.ReadFileCapability = beam.OperatingSystemFiles{}
	var callback *LoadedModule
	switch __gp_m0 := any(LoadModuleFile(read, "testdata/otp-29.0.4/gen_server_async_callbacks.beam", ModuleLoaderConfig{})).(type) {
	case result.Err[*LoadedModule, ModuleLoadFailure]:
		failure := __gp_m0.Err
		t.Fatal(failure)
	case result.Ok[*LoadedModule, ModuleLoadFailure]:
		found := __gp_m0.Value
		callback = found
	default:
		panic("goplus: impossible enum value in match")
	}
	dependencies := []string{"sets", "gen", "proc_lib", "sys", "global", "code", "io", "io_lib", "logger", "logger_config", "error_logger"}
	loaded := []*LoadedModule{callback, pinnedGenServerModule(t), pinnedListsModule(t), pinnedMapsModule(t)}
	for _, dependency := range dependencies {
		loaded = append(loaded, pinnedStdlibDependency(t, dependency))
	}
	var modules *ModuleSet
	switch __gp_m1 := any(NewModuleSet(loaded)).(type) {
	case result.Err[*ModuleSet, ModuleLoadFailure]:
		failure := __gp_m1.Err
		t.Fatal(failure)
	case result.Ok[*ModuleSet, ModuleLoadFailure]:
		found := __gp_m1.Value
		modules = found
	default:
		panic("goplus: impossible enum value in match")
	}
	registry := otpRegistryForInvocation(t)
	for lineNumber, line := range strings.Split(strings.TrimSpace(string(payload)), "\n") {
		fields := strings.Split(line, "|")
		if len(fields) != 3 || fields[0] != "case" {
			t.Fatalf("line %d is malformed", lineNumber+1)
		}
		expected := decodeGenServerCorpusTerm(t, fields[2])
		var process *VMProcess
		switch __gp_m2 := any(modules.Invoke("gen_server_async_callbacks", fields[1], []term.Term{}, clock.Real{}, registry)).(type) {
		case result.Err[*VMProcess, ModuleLoadFailure]:
			failure := __gp_m2.Err
			t.Fatal(failure)
		case result.Ok[*VMProcess, ModuleLoadFailure]:
			created := __gp_m2.Value
			process = created
		default:
			panic("goplus: impossible enum value in match")
		}
		runtime := kernel.New(kernel.KernelConfig{})
		runtime.PersistentPut(term.Tuple(term.MustAtom("logger_config"), term.MustAtom("$primary_config$")), term.Integer(0))
		switch __gp_m3 := any(runtime.Spawn(process.Behavior(), kernel.Unlinked{TrapExit: false})).(type) {
		case result.Err[term.PID, kernel.Failure]:
			failure := __gp_m3.Err
			t.Fatal(failure)
		case result.Ok[term.PID, kernel.Failure]:
		default:
			panic("goplus: impossible enum value in match")
		}
		runtime.Run(1_000_000)
		assertGenServerCorpusOutcome(t, fields[1], 0, process.State(), expected)
	}
}
