// Code generated by goplus from receive_timeout_example_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package erts

import (
	"math/big"
	"testing"
	"time"

	"goforge.dev/goplus/std/clock"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/beam"
	"goforge.dev/gotp/kernel"
	"goforge.dev/gotp/term"
	"goforge.dev/gotp/vm"
)

func adapterTimeoutMachine(milliseconds int64) *vm.Machine {
	program := []beam.Instruction{
		{Opcode: beam.Opcode{Name: "label", Arity: 1}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(1)}}},
		{Opcode: beam.Opcode{Name: "loop_rec", Arity: 2}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(2)}, beam.XRegisterOperand{Index: big.NewInt(0)}}},
		{Opcode: beam.Opcode{Name: "label", Arity: 1}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(2)}}},
		{Opcode: beam.Opcode{Name: "wait_timeout", Arity: 2}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(1)}, beam.IntegerOperand{Value: big.NewInt(milliseconds)}}},
		{Opcode: beam.Opcode{Name: "timeout", Arity: 0}},
		{Opcode: beam.Opcode{Name: "move", Arity: 2}, Operands: []beam.Operand{beam.IntegerOperand{Value: big.NewInt(42)}, beam.XRegisterOperand{Index: big.NewInt(0)}}},
		{Opcode: beam.Opcode{Name: "return", Arity: 0}},
	}
	switch __gp_m0 := any(vm.NewMachine(program, vm.MachineConfig{XRegisters: 2, StepLimit: 100})).(type) {
	case result.Err[*vm.Machine, vm.Failure]:
		failure := __gp_m0.Err

		panic(vm.Error(failure))
	case result.Ok[*vm.Machine, vm.Failure]:
		machine := __gp_m0.Value

		return machine
	default:
		panic("goplus: impossible enum value in match")
	}
}

func adapterMessageBeforeTimeoutMachine(milliseconds int64) *vm.Machine {
	program := []beam.Instruction{
		{Opcode: beam.Opcode{Name: "label", Arity: 1}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(1)}}},
		{Opcode: beam.Opcode{Name: "loop_rec", Arity: 2}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(2)}, beam.XRegisterOperand{Index: big.NewInt(0)}}},
		{Opcode: beam.Opcode{Name: "remove_message", Arity: 0}},
		{Opcode: beam.Opcode{Name: "move", Arity: 2}, Operands: []beam.Operand{beam.IntegerOperand{Value: big.NewInt(7)}, beam.XRegisterOperand{Index: big.NewInt(0)}}},
		{Opcode: beam.Opcode{Name: "return", Arity: 0}},
		{Opcode: beam.Opcode{Name: "label", Arity: 1}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(2)}}},
		{Opcode: beam.Opcode{Name: "wait_timeout", Arity: 2}, Operands: []beam.Operand{beam.LabelOperand{Index: big.NewInt(1)}, beam.IntegerOperand{Value: big.NewInt(milliseconds)}}},
		{Opcode: beam.Opcode{Name: "timeout", Arity: 0}},
		{Opcode: beam.Opcode{Name: "move", Arity: 2}, Operands: []beam.Operand{beam.IntegerOperand{Value: big.NewInt(42)}, beam.XRegisterOperand{Index: big.NewInt(0)}}},
		{Opcode: beam.Opcode{Name: "return", Arity: 0}},
	}
	switch __gp_m1 := any(vm.NewMachine(program, vm.MachineConfig{XRegisters: 2, StepLimit: 100})).(type) {
	case result.Err[*vm.Machine, vm.Failure]:
		failure := __gp_m1.Err

		panic(vm.Error(failure))
	case result.Ok[*vm.Machine, vm.Failure]:
		machine := __gp_m1.Value

		return machine
	default:
		panic("goplus: impossible enum value in match")
	}
}

// assayxport:law gotp.erts.receive-timeout-laws
func TestReceiveTimeoutUsesInjectedClock(t *testing.T) {
	source := clock.NewFake(time.Unix(1_000, 0))
	var process *VMProcess
	switch __gp_m2 := any(NewVMProcessWithClock(adapterTimeoutMachine(10), 1, source)).(type) {
	case result.Err[*VMProcess, AdapterFailure]:
		failure := __gp_m2.Err

		t.Fatal(failure)
	case result.Ok[*VMProcess, AdapterFailure]:
		created := __gp_m2.Value

		process = created
	default:
		panic("goplus: impossible enum value in match")
	}
	runtime := kernel.New(kernel.KernelConfig{})
	switch __gp_m3 := any(runtime.Spawn(process.Behavior(), kernel.Unlinked{TrapExit: false})).(type) {
	case result.Err[term.PID, kernel.Failure]:
		failure := __gp_m3.Err

		t.Fatal(failure)
	case result.Ok[term.PID, kernel.Failure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	runtime.Run(10)
	var waiting VMProcessState = process.State()
	switch any(waiting).(type) {
	case VMProcessWaiting:

	case VMProcessRunning, VMProcessSuspended, VMProcessCompleted, VMProcessRaised, VMProcessFailed:

		t.Fatalf("expected waiting state, got %T", waiting)
	default:
		panic("goplus: impossible enum value in match")
	}
	source.Advance(10*time.Millisecond - time.Nanosecond)
	runtime.Run(10)
	var early VMProcessState = process.State()
	switch any(early).(type) {
	case VMProcessWaiting:

	case VMProcessRunning, VMProcessSuspended, VMProcessCompleted, VMProcessRaised, VMProcessFailed:

		t.Fatalf("timer fired early: %T", early)
	default:
		panic("goplus: impossible enum value in match")
	}
	source.Advance(time.Nanosecond)
	runtime.Run(10)
	var completed VMProcessState = process.State()
	switch __gp_m6 := any(completed).(type) {
	case VMProcessCompleted:
		value := __gp_m6.Value

		if !term.Equal(value, term.Integer(42)) {
			t.Fatalf("unexpected value: %v", value)
		}
	case VMProcessRunning, VMProcessSuspended, VMProcessWaiting, VMProcessRaised, VMProcessFailed:

		t.Fatalf("expected completed state, got %T", completed)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestSelectedMessageCancelsReceiveTimeout(t *testing.T) {
	source := clock.NewFake(time.Unix(2_000, 0))
	var process *VMProcess
	switch __gp_m7 := any(NewVMProcessWithClock(adapterMessageBeforeTimeoutMachine(100), 1, source)).(type) {
	case result.Err[*VMProcess, AdapterFailure]:
		failure := __gp_m7.Err

		t.Fatal(failure)
	case result.Ok[*VMProcess, AdapterFailure]:
		created := __gp_m7.Value

		process = created
	default:
		panic("goplus: impossible enum value in match")
	}
	runtime := kernel.New(kernel.KernelConfig{})
	var pid term.PID
	switch __gp_m8 := any(runtime.Spawn(process.Behavior(), kernel.Unlinked{TrapExit: false})).(type) {
	case result.Err[term.PID, kernel.Failure]:
		failure := __gp_m8.Err

		t.Fatal(failure)
	case result.Ok[term.PID, kernel.Failure]:
		spawned := __gp_m8.Value

		pid = spawned
	default:
		panic("goplus: impossible enum value in match")
	}
	runtime.Run(10)
	runtime.Send(pid, pid, term.Integer(9))
	runtime.Run(10)
	var selected VMProcessState = process.State()
	switch __gp_m9 := any(selected).(type) {
	case VMProcessCompleted:
		value := __gp_m9.Value

		if !term.Equal(value, term.Integer(7)) {
			t.Fatalf("message branch returned %v", value)
		}
	case VMProcessRunning, VMProcessSuspended, VMProcessWaiting, VMProcessRaised, VMProcessFailed:

		t.Fatalf("message did not complete receive: %T", selected)
	default:
		panic("goplus: impossible enum value in match")
	}
	source.Advance(100 * time.Millisecond)
	runtime.Run(10)
	var afterDeadline VMProcessState = process.State()
	switch __gp_m10 := any(afterDeadline).(type) {
	case VMProcessCompleted:
		value := __gp_m10.Value

		if !term.Equal(value, term.Integer(7)) {
			t.Fatalf("cancelled timeout changed result to %v", value)
		}
	case VMProcessRunning, VMProcessSuspended, VMProcessWaiting, VMProcessRaised, VMProcessFailed:

		t.Fatalf("cancelled timeout resumed process: %T", afterDeadline)
	default:
		panic("goplus: impossible enum value in match")
	}
}
