// Code generated by goplus from decode.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package etf decodes bounded Erlang External Term Format values.
package etf

import "iter"

import (
	"bytes"
	"compress/zlib"
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"math/big"

	"goforge.dev/goplus/std/result"
)

const Version = 131

// RawTerm preserves every ETF shape, including values that are not yet part of
// GoTP's immutable runtime term algebra.
//
//goplus:enum RawTerm
type RawTerm interface{ isRawTerm() }

//goplus:variant (RawTerm) RawInteger(Value *big.Int)
type RawInteger struct {
	Value *big.Int
}

func (RawInteger) isRawTerm() {}

//goplus:variant (RawTerm) RawFloat(Value float64)
type RawFloat struct {
	Value float64
}

func (RawFloat) isRawTerm() {}

//goplus:variant (RawTerm) RawAtom(Name string)
type RawAtom struct {
	Name string
}

func (RawAtom) isRawTerm() {}

//goplus:variant (RawTerm) RawTuple(Elements []RawTerm)
type RawTuple struct {
	Elements []RawTerm
}

func (RawTuple) isRawTerm() {}

//goplus:variant (RawTerm) RawNil()
type RawNil struct{}

func (RawNil) isRawTerm() {}

//goplus:variant (RawTerm) RawString(Text string)
type RawString struct {
	Text string
}

func (RawString) isRawTerm() {}

//goplus:variant (RawTerm) RawList(Elements []RawTerm, Tail RawTerm)
type RawList struct {
	Elements []RawTerm
	Tail     RawTerm
}

func (RawList) isRawTerm() {}

//goplus:variant (RawTerm) RawBinary(Bytes []byte)
type RawBinary struct {
	Bytes []byte
}

func (RawBinary) isRawTerm() {}

//goplus:variant (RawTerm) RawBitBinary(Bytes []byte, Bits uint8)
type RawBitBinary struct {
	Bytes []byte
	Bits  uint8
}

func (RawBitBinary) isRawTerm() {}

//goplus:variant (RawTerm) RawMap(Pairs []RawPair)
type RawMap struct {
	Pairs []RawPair
}

func (RawMap) isRawTerm() {}

//goplus:variant (RawTerm) RawPID(Identity NodeIdentity)
type RawPID struct {
	Identity NodeIdentity
}

func (RawPID) isRawTerm() {}

//goplus:variant (RawTerm) RawPort(Identity NodeIdentity)
type RawPort struct {
	Identity NodeIdentity
}

func (RawPort) isRawTerm() {}

//goplus:variant (RawTerm) RawReference(Identity NodeIdentity)
type RawReference struct {
	Identity NodeIdentity
}

func (RawReference) isRawTerm() {}

//goplus:variant (RawTerm) RawExport(Module string, Function string, Arity uint32)
type RawExport struct {
	Module   string
	Function string
	Arity    uint32
}

func (RawExport) isRawTerm() {}

//goplus:variant (RawTerm) RawOpaque(Tag byte, Bytes []byte)
type RawOpaque struct {
	Tag   byte
	Bytes []byte
}

func (RawOpaque) isRawTerm() {}

// RawTermCases selects one handler per RawTerm variant for RawTermFold.
type RawTermCases[R any] struct {
	RawInteger   func(Value *big.Int) R
	RawFloat     func(Value float64) R
	RawAtom      func(Name string) R
	RawTuple     func(Elements []RawTerm) R
	RawNil       func() R
	RawString    func(Text string) R
	RawList      func(Elements []RawTerm, Tail RawTerm) R
	RawBinary    func(Bytes []byte) R
	RawBitBinary func(Bytes []byte, Bits uint8) R
	RawMap       func(Pairs []RawPair) R
	RawPID       func(Identity NodeIdentity) R
	RawPort      func(Identity NodeIdentity) R
	RawReference func(Identity NodeIdentity) R
	RawExport    func(Module string, Function string, Arity uint32) R
	RawOpaque    func(Tag byte, Bytes []byte) R
}

// RawTermFold reduces RawTerm by one-level case analysis.
func RawTermFold[R any](v RawTerm, cs RawTermCases[R]) R {
	switch m := any(v).(type) {
	case RawInteger:
		return cs.RawInteger(m.Value)
	case RawFloat:
		return cs.RawFloat(m.Value)
	case RawAtom:
		return cs.RawAtom(m.Name)
	case RawTuple:
		return cs.RawTuple(m.Elements)
	case RawNil:
		return cs.RawNil()
	case RawString:
		return cs.RawString(m.Text)
	case RawList:
		return cs.RawList(m.Elements, m.Tail)
	case RawBinary:
		return cs.RawBinary(m.Bytes)
	case RawBitBinary:
		return cs.RawBitBinary(m.Bytes, m.Bits)
	case RawMap:
		return cs.RawMap(m.Pairs)
	case RawPID:
		return cs.RawPID(m.Identity)
	case RawPort:
		return cs.RawPort(m.Identity)
	case RawReference:
		return cs.RawReference(m.Identity)
	case RawExport:
		return cs.RawExport(m.Module, m.Function, m.Arity)
	case RawOpaque:
		return cs.RawOpaque(m.Tag, m.Bytes)
	default:
		panic("goplus: impossible enum value in RawTermFold")
	}
}

// RawTermChildren lists the direct RawTerm subterms of r.
func RawTermChildren(r RawTerm) []RawTerm {
	var out []RawTerm
	switch m := any(r).(type) {
	case RawTuple:
		for _, c0 := range m.Elements {
			if c0 != nil {
				out = append(out, c0)
			}
		}
	case RawList:
		for _, c1 := range m.Elements {
			if c1 != nil {
				out = append(out, c1)
			}
		}
		if m.Tail != nil {
			out = append(out, m.Tail)
		}
	case RawMap:
		for _, w2 := range m.Pairs {
			if w2.Key != nil {
				out = append(out, w2.Key)
			}
			if w2.Value != nil {
				out = append(out, w2.Value)
			}
		}
	}
	return out
}

// RawTermUniverse yields r and all transitive RawTerm subterms, preorder.
func RawTermUniverse(r RawTerm) iter.Seq[RawTerm] {
	return func(yield func(RawTerm) bool) {
		var walk func(RawTerm) bool
		walk = func(cur RawTerm) bool {
			if !yield(cur) {
				return false
			}
			for _, c := range RawTermChildren(cur) {
				if !walk(c) {
					return false
				}
			}
			return true
		}
		walk(r)
	}
}

// RawTermTransform rewrites r bottom-up: children first, then f at each node.
func RawTermTransform(r RawTerm, f func(RawTerm) RawTerm) RawTerm {
	switch m := any(r).(type) {
	case RawTuple:
		if len(m.Elements) > 0 {
			s3 := make([]RawTerm, len(m.Elements))
			for i3, x3 := range m.Elements {
				s3[i3] = x3
				if x3 != nil {
					s3[i3] = RawTermTransform(x3, f)
				}
			}
			m.Elements = s3
		}
		return f(m)
	case RawList:
		if len(m.Elements) > 0 {
			s4 := make([]RawTerm, len(m.Elements))
			for i4, x4 := range m.Elements {
				s4[i4] = x4
				if x4 != nil {
					s4[i4] = RawTermTransform(x4, f)
				}
			}
			m.Elements = s4
		}
		if m.Tail != nil {
			m.Tail = RawTermTransform(m.Tail, f)
		}
		return f(m)
	case RawMap:
		if len(m.Pairs) > 0 {
			s5 := make([]RawPair, len(m.Pairs))
			copy(s5, m.Pairs)
			for i5 := range s5 {
				if s5[i5].Key != nil {
					s5[i5].Key = RawTermTransform(s5[i5].Key, f)
				}
				if s5[i5].Value != nil {
					s5[i5].Value = RawTermTransform(s5[i5].Value, f)
				}
			}
			m.Pairs = s5
		}
		return f(m)
	}
	return f(r)
}

type RawPair struct {
	Key   RawTerm
	Value RawTerm
}

type NodeIdentity struct {
	Node     string
	ID       []uint32
	Serial   uint32
	Creation uint32
}

type Limits struct {
	MaxDepth int
	MaxTerms int
	MaxBytes int
}

func DefaultLimits() Limits {
	return Limits{MaxDepth: 256, MaxTerms: 1_000_000, MaxBytes: 256 << 20}
}

type rawDecoder struct {
	data   []byte
	at     int
	limits Limits
	terms  int
}

func Decode(data []byte, limits Limits) result.Result[RawTerm, Failure] {
	if limits.MaxDepth <= 0 || limits.MaxTerms <= 0 || limits.MaxBytes <= 0 {
		return result.Err[RawTerm, Failure]{Err: Invalid{Area: "limits", Detail: "all limits must be positive"}}
	}
	if len(data) > limits.MaxBytes {
		return result.Err[RawTerm, Failure]{Err: LimitExceeded{Resource: "input bytes", Actual: len(data), Limit: limits.MaxBytes}}
	}
	if len(data) == 0 || data[0] != Version {
		return result.Err[RawTerm, Failure]{Err: MissingVersion{}}
	}
	decoder := &rawDecoder{data: data, at: 1, limits: limits}
	switch __gp_m0 := any(decoder.decodeTerm(0)).(type) {
	case result.Err[RawTerm, Failure]:
		failure := __gp_m0.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[RawTerm, Failure]:
		value := __gp_m0.Value

		if decoder.at != len(data) {
			return result.Err[RawTerm, Failure]{Err: TrailingBytes{Count: len(data) - decoder.at}}
		}
		return result.Ok[RawTerm, Failure]{Value: value}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) decodeTerm(depth int) result.Result[RawTerm, Failure] {
	if depth > decoder.limits.MaxDepth {
		return result.Err[RawTerm, Failure]{Err: LimitExceeded{Resource: "nesting depth", Actual: depth, Limit: decoder.limits.MaxDepth}}
	}
	decoder.terms++
	if decoder.terms > decoder.limits.MaxTerms {
		return result.Err[RawTerm, Failure]{Err: LimitExceeded{Resource: "term count", Actual: decoder.terms, Limit: decoder.limits.MaxTerms}}
	}
	switch __gp_m1 := any(decoder.byte()).(type) {
	case result.Err[byte, Failure]:
		failure := __gp_m1.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[byte, Failure]:
		tag := __gp_m1.Value

		return decoder.decodeTagged(tag, depth)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) decodeTagged(tag byte, depth int) result.Result[RawTerm, Failure] {
	switch tag {
	case 97:
		switch __gp_m2 := any(decoder.byte()).(type) {
		case result.Ok[byte, Failure]:
			value := __gp_m2.Value

			return result.Ok[RawTerm, Failure]{Value: RawInteger{Value: big.NewInt(int64(value))}}
		case result.Err[byte, Failure]:
			failure := __gp_m2.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 98:
		switch __gp_m3 := any(decoder.u32()).(type) {
		case result.Ok[uint32, Failure]:
			value := __gp_m3.Value

			return result.Ok[RawTerm, Failure]{Value: RawInteger{Value: big.NewInt(int64(int32(value)))}}
		case result.Err[uint32, Failure]:
			failure := __gp_m3.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 70:
		switch __gp_m4 := any(decoder.u64()).(type) {
		case result.Ok[uint64, Failure]:
			bits := __gp_m4.Value

			return result.Ok[RawTerm, Failure]{Value: RawFloat{Value: math.Float64frombits(bits)}}
		case result.Err[uint64, Failure]:
			failure := __gp_m4.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 99:
		return decoder.oldFloat()
	case 100, 118:
		switch __gp_m5 := any(decoder.u16()).(type) {
		case result.Ok[uint16, Failure]:
			length := __gp_m5.Value

			return decoder.atom(int(length))
		case result.Err[uint16, Failure]:
			failure := __gp_m5.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 115, 119:
		switch __gp_m6 := any(decoder.byte()).(type) {
		case result.Ok[byte, Failure]:
			length := __gp_m6.Value

			return decoder.atom(int(length))
		case result.Err[byte, Failure]:
			failure := __gp_m6.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 104:
		switch __gp_m7 := any(decoder.byte()).(type) {
		case result.Ok[byte, Failure]:
			arity := __gp_m7.Value

			return decoder.tuple(int(arity), depth)
		case result.Err[byte, Failure]:
			failure := __gp_m7.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 105:
		switch __gp_m8 := any(decoder.u32()).(type) {
		case result.Ok[uint32, Failure]:
			arity := __gp_m8.Value

			return decoder.tuple(int(arity), depth)
		case result.Err[uint32, Failure]:
			failure := __gp_m8.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 106:
		return result.Ok[RawTerm, Failure]{Value: RawNil{}}
	case 107:
		switch __gp_m9 := any(decoder.u16()).(type) {
		case result.Err[uint16, Failure]:
			failure := __gp_m9.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[uint16, Failure]:
			length := __gp_m9.Value

			switch __gp_m10 := any(decoder.take(int(length))).(type) {
			case result.Ok[[]byte, Failure]:
				raw := __gp_m10.Value

				return result.Ok[RawTerm, Failure]{Value: RawString{Text: string(raw)}}
			case result.Err[[]byte, Failure]:
				failure := __gp_m10.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 108:
		return decoder.list(depth)
	case 109:
		return decoder.binary(false)
	case 77:
		return decoder.binary(true)
	case 110:
		switch __gp_m11 := any(decoder.byte()).(type) {
		case result.Ok[byte, Failure]:
			length := __gp_m11.Value

			return decoder.bigInteger(int(length))
		case result.Err[byte, Failure]:
			failure := __gp_m11.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 111:
		switch __gp_m12 := any(decoder.u32()).(type) {
		case result.Ok[uint32, Failure]:
			length := __gp_m12.Value

			return decoder.bigInteger(int(length))
		case result.Err[uint32, Failure]:
			failure := __gp_m12.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 116:
		return decoder.mapValue(depth)
	case 103:
		return decoder.pid(depth, false)
	case 88:
		return decoder.pid(depth, true)
	case 102, 89, 120:
		return decoder.port(depth, tag)
	case 101, 114, 90:
		return decoder.reference(depth, tag)
	case 113:
		return decoder.exportValue(depth)
	case 80:
		return decoder.compressed(depth)
	case 112:
		switch __gp_m13 := any(decoder.u32()).(type) {
		case result.Err[uint32, Failure]:
			failure := __gp_m13.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[uint32, Failure]:
			size := __gp_m13.Value

			switch __gp_m14 := any(decoder.take(int(size))).(type) {
			case result.Ok[[]byte, Failure]:
				raw := __gp_m14.Value

				return result.Ok[RawTerm, Failure]{Value: RawOpaque{Tag: tag, Bytes: bytes.Clone(raw)}}
			case result.Err[[]byte, Failure]:
				failure := __gp_m14.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		return result.Err[RawTerm, Failure]{Err: UnsupportedTag{Tag: tag, Offset: decoder.at - 1}}
	}
}

func (decoder *rawDecoder) oldFloat() result.Result[RawTerm, Failure] {
	switch __gp_m15 := any(decoder.take(31)).(type) {
	case result.Err[[]byte, Failure]:
		failure := __gp_m15.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[[]byte, Failure]:
		raw := __gp_m15.Value

		var value float64
		_, scanError := fmt.Sscanf(string(bytes.TrimRight(raw, "\x00")), "%g", &value)
		switch __gp_m16 := any(result.Of(value, scanError)).(type) {
		case result.Ok[float64, error]:
			parsed := __gp_m16.Value

			return result.Ok[RawTerm, Failure]{Value: RawFloat{Value: parsed}}
		case result.Err[float64, error]:
			cause := __gp_m16.Err

			return result.Err[RawTerm, Failure]{Err: Foreign{Operation: "decode old float", Cause: cause}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) atom(length int) result.Result[RawTerm, Failure] {
	if length > 1020 {
		return result.Err[RawTerm, Failure]{Err: LimitExceeded{Resource: "atom bytes", Actual: length, Limit: 1020}}
	}
	switch __gp_m17 := any(decoder.take(length)).(type) {
	case result.Ok[[]byte, Failure]:
		raw := __gp_m17.Value

		return result.Ok[RawTerm, Failure]{Value: RawAtom{Name: string(raw)}}
	case result.Err[[]byte, Failure]:
		failure := __gp_m17.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) sequence(length int, depth int) result.Result[[]RawTerm, Failure] {
	if length < 0 || length > decoder.limits.MaxTerms {
		return result.Err[[]RawTerm, Failure]{Err: LimitExceeded{Resource: "sequence terms", Actual: length, Limit: decoder.limits.MaxTerms}}
	}
	elements := make([]RawTerm, length)
	for index := range elements {
		switch __gp_m18 := any(decoder.decodeTerm(depth + 1)).(type) {
		case result.Ok[RawTerm, Failure]:
			value := __gp_m18.Value

			elements[index] = value
		case result.Err[RawTerm, Failure]:
			failure := __gp_m18.Err

			return result.Err[[]RawTerm, Failure]{Err: failure}
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return result.Ok[[]RawTerm, Failure]{Value: elements}
}

func (decoder *rawDecoder) tuple(length int, depth int) result.Result[RawTerm, Failure] {
	switch __gp_m19 := any(decoder.sequence(length, depth)).(type) {
	case result.Ok[[]RawTerm, Failure]:
		elements := __gp_m19.Value

		return result.Ok[RawTerm, Failure]{Value: RawTuple{Elements: elements}}
	case result.Err[[]RawTerm, Failure]:
		failure := __gp_m19.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) list(depth int) result.Result[RawTerm, Failure] {
	switch __gp_m20 := any(decoder.u32()).(type) {
	case result.Err[uint32, Failure]:
		failure := __gp_m20.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[uint32, Failure]:
		length := __gp_m20.Value

		switch __gp_m21 := any(decoder.sequence(int(length), depth)).(type) {
		case result.Err[[]RawTerm, Failure]:
			failure := __gp_m21.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[[]RawTerm, Failure]:
			elements := __gp_m21.Value

			switch __gp_m22 := any(decoder.decodeTerm(depth + 1)).(type) {
			case result.Ok[RawTerm, Failure]:
				tail := __gp_m22.Value

				return result.Ok[RawTerm, Failure]{Value: RawList{Elements: elements, Tail: tail}}
			case result.Err[RawTerm, Failure]:
				failure := __gp_m22.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) binary(withBits bool) result.Result[RawTerm, Failure] {
	switch __gp_m23 := any(decoder.u32()).(type) {
	case result.Err[uint32, Failure]:
		failure := __gp_m23.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[uint32, Failure]:
		length := __gp_m23.Value

		bits := uint8(8)
		if withBits {
			switch __gp_m24 := any(decoder.byte()).(type) {
			case result.Err[byte, Failure]:
				failure := __gp_m24.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			case result.Ok[byte, Failure]:
				width := __gp_m24.Value

				if width == 0 || width > 8 {
					return result.Err[RawTerm, Failure]{Err: Invalid{Area: "bit-binary", Detail: fmt.Sprintf("tail width %d", width)}}
				}
				bits = width
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		switch __gp_m25 := any(decoder.take(int(length))).(type) {
		case result.Err[[]byte, Failure]:
			failure := __gp_m25.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[[]byte, Failure]:
			raw := __gp_m25.Value

			if withBits {
				return result.Ok[RawTerm, Failure]{Value: RawBitBinary{Bytes: bytes.Clone(raw), Bits: bits}}
			}
			return result.Ok[RawTerm, Failure]{Value: RawBinary{Bytes: bytes.Clone(raw)}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) bigInteger(length int) result.Result[RawTerm, Failure] {
	switch __gp_m26 := any(decoder.byte()).(type) {
	case result.Err[byte, Failure]:
		failure := __gp_m26.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[byte, Failure]:
		sign := __gp_m26.Value

		if sign > 1 {
			return result.Err[RawTerm, Failure]{Err: Invalid{Area: "big integer", Detail: fmt.Sprintf("sign %d", sign)}}
		}
		switch __gp_m27 := any(decoder.take(length)).(type) {
		case result.Err[[]byte, Failure]:
			failure := __gp_m27.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[[]byte, Failure]:
			little := __gp_m27.Value

			bigEndian := make([]byte, len(little))
			for index := range little {
				bigEndian[len(little)-1-index] = little[index]
			}
			value := new(big.Int).SetBytes(bigEndian)
			if sign == 1 {
				value.Neg(value)
			}
			return result.Ok[RawTerm, Failure]{Value: RawInteger{Value: value}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) mapValue(depth int) result.Result[RawTerm, Failure] {
	switch __gp_m28 := any(decoder.u32()).(type) {
	case result.Err[uint32, Failure]:
		failure := __gp_m28.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[uint32, Failure]:
		length := __gp_m28.Value

		if uint64(length) > uint64(decoder.limits.MaxTerms) {
			return result.Err[RawTerm, Failure]{Err: LimitExceeded{Resource: "map pairs", Actual: int(length), Limit: decoder.limits.MaxTerms}}
		}
		pairs := make([]RawPair, int(length))
		for index := range pairs {
			switch __gp_m29 := any(decoder.decodeTerm(depth + 1)).(type) {
			case result.Err[RawTerm, Failure]:
				failure := __gp_m29.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			case result.Ok[RawTerm, Failure]:
				key := __gp_m29.Value

				switch __gp_m30 := any(decoder.decodeTerm(depth + 1)).(type) {
				case result.Err[RawTerm, Failure]:
					failure := __gp_m30.Err

					return result.Err[RawTerm, Failure]{Err: failure}
				case result.Ok[RawTerm, Failure]:
					value := __gp_m30.Value

					pairs[index] = RawPair{Key: key, Value: value}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		return result.Ok[RawTerm, Failure]{Value: RawMap{Pairs: pairs}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) node(depth int) result.Result[string, Failure] {
	switch __gp_m31 := any(decoder.decodeTerm(depth + 1)).(type) {
	case result.Err[RawTerm, Failure]:
		failure := __gp_m31.Err

		return result.Err[string, Failure]{Err: failure}
	case result.Ok[RawTerm, Failure]:
		value := __gp_m31.Value

		switch __gp_m32 := any(value).(type) {
		case RawAtom:
			name := __gp_m32.Name

			return result.Ok[string, Failure]{Value: name}
		default:

			return result.Err[string, Failure]{Err: Invalid{Area: "node identity", Detail: "node must be an atom"}}
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) pid(depth int, modern bool) result.Result[RawTerm, Failure] {
	switch __gp_m33 := any(decoder.node(depth)).(type) {
	case result.Err[string, Failure]:
		failure := __gp_m33.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[string, Failure]:
		node := __gp_m33.Value

		switch __gp_m34 := any(decoder.u32()).(type) {
		case result.Err[uint32, Failure]:
			failure := __gp_m34.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[uint32, Failure]:
			id := __gp_m34.Value

			switch __gp_m35 := any(decoder.u32()).(type) {
			case result.Err[uint32, Failure]:
				failure := __gp_m35.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			case result.Ok[uint32, Failure]:
				serial := __gp_m35.Value

				switch __gp_m36 := any(decoder.creation(modern)).(type) {
				case result.Ok[uint32, Failure]:
					creation := __gp_m36.Value

					return result.Ok[RawTerm, Failure]{Value: RawPID{Identity: NodeIdentity{
						Node: node, ID: []uint32{id}, Serial: serial, Creation: creation,
					}}}
				case result.Err[uint32, Failure]:
					failure := __gp_m36.Err

					return result.Err[RawTerm, Failure]{Err: failure}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) port(depth int, tag byte) result.Result[RawTerm, Failure] {
	switch __gp_m37 := any(decoder.node(depth)).(type) {
	case result.Err[string, Failure]:
		failure := __gp_m37.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[string, Failure]:
		node := __gp_m37.Value

		var idResult result.Result[uint64, Failure]
		if tag == 120 {
			idResult = decoder.u64()
		} else {
			switch __gp_m38 := any(decoder.u32()).(type) {
			case result.Ok[uint32, Failure]:
				id := __gp_m38.Value

				idResult = result.Ok[uint64, Failure]{Value: uint64(id)}
			case result.Err[uint32, Failure]:
				failure := __gp_m38.Err

				idResult = result.Err[uint64, Failure]{Err: failure}
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		switch __gp_m39 := any(idResult).(type) {
		case result.Err[uint64, Failure]:
			failure := __gp_m39.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[uint64, Failure]:
			id := __gp_m39.Value

			switch __gp_m40 := any(decoder.creation(tag != 102)).(type) {
			case result.Ok[uint32, Failure]:
				creation := __gp_m40.Value

				return result.Ok[RawTerm, Failure]{Value: RawPort{Identity: NodeIdentity{
					Node: node, ID: []uint32{uint32(id), uint32(id >> 32)}, Creation: creation,
				}}}
			case result.Err[uint32, Failure]:
				failure := __gp_m40.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) reference(depth int, tag byte) result.Result[RawTerm, Failure] {
	if tag == 101 {
		switch __gp_m41 := any(decoder.node(depth)).(type) {
		case result.Err[string, Failure]:
			failure := __gp_m41.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[string, Failure]:
			node := __gp_m41.Value

			switch __gp_m42 := any(decoder.u32()).(type) {
			case result.Err[uint32, Failure]:
				failure := __gp_m42.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			case result.Ok[uint32, Failure]:
				id := __gp_m42.Value

				switch __gp_m43 := any(decoder.creation(false)).(type) {
				case result.Ok[uint32, Failure]:
					creation := __gp_m43.Value

					return result.Ok[RawTerm, Failure]{Value: RawReference{Identity: NodeIdentity{
						Node: node, ID: []uint32{id}, Creation: creation,
					}}}
				case result.Err[uint32, Failure]:
					failure := __gp_m43.Err

					return result.Err[RawTerm, Failure]{Err: failure}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	switch __gp_m44 := any(decoder.u16()).(type) {
	case result.Err[uint16, Failure]:
		failure := __gp_m44.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[uint16, Failure]:
		length := __gp_m44.Value

		switch __gp_m45 := any(decoder.node(depth)).(type) {
		case result.Err[string, Failure]:
			failure := __gp_m45.Err

			return result.Err[RawTerm, Failure]{Err: failure}
		case result.Ok[string, Failure]:
			node := __gp_m45.Value

			switch __gp_m46 := any(decoder.creation(tag == 90)).(type) {
			case result.Err[uint32, Failure]:
				failure := __gp_m46.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			case result.Ok[uint32, Failure]:
				creation := __gp_m46.Value

				ids := make([]uint32, int(length))
				for index := range ids {
					switch __gp_m47 := any(decoder.u32()).(type) {
					case result.Ok[uint32, Failure]:
						id := __gp_m47.Value

						ids[index] = id
					case result.Err[uint32, Failure]:
						failure := __gp_m47.Err

						return result.Err[RawTerm, Failure]{Err: failure}
					default:
						panic("goplus: impossible enum value in match")
					}
				}
				return result.Ok[RawTerm, Failure]{Value: RawReference{Identity: NodeIdentity{
					Node: node, ID: ids, Creation: creation,
				}}}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) exportValue(depth int) result.Result[RawTerm, Failure] {
	switch __gp_m48 := any(decoder.decodeTerm(depth + 1)).(type) {
	case result.Err[RawTerm, Failure]:
		failure := __gp_m48.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[RawTerm, Failure]:
		moduleTerm := __gp_m48.Value

		switch __gp_m49 := any(moduleTerm).(type) {
		case RawAtom:
			module := __gp_m49.Name

			switch __gp_m50 := any(decoder.decodeTerm(depth + 1)).(type) {
			case result.Err[RawTerm, Failure]:
				failure := __gp_m50.Err

				return result.Err[RawTerm, Failure]{Err: failure}
			case result.Ok[RawTerm, Failure]:
				functionTerm := __gp_m50.Value

				switch __gp_m51 := any(functionTerm).(type) {
				case RawAtom:
					function := __gp_m51.Name

					switch __gp_m52 := any(decoder.decodeTerm(depth + 1)).(type) {
					case result.Err[RawTerm, Failure]:
						failure := __gp_m52.Err

						return result.Err[RawTerm, Failure]{Err: failure}
					case result.Ok[RawTerm, Failure]:
						arityTerm := __gp_m52.Value

						switch __gp_m53 := any(arityTerm).(type) {
						case RawInteger:
							arity := __gp_m53.Value

							if arity.Sign() < 0 || !arity.IsUint64() || arity.Uint64() > uint64(^uint32(0)) {
								return result.Err[RawTerm, Failure]{Err: Invalid{Area: "export", Detail: "arity is not uint32"}}
							}
							return result.Ok[RawTerm, Failure]{Value: RawExport{Module: module, Function: function, Arity: uint32(arity.Uint64())}}
						default:

							return result.Err[RawTerm, Failure]{Err: Invalid{Area: "export", Detail: "arity is not an integer"}}
						}
					default:
						panic("goplus: impossible enum value in match")
					}
				default:

					return result.Err[RawTerm, Failure]{Err: Invalid{Area: "export", Detail: "function is not an atom"}}
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:

			return result.Err[RawTerm, Failure]{Err: Invalid{Area: "export", Detail: "module is not an atom"}}
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) compressed(depth int) result.Result[RawTerm, Failure] {
	switch __gp_m54 := any(decoder.u32()).(type) {
	case result.Err[uint32, Failure]:
		failure := __gp_m54.Err

		return result.Err[RawTerm, Failure]{Err: failure}
	case result.Ok[uint32, Failure]:
		expected := __gp_m54.Value

		if expected > uint32(decoder.limits.MaxBytes) {
			return result.Err[RawTerm, Failure]{Err: LimitExceeded{Resource: "compressed bytes", Actual: int(expected), Limit: decoder.limits.MaxBytes}}
		}
		readerValue, readerError := zlib.NewReader(bytes.NewReader(decoder.data[decoder.at:]))
		switch __gp_m55 := any(result.Of(readerValue, readerError)).(type) {
		case result.Err[io.ReadCloser, error]:
			cause := __gp_m55.Err

			return result.Err[RawTerm, Failure]{Err: Foreign{Operation: "open compressed stream", Cause: cause}}
		case result.Ok[io.ReadCloser, error]:
			reader := __gp_m55.Value

			defer reader.Close()
			rawValue, rawError := io.ReadAll(io.LimitReader(reader, int64(decoder.limits.MaxBytes)+1))
			switch __gp_m56 := any(result.Of(rawValue, rawError)).(type) {
			case result.Err[[]byte, error]:
				cause := __gp_m56.Err

				return result.Err[RawTerm, Failure]{Err: Foreign{Operation: "read compressed stream", Cause: cause}}
			case result.Ok[[]byte, error]:
				raw := __gp_m56.Value

				if len(raw) != int(expected) {
					return result.Err[RawTerm, Failure]{Err: Invalid{Area: "compressed size", Detail: fmt.Sprintf("header says %d, decoded %d", expected, len(raw))}}
				}
				decoder.at = len(decoder.data)
				nested := &rawDecoder{data: raw, limits: decoder.limits, terms: decoder.terms}
				switch __gp_m57 := any(nested.decodeTerm(depth + 1)).(type) {
				case result.Err[RawTerm, Failure]:
					failure := __gp_m57.Err

					return result.Err[RawTerm, Failure]{Err: failure}
				case result.Ok[RawTerm, Failure]:
					value := __gp_m57.Value

					if nested.at != len(raw) {
						return result.Err[RawTerm, Failure]{Err: TrailingBytes{Count: len(raw) - nested.at}}
					}
					decoder.terms = nested.terms
					return result.Ok[RawTerm, Failure]{Value: value}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) creation(modern bool) result.Result[uint32, Failure] {
	if modern {
		return decoder.u32()
	}
	switch __gp_m58 := any(decoder.byte()).(type) {
	case result.Ok[byte, Failure]:
		value := __gp_m58.Value

		return result.Ok[uint32, Failure]{Value: uint32(value)}
	case result.Err[byte, Failure]:
		failure := __gp_m58.Err

		return result.Err[uint32, Failure]{Err: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) byte() result.Result[byte, Failure] {
	switch __gp_m59 := any(decoder.take(1)).(type) {
	case result.Ok[[]byte, Failure]:
		raw := __gp_m59.Value

		return result.Ok[byte, Failure]{Value: raw[0]}
	case result.Err[[]byte, Failure]:
		failure := __gp_m59.Err

		return result.Err[byte, Failure]{Err: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) take(length int) result.Result[[]byte, Failure] {
	if length < 0 || decoder.at > len(decoder.data) || length > len(decoder.data)-decoder.at {
		return result.Err[[]byte, Failure]{Err: Truncated{Offset: decoder.at, Need: length}}
	}
	value := decoder.data[decoder.at : decoder.at+length]
	decoder.at += length
	return result.Ok[[]byte, Failure]{Value: value}
}

func (decoder *rawDecoder) u16() result.Result[uint16, Failure] {
	switch __gp_m60 := any(decoder.take(2)).(type) {
	case result.Ok[[]byte, Failure]:
		raw := __gp_m60.Value

		return result.Ok[uint16, Failure]{Value: binary.BigEndian.Uint16(raw)}
	case result.Err[[]byte, Failure]:
		failure := __gp_m60.Err

		return result.Err[uint16, Failure]{Err: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) u32() result.Result[uint32, Failure] {
	switch __gp_m61 := any(decoder.take(4)).(type) {
	case result.Ok[[]byte, Failure]:
		raw := __gp_m61.Value

		return result.Ok[uint32, Failure]{Value: binary.BigEndian.Uint32(raw)}
	case result.Err[[]byte, Failure]:
		failure := __gp_m61.Err

		return result.Err[uint32, Failure]{Err: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (decoder *rawDecoder) u64() result.Result[uint64, Failure] {
	switch __gp_m62 := any(decoder.take(8)).(type) {
	case result.Ok[[]byte, Failure]:
		raw := __gp_m62.Value

		return result.Ok[uint64, Failure]{Value: binary.BigEndian.Uint64(raw)}
	case result.Err[[]byte, Failure]:
		failure := __gp_m62.Err

		return result.Err[uint64, Failure]{Err: failure}
	default:
		panic("goplus: impossible enum value in match")
	}
}
