// Code generated by goplus from decode_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package etf

import (
	"testing"
	"testing/quick"

	"goforge.dev/goplus/std/result"
)

func TestDecodeTupleMapAndInteger(t *testing.T) {
	data := []byte{
		131, 104, 2,
		119, 2, 'o', 'k',
		116, 0, 0, 0, 1,
		119, 1, 'n',
		98, 0, 0, 0, 42,
	}
	switch __gp_m0 := any(Decode(data, DefaultLimits())).(type) {
	case result.Err[RawTerm, Failure]:
		failure := __gp_m0.Err

		t.Fatal(Error(failure))
	case result.Ok[RawTerm, Failure]:
		value := __gp_m0.Value

		switch __gp_m1 := any(value).(type) {
		case RawTuple:
			elements := __gp_m1.Elements

			if len(elements) != 2 {
				t.Fatalf("tuple length = %d", len(elements))
			}
			switch __gp_m2 := any(elements[1]).(type) {
			case RawMap:
				pairs := __gp_m2.Pairs

				if len(pairs) != 1 {
					t.Fatalf("map length = %d", len(pairs))
				}
				switch __gp_m3 := any(pairs[0].Value).(type) {
				case RawInteger:
					integer := __gp_m3.Value

					if integer.Int64() != 42 {
						t.Fatalf("integer = %s", integer.String())
					}
				default:

					t.Fatal("map value is not an integer")
				}
			default:

				t.Fatal("second tuple element is not a map")
			}
		default:

			t.Fatal("decoded value is not a tuple")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestSmallIntegerProperty(t *testing.T) {
	property := func(value uint8) bool {
		switch __gp_m4 := any(Decode([]byte{131, 97, value}, DefaultLimits())).(type) {
		case result.Ok[RawTerm, Failure]:
			decoded := __gp_m4.Value

			switch __gp_m5 := any(decoded).(type) {
			case RawInteger:
				integer := __gp_m5.Value

				return integer.Uint64() == uint64(value)
			default:

				return false
			}
		default:

			return false
		}
	}
	switch __gp_m6 := any(result.Of(true, quick.Check(property, nil))).(type) {
	case result.Err[bool, error]:
		cause := __gp_m6.Err

		t.Fatal(cause)
	case result.Ok[bool, error]:

	default:
		panic("goplus: impossible enum value in match")
	}
}

func FuzzDecodeNeverPanics(f *testing.F) {
	f.Add([]byte{131, 97, 1})
	f.Add([]byte{131, 104, 0})
	f.Fuzz(func(t *testing.T, data []byte) {
		limits := DefaultLimits()
		limits.MaxBytes = 1 << 20
		Decode(data, limits)
	})
}
