// Code generated by goplus from failure.gp. DO NOT EDIT.
//goplus:v v0.28.0

package etf

import (
	"fmt"

	"goforge.dev/gotp/term"
)

// Failure is the closed set of failures produced by ETF codecs. Keeping this
// algebra closed makes failure handling exhaustive in Go+ while the generated
// Go remains usable by ordinary Go tooling.
//
//goplus:enum Failure
type Failure interface{ isFailure() }

//goplus:variant (Failure) Invalid(Area string, Detail string)
type Invalid struct {
	Area   string
	Detail string
}

func (Invalid) isFailure() {}

//goplus:variant (Failure) LimitExceeded(Resource string, Actual int, Limit int)
type LimitExceeded struct {
	Resource string
	Actual   int
	Limit    int
}

func (LimitExceeded) isFailure() {}

//goplus:variant (Failure) MissingVersion()
type MissingVersion struct{}

func (MissingVersion) isFailure() {}

//goplus:variant (Failure) TrailingBytes(Count int)
type TrailingBytes struct {
	Count int
}

func (TrailingBytes) isFailure() {}

//goplus:variant (Failure) UnsupportedTag(Tag byte, Offset int)
type UnsupportedTag struct {
	Tag    byte
	Offset int
}

func (UnsupportedTag) isFailure() {}

//goplus:variant (Failure) Truncated(Offset int, Need int)
type Truncated struct {
	Offset int
	Need   int
}

func (Truncated) isFailure() {}

//goplus:variant (Failure) ResolverRequired()
type ResolverRequired struct{}

func (ResolverRequired) isFailure() {}

//goplus:variant (Failure) UnknownNodeID(ID uint32)
type UnknownNodeID struct {
	ID uint32
}

func (UnknownNodeID) isFailure() {}

//goplus:variant (Failure) UnknownNodeName(Name string)
type UnknownNodeName struct {
	Name string
}

func (UnknownNodeName) isFailure() {}

//goplus:variant (Failure) Foreign(Operation string, Cause error)
type Foreign struct {
	Operation string
	Cause     error
}

func (Foreign) isFailure() {}

//goplus:variant (Failure) TermRejected(Cause term.ValidationFailure)
type TermRejected struct {
	Cause term.ValidationFailure
}

func (TermRejected) isFailure() {}

// FailureCases selects one handler per Failure variant for FailureFold.
type FailureCases[R any] struct {
	Invalid          func(Area string, Detail string) R
	LimitExceeded    func(Resource string, Actual int, Limit int) R
	MissingVersion   func() R
	TrailingBytes    func(Count int) R
	UnsupportedTag   func(Tag byte, Offset int) R
	Truncated        func(Offset int, Need int) R
	ResolverRequired func() R
	UnknownNodeID    func(ID uint32) R
	UnknownNodeName  func(Name string) R
	Foreign          func(Operation string, Cause error) R
	TermRejected     func(Cause term.ValidationFailure) R
}

// FailureFold reduces Failure by one-level case analysis.
func FailureFold[R any](f Failure, cs FailureCases[R]) R {
	switch m := any(f).(type) {
	case Invalid:
		return cs.Invalid(m.Area, m.Detail)
	case LimitExceeded:
		return cs.LimitExceeded(m.Resource, m.Actual, m.Limit)
	case MissingVersion:
		return cs.MissingVersion()
	case TrailingBytes:
		return cs.TrailingBytes(m.Count)
	case UnsupportedTag:
		return cs.UnsupportedTag(m.Tag, m.Offset)
	case Truncated:
		return cs.Truncated(m.Offset, m.Need)
	case ResolverRequired:
		return cs.ResolverRequired()
	case UnknownNodeID:
		return cs.UnknownNodeID(m.ID)
	case UnknownNodeName:
		return cs.UnknownNodeName(m.Name)
	case Foreign:
		return cs.Foreign(m.Operation, m.Cause)
	case TermRejected:
		return cs.TermRejected(m.Cause)
	default:
		panic("goplus: impossible enum value in FailureFold")
	}
}

// FailureEqOverrides carries optional per-variant hooks for FailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FailureEqOverrides struct {
	Invalid          func(x, y Invalid) (eq, handled bool)
	LimitExceeded    func(x, y LimitExceeded) (eq, handled bool)
	MissingVersion   func(x, y MissingVersion) (eq, handled bool)
	TrailingBytes    func(x, y TrailingBytes) (eq, handled bool)
	UnsupportedTag   func(x, y UnsupportedTag) (eq, handled bool)
	Truncated        func(x, y Truncated) (eq, handled bool)
	ResolverRequired func(x, y ResolverRequired) (eq, handled bool)
	UnknownNodeID    func(x, y UnknownNodeID) (eq, handled bool)
	UnknownNodeName  func(x, y UnknownNodeName) (eq, handled bool)
	Foreign          func(x, y Foreign) (eq, handled bool)
	TermRejected     func(x, y TermRejected) (eq, handled bool)
}

// FailureEqualWith reports structural equality of a and b under ov.
func FailureEqualWith(a, b Failure, ov FailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case Invalid:
		y, ok := any(b).(Invalid)
		if !ok {
			return false
		}
		if ov.Invalid != nil {
			if eq, handled := ov.Invalid(x, y); handled {
				return eq
			}
		}
		if x.Area != y.Area {
			return false
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	case LimitExceeded:
		y, ok := any(b).(LimitExceeded)
		if !ok {
			return false
		}
		if ov.LimitExceeded != nil {
			if eq, handled := ov.LimitExceeded(x, y); handled {
				return eq
			}
		}
		if x.Resource != y.Resource {
			return false
		}
		if x.Actual != y.Actual {
			return false
		}
		if x.Limit != y.Limit {
			return false
		}
		return true
	case MissingVersion:
		y, ok := any(b).(MissingVersion)
		if !ok {
			return false
		}
		if ov.MissingVersion != nil {
			if eq, handled := ov.MissingVersion(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TrailingBytes:
		y, ok := any(b).(TrailingBytes)
		if !ok {
			return false
		}
		if ov.TrailingBytes != nil {
			if eq, handled := ov.TrailingBytes(x, y); handled {
				return eq
			}
		}
		if x.Count != y.Count {
			return false
		}
		return true
	case UnsupportedTag:
		y, ok := any(b).(UnsupportedTag)
		if !ok {
			return false
		}
		if ov.UnsupportedTag != nil {
			if eq, handled := ov.UnsupportedTag(x, y); handled {
				return eq
			}
		}
		if x.Tag != y.Tag {
			return false
		}
		if x.Offset != y.Offset {
			return false
		}
		return true
	case Truncated:
		y, ok := any(b).(Truncated)
		if !ok {
			return false
		}
		if ov.Truncated != nil {
			if eq, handled := ov.Truncated(x, y); handled {
				return eq
			}
		}
		if x.Offset != y.Offset {
			return false
		}
		if x.Need != y.Need {
			return false
		}
		return true
	case ResolverRequired:
		y, ok := any(b).(ResolverRequired)
		if !ok {
			return false
		}
		if ov.ResolverRequired != nil {
			if eq, handled := ov.ResolverRequired(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case UnknownNodeID:
		y, ok := any(b).(UnknownNodeID)
		if !ok {
			return false
		}
		if ov.UnknownNodeID != nil {
			if eq, handled := ov.UnknownNodeID(x, y); handled {
				return eq
			}
		}
		if x.ID != y.ID {
			return false
		}
		return true
	case UnknownNodeName:
		y, ok := any(b).(UnknownNodeName)
		if !ok {
			return false
		}
		if ov.UnknownNodeName != nil {
			if eq, handled := ov.UnknownNodeName(x, y); handled {
				return eq
			}
		}
		if x.Name != y.Name {
			return false
		}
		return true
	case Foreign:
		y, ok := any(b).(Foreign)
		if !ok {
			return false
		}
		if ov.Foreign != nil {
			if eq, handled := ov.Foreign(x, y); handled {
				return eq
			}
		}
		if x.Operation != y.Operation {
			return false
		}
		if (x.Cause == nil) != (y.Cause == nil) {
			return false
		}
		if x.Cause != nil && x.Cause.Error() != y.Cause.Error() {
			return false
		}
		return true
	case TermRejected:
		y, ok := any(b).(TermRejected)
		if !ok {
			return false
		}
		if ov.TermRejected != nil {
			if eq, handled := ov.TermRejected(x, y); handled {
				return eq
			}
		}
		if x.Cause != y.Cause {
			return false
		}
		return true
	}
	return false
}

// FailureEqual reports structural equality of a and b.
func FailureEqual(a, b Failure) bool {
	return FailureEqualWith(a, b, FailureEqOverrides{})
}

//goplus:method (Failure) Error
func Error(failure Failure) string {
	switch __gp_m0 := any(failure).(type) {
	case Invalid:
		area := __gp_m0.Area
		detail := __gp_m0.Detail

		return fmt.Sprintf("gotp/etf: invalid %s: %s", area, detail)
	case LimitExceeded:
		resource := __gp_m0.Resource
		actual := __gp_m0.Actual
		limit := __gp_m0.Limit

		return fmt.Sprintf("gotp/etf: %s size %d exceeds limit %d", resource, actual, limit)
	case MissingVersion:

		return fmt.Sprintf("gotp/etf: missing external term version %d", Version)
	case TrailingBytes:
		count := __gp_m0.Count

		return fmt.Sprintf("gotp/etf: %d trailing bytes", count)
	case UnsupportedTag:
		tag := __gp_m0.Tag
		offset := __gp_m0.Offset

		return fmt.Sprintf("gotp/etf: unsupported tag %d at byte %d", tag, offset)
	case Truncated:
		offset := __gp_m0.Offset
		need := __gp_m0.Need

		return fmt.Sprintf("gotp/etf: truncated input at byte %d; need %d bytes", offset, need)
	case ResolverRequired:

		return "gotp/etf: identifier requires a node resolver"
	case UnknownNodeID:
		id := __gp_m0.ID

		return fmt.Sprintf("gotp/etf: unknown node ID %d", id)
	case UnknownNodeName:
		name := __gp_m0.Name

		return fmt.Sprintf("gotp/etf: unknown node name %q", name)
	case Foreign:
		operation := __gp_m0.Operation
		cause := __gp_m0.Cause

		return fmt.Sprintf("gotp/etf: %s: %v", operation, cause)
	case TermRejected:
		cause := __gp_m0.Cause

		return fmt.Sprintf("gotp/etf: term rejected: %s", term.Error(cause))
	default:
		panic("goplus: impossible enum value in match")
	}
}
