// Code generated by goplus from code.gp. DO NOT EDIT.
//goplus:v v0.28.0

package beam

import (
	"encoding/binary"
	"fmt"
	"math/big"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
)

type Opcode struct {
	Number byte
	Name   string
	Arity  int
}

func LookupOpcode(number byte) option.Option[Opcode] {
	if number == 0 || int(number) >= len(generatedOpcodeTable) {
		return option.None[Opcode]{}
	}
	spec := generatedOpcodeTable[number]
	if spec.name == "" {
		return option.None[Opcode]{}
	}
	return option.Some[Opcode]{Value: Opcode{
		Number: number,
		Name:   spec.name,
		Arity:  int(spec.arity),
	}}
}

//goplus:enum OperandKind
type OperandKind interface{ isOperandKind() }

//goplus:variant (OperandKind) UnsignedKind()
type UnsignedKind struct{}

func (UnsignedKind) isOperandKind() {}

//goplus:variant (OperandKind) IntegerKind()
type IntegerKind struct{}

func (IntegerKind) isOperandKind() {}

//goplus:variant (OperandKind) AtomKind()
type AtomKind struct{}

func (AtomKind) isOperandKind() {}

//goplus:variant (OperandKind) XRegisterKind()
type XRegisterKind struct{}

func (XRegisterKind) isOperandKind() {}

//goplus:variant (OperandKind) YRegisterKind()
type YRegisterKind struct{}

func (YRegisterKind) isOperandKind() {}

//goplus:variant (OperandKind) LabelKind()
type LabelKind struct{}

func (LabelKind) isOperandKind() {}

//goplus:variant (OperandKind) CharacterKind()
type CharacterKind struct{}

func (CharacterKind) isOperandKind() {}

//goplus:variant (OperandKind) ListKind()
type ListKind struct{}

func (ListKind) isOperandKind() {}

//goplus:variant (OperandKind) FloatRegisterKind()
type FloatRegisterKind struct{}

func (FloatRegisterKind) isOperandKind() {}

//goplus:variant (OperandKind) AllocationListKind()
type AllocationListKind struct{}

func (AllocationListKind) isOperandKind() {}

//goplus:variant (OperandKind) LiteralKind()
type LiteralKind struct{}

func (LiteralKind) isOperandKind() {}

//goplus:variant (OperandKind) TypedRegisterKind()
type TypedRegisterKind struct{}

func (TypedRegisterKind) isOperandKind() {}

// OperandKindCases selects one handler per OperandKind variant for Fold.
type OperandKindCases[R any] struct {
	UnsignedKind       func() R
	IntegerKind        func() R
	AtomKind           func() R
	XRegisterKind      func() R
	YRegisterKind      func() R
	LabelKind          func() R
	CharacterKind      func() R
	ListKind           func() R
	FloatRegisterKind  func() R
	AllocationListKind func() R
	LiteralKind        func() R
	TypedRegisterKind  func() R
}

// Fold reduces OperandKind by one-level case analysis.
func Fold[R any](o OperandKind, cs OperandKindCases[R]) R {
	switch any(o).(type) {
	case UnsignedKind:
		return cs.UnsignedKind()
	case IntegerKind:
		return cs.IntegerKind()
	case AtomKind:
		return cs.AtomKind()
	case XRegisterKind:
		return cs.XRegisterKind()
	case YRegisterKind:
		return cs.YRegisterKind()
	case LabelKind:
		return cs.LabelKind()
	case CharacterKind:
		return cs.CharacterKind()
	case ListKind:
		return cs.ListKind()
	case FloatRegisterKind:
		return cs.FloatRegisterKind()
	case AllocationListKind:
		return cs.AllocationListKind()
	case LiteralKind:
		return cs.LiteralKind()
	case TypedRegisterKind:
		return cs.TypedRegisterKind()
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// OperandKindEqOverrides carries optional per-variant hooks for OperandKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type OperandKindEqOverrides struct {
	UnsignedKind       func(x, y UnsignedKind) (eq, handled bool)
	IntegerKind        func(x, y IntegerKind) (eq, handled bool)
	AtomKind           func(x, y AtomKind) (eq, handled bool)
	XRegisterKind      func(x, y XRegisterKind) (eq, handled bool)
	YRegisterKind      func(x, y YRegisterKind) (eq, handled bool)
	LabelKind          func(x, y LabelKind) (eq, handled bool)
	CharacterKind      func(x, y CharacterKind) (eq, handled bool)
	ListKind           func(x, y ListKind) (eq, handled bool)
	FloatRegisterKind  func(x, y FloatRegisterKind) (eq, handled bool)
	AllocationListKind func(x, y AllocationListKind) (eq, handled bool)
	LiteralKind        func(x, y LiteralKind) (eq, handled bool)
	TypedRegisterKind  func(x, y TypedRegisterKind) (eq, handled bool)
}

// OperandKindEqualWith reports structural equality of a and b under ov.
func OperandKindEqualWith(a, b OperandKind, ov OperandKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case UnsignedKind:
		y, ok := any(b).(UnsignedKind)
		if !ok {
			return false
		}
		if ov.UnsignedKind != nil {
			if eq, handled := ov.UnsignedKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case IntegerKind:
		y, ok := any(b).(IntegerKind)
		if !ok {
			return false
		}
		if ov.IntegerKind != nil {
			if eq, handled := ov.IntegerKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AtomKind:
		y, ok := any(b).(AtomKind)
		if !ok {
			return false
		}
		if ov.AtomKind != nil {
			if eq, handled := ov.AtomKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case XRegisterKind:
		y, ok := any(b).(XRegisterKind)
		if !ok {
			return false
		}
		if ov.XRegisterKind != nil {
			if eq, handled := ov.XRegisterKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case YRegisterKind:
		y, ok := any(b).(YRegisterKind)
		if !ok {
			return false
		}
		if ov.YRegisterKind != nil {
			if eq, handled := ov.YRegisterKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case LabelKind:
		y, ok := any(b).(LabelKind)
		if !ok {
			return false
		}
		if ov.LabelKind != nil {
			if eq, handled := ov.LabelKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CharacterKind:
		y, ok := any(b).(CharacterKind)
		if !ok {
			return false
		}
		if ov.CharacterKind != nil {
			if eq, handled := ov.CharacterKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ListKind:
		y, ok := any(b).(ListKind)
		if !ok {
			return false
		}
		if ov.ListKind != nil {
			if eq, handled := ov.ListKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FloatRegisterKind:
		y, ok := any(b).(FloatRegisterKind)
		if !ok {
			return false
		}
		if ov.FloatRegisterKind != nil {
			if eq, handled := ov.FloatRegisterKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AllocationListKind:
		y, ok := any(b).(AllocationListKind)
		if !ok {
			return false
		}
		if ov.AllocationListKind != nil {
			if eq, handled := ov.AllocationListKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case LiteralKind:
		y, ok := any(b).(LiteralKind)
		if !ok {
			return false
		}
		if ov.LiteralKind != nil {
			if eq, handled := ov.LiteralKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TypedRegisterKind:
		y, ok := any(b).(TypedRegisterKind)
		if !ok {
			return false
		}
		if ov.TypedRegisterKind != nil {
			if eq, handled := ov.TypedRegisterKind(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// OperandKindEqual reports structural equality of a and b.
func OperandKindEqual(a, b OperandKind) bool {
	return OperandKindEqualWith(a, b, OperandKindEqOverrides{})
}

type Allocation struct {
	Kind  uint64
	Count uint64
}

//goplus:enum Operand
//goplus:derive off
type Operand interface{ isOperand() }

//goplus:variant (Operand) UnsignedOperand(Value *big.Int)
type UnsignedOperand struct {
	Value *big.Int
}

func (UnsignedOperand) isOperand() {}

//goplus:variant (Operand) IntegerOperand(Value *big.Int)
type IntegerOperand struct {
	Value *big.Int
}

func (IntegerOperand) isOperand() {}

//goplus:variant (Operand) AtomOperand(Index *big.Int)
type AtomOperand struct {
	Index *big.Int
}

func (AtomOperand) isOperand() {}

//goplus:variant (Operand) XRegisterOperand(Index *big.Int)
type XRegisterOperand struct {
	Index *big.Int
}

func (XRegisterOperand) isOperand() {}

//goplus:variant (Operand) YRegisterOperand(Index *big.Int)
type YRegisterOperand struct {
	Index *big.Int
}

func (YRegisterOperand) isOperand() {}

//goplus:variant (Operand) LabelOperand(Index *big.Int)
type LabelOperand struct {
	Index *big.Int
}

func (LabelOperand) isOperand() {}

//goplus:variant (Operand) CharacterOperand(Value *big.Int)
type CharacterOperand struct {
	Value *big.Int
}

func (CharacterOperand) isOperand() {}

//goplus:variant (Operand) ListOperand(Items []Operand)
type ListOperand struct {
	Items []Operand
}

func (ListOperand) isOperand() {}

//goplus:variant (Operand) FloatRegisterOperand(Index *big.Int)
type FloatRegisterOperand struct {
	Index *big.Int
}

func (FloatRegisterOperand) isOperand() {}

//goplus:variant (Operand) AllocationListOperand(Allocations []Allocation)
type AllocationListOperand struct {
	Allocations []Allocation
}

func (AllocationListOperand) isOperand() {}

//goplus:variant (Operand) LiteralOperand(Index *big.Int)
type LiteralOperand struct {
	Index *big.Int
}

func (LiteralOperand) isOperand() {}

//goplus:variant (Operand) TypedRegisterOperand(Register Operand, TypeIndex uint64)
type TypedRegisterOperand struct {
	Register  Operand
	TypeIndex uint64
}

func (TypedRegisterOperand) isOperand() {}

//goplus:method (Operand) Kind
func Kind(operand Operand) OperandKind {
	switch any(operand).(type) {
	case UnsignedOperand:

		return UnsignedKind{}
	case IntegerOperand:

		return IntegerKind{}
	case AtomOperand:

		return AtomKind{}
	case XRegisterOperand:

		return XRegisterKind{}
	case YRegisterOperand:

		return YRegisterKind{}
	case LabelOperand:

		return LabelKind{}
	case CharacterOperand:

		return CharacterKind{}
	case ListOperand:

		return ListKind{}
	case FloatRegisterOperand:

		return FloatRegisterKind{}
	case AllocationListOperand:

		return AllocationListKind{}
	case LiteralOperand:

		return LiteralKind{}
	case TypedRegisterOperand:

		return TypedRegisterKind{}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:method (Operand) BigInteger
func BigInteger(operand Operand) option.Option[*big.Int] {
	switch __gp_m1 := any(operand).(type) {
	case UnsignedOperand:
		value := __gp_m1.Value

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	case IntegerOperand:
		value := __gp_m1.Value

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	case AtomOperand:
		value := __gp_m1.Index

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	case XRegisterOperand:
		value := __gp_m1.Index

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	case YRegisterOperand:
		value := __gp_m1.Index

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	case LabelOperand:
		value := __gp_m1.Index

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	case CharacterOperand:
		value := __gp_m1.Value

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	case FloatRegisterOperand:
		value := __gp_m1.Index

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	case LiteralOperand:
		value := __gp_m1.Index

		return option.Some[*big.Int]{Value: new(big.Int).Set(value)}
	default:

		return option.None[*big.Int]{}
	}
}

//goplus:method (Operand) Uint64
func Uint64(operand Operand) option.Option[uint64] {
	switch __gp_m2 := any(BigInteger(operand)).(type) {
	case option.None[*big.Int]:

		return option.None[uint64]{}
	case option.Some[*big.Int]:
		value := __gp_m2.Value

		if value.IsUint64() {
			return option.Some[uint64]{Value: value.Uint64()}
		}
		return option.None[uint64]{}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:method (Operand) Int64
func Int64(operand Operand) option.Option[int64] {
	switch __gp_m3 := any(BigInteger(operand)).(type) {
	case option.None[*big.Int]:

		return option.None[int64]{}
	case option.Some[*big.Int]:
		value := __gp_m3.Value

		if value.IsInt64() {
			return option.Some[int64]{Value: value.Int64()}
		}
		return option.None[int64]{}
	default:
		panic("goplus: impossible enum value in match")
	}
}

type Instruction struct {
	Offset   int
	Opcode   Opcode
	Operands []Operand
}

type CodeInfo struct {
	HeaderSize     uint32
	InstructionSet uint32
	OpcodeMax      uint32
	LabelCount     uint32
	FunctionCount  uint32
}

type DecodedCode struct {
	Info         CodeInfo
	Instructions []Instruction
}

type CodeDecodeLimits struct {
	MaxInstructions int
	MaxOperandDepth int
	MaxListItems    int
	MaxIntegerBytes int
}

func DefaultCodeDecodeLimits() CodeDecodeLimits {
	return CodeDecodeLimits{
		MaxInstructions: 1_000_000,
		MaxOperandDepth: 64,
		MaxListItems:    1_000_000,
		MaxIntegerBytes: 256,
	}
}

func (limits CodeDecodeLimits) normalized() CodeDecodeLimits {
	defaults := DefaultCodeDecodeLimits()
	if limits.MaxInstructions <= 0 {
		limits.MaxInstructions = defaults.MaxInstructions
	}
	if limits.MaxOperandDepth <= 0 {
		limits.MaxOperandDepth = defaults.MaxOperandDepth
	}
	if limits.MaxListItems <= 0 {
		limits.MaxListItems = defaults.MaxListItems
	}
	if limits.MaxIntegerBytes <= 0 {
		limits.MaxIntegerBytes = defaults.MaxIntegerBytes
	}
	return limits
}

func DecodeCodeChunk(
	chunk []byte,
	limits CodeDecodeLimits,
) result.Result[DecodedCode, Failure] {
	if len(chunk) < 20 {
		return result.Err[DecodedCode, Failure]{Err: Truncated{Part: "Code chunk"}}
	}
	info := CodeInfo{
		HeaderSize:     binary.BigEndian.Uint32(chunk[0:4]),
		InstructionSet: binary.BigEndian.Uint32(chunk[4:8]),
		OpcodeMax:      binary.BigEndian.Uint32(chunk[8:12]),
		LabelCount:     binary.BigEndian.Uint32(chunk[12:16]),
		FunctionCount:  binary.BigEndian.Uint32(chunk[16:20]),
	}
	if info.HeaderSize < 16 {
		return result.Err[DecodedCode, Failure]{Err: InvalidCodeHeader{}}
	}
	codeOffset64 := uint64(info.HeaderSize) + 4
	if codeOffset64 > uint64(len(chunk)) {
		return result.Err[DecodedCode, Failure]{Err: InvalidCodeHeader{}}
	}
	if info.InstructionSet != OpcodeFormatNumber {
		return result.Err[DecodedCode, Failure]{Err: UnsupportedInstructionSet{Found: info.InstructionSet, Supported: OpcodeFormatNumber}}
	}
	if info.OpcodeMax > uint32(generatedMaxOpcode) {
		return result.Err[DecodedCode, Failure]{Err: UnsupportedOpcode{Required: info.OpcodeMax, Supported: generatedMaxOpcode}}
	}
	switch __gp_m4 := any(DecodeInstructions(chunk[int(codeOffset64):], limits)).(type) {
	case result.Err[[]Instruction, Failure]:
		failure := __gp_m4.Err

		return result.Err[DecodedCode, Failure]{Err: failure}
	case result.Ok[[]Instruction, Failure]:
		instructions := __gp_m4.Value

		return result.Ok[DecodedCode, Failure]{Value: DecodedCode{
			Info: info, Instructions: instructions,
		}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func DecodeInstructions(
	code []byte,
	limits CodeDecodeLimits,
) result.Result[[]Instruction, Failure] {
	limits = limits.normalized()
	instructions := make([]Instruction, 0)
	position := 0
	for position < len(code) {
		if len(instructions) >= limits.MaxInstructions {
			return result.Err[[]Instruction, Failure]{Err: DecodeLimit{Name: "instruction", Limit: limits.MaxInstructions}}
		}
		offset := position
		number := code[position]
		position++
		var opcode Opcode
		switch __gp_m5 := any(LookupOpcode(number)).(type) {
		case option.None[Opcode]:

			return result.Err[[]Instruction, Failure]{Err: UnknownOpcode{Number: number, Offset: offset}}
		case option.Some[Opcode]:
			found := __gp_m5.Value

			opcode = found
		default:
			panic("goplus: impossible enum value in match")
		}
		operands := make([]Operand, opcode.Arity)
		for index := range operands {
			switch __gp_m6 := any(decodeOperand(code, &position, limits, 0)).(type) {
			case result.Err[Operand, Failure]:
				failure := __gp_m6.Err

				return result.Err[[]Instruction, Failure]{Err: InstructionOperandFailure{Opcode: opcode.Name, Index: index, Offset: position, Cause: failure}}
			case result.Ok[Operand, Failure]:
				operand := __gp_m6.Value

				operands[index] = operand
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		instructions = append(instructions, Instruction{
			Offset: offset, Opcode: opcode, Operands: operands,
		})
	}
	return result.Ok[[]Instruction, Failure]{Value: instructions}
}

type compactNumber struct {
	tag   byte
	value *big.Int
}

func decodeOperand(
	data []byte,
	position *int,
	limits CodeDecodeLimits,
	depth int,
) result.Result[Operand, Failure] {
	if depth >= limits.MaxOperandDepth {
		return result.Err[Operand, Failure]{Err: DecodeLimit{Name: "operand depth", Limit: limits.MaxOperandDepth}}
	}
	switch __gp_m7 := any(decodeCompactNumber(data, position, limits, depth)).(type) {
	case result.Err[compactNumber, Failure]:
		failure := __gp_m7.Err

		return result.Err[Operand, Failure]{Err: failure}
	case result.Ok[compactNumber, Failure]:
		compact := __gp_m7.Value

		switch compact.tag {
		case 0:
			return result.Ok[Operand, Failure]{Value: UnsignedOperand{Value: compact.value}}
		case 1:
			return result.Ok[Operand, Failure]{Value: IntegerOperand{Value: compact.value}}
		case 2:
			return result.Ok[Operand, Failure]{Value: AtomOperand{Index: compact.value}}
		case 3:
			return result.Ok[Operand, Failure]{Value: XRegisterOperand{Index: compact.value}}
		case 4:
			return result.Ok[Operand, Failure]{Value: YRegisterOperand{Index: compact.value}}
		case 5:
			return result.Ok[Operand, Failure]{Value: LabelOperand{Index: compact.value}}
		case 6:
			return result.Ok[Operand, Failure]{Value: CharacterOperand{Value: compact.value}}
		case 7:
			return decodeExtendedOperand(data, position, limits, depth+1, compact.value)
		default:
			return result.Err[Operand, Failure]{Err: MalformedCode{Detail: "invalid compact tag"}}
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func decodeExtendedOperand(
	data []byte,
	position *int,
	limits CodeDecodeLimits,
	depth int,
	extension *big.Int,
) result.Result[Operand, Failure] {
	if extension == nil || !extension.IsUint64() {
		return result.Err[Operand, Failure]{Err: MalformedCode{Detail: "extended operand tag is not unsigned"}}
	}
	switch extension.Uint64() {
	case 1:
		switch __gp_m8 := any(decodeUnsigned(data, position, limits, depth)).(type) {
		case result.Err[uint64, Failure]:
			failure := __gp_m8.Err

			return result.Err[Operand, Failure]{Err: failure}
		case result.Ok[uint64, Failure]:
			count := __gp_m8.Value

			if count > uint64(limits.MaxListItems) {
				return result.Err[Operand, Failure]{Err: DecodeLimit{Name: "list item", Limit: limits.MaxListItems}}
			}
			items := make([]Operand, int(count))
			for index := range items {
				switch __gp_m9 := any(decodeOperand(data, position, limits, depth)).(type) {
				case result.Err[Operand, Failure]:
					failure := __gp_m9.Err

					return result.Err[Operand, Failure]{Err: failure}
				case result.Ok[Operand, Failure]:
					item := __gp_m9.Value

					items[index] = item
				default:
					panic("goplus: impossible enum value in match")
				}
			}
			return result.Ok[Operand, Failure]{Value: ListOperand{Items: items}}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 2:
		switch __gp_m10 := any(decodeUnsigned(data, position, limits, depth)).(type) {
		case result.Err[uint64, Failure]:
			failure := __gp_m10.Err

			return result.Err[Operand, Failure]{Err: failure}
		case result.Ok[uint64, Failure]:
			index := __gp_m10.Value

			return result.Ok[Operand, Failure]{Value: FloatRegisterOperand{Index: new(big.Int).SetUint64(index)}}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 3:
		switch __gp_m11 := any(decodeUnsigned(data, position, limits, depth)).(type) {
		case result.Err[uint64, Failure]:
			failure := __gp_m11.Err

			return result.Err[Operand, Failure]{Err: failure}
		case result.Ok[uint64, Failure]:
			count := __gp_m11.Value

			if count > uint64(limits.MaxListItems) {
				return result.Err[Operand, Failure]{Err: DecodeLimit{Name: "allocation", Limit: limits.MaxListItems}}
			}
			allocations := make([]Allocation, int(count))
			for index := range allocations {
				var kind uint64
				switch __gp_m12 := any(decodeUnsigned(data, position, limits, depth)).(type) {
				case result.Err[uint64, Failure]:
					failure := __gp_m12.Err

					return result.Err[Operand, Failure]{Err: failure}
				case result.Ok[uint64, Failure]:
					value := __gp_m12.Value

					kind = value
				default:
					panic("goplus: impossible enum value in match")
				}
				var count uint64
				switch __gp_m13 := any(decodeUnsigned(data, position, limits, depth)).(type) {
				case result.Err[uint64, Failure]:
					failure := __gp_m13.Err

					return result.Err[Operand, Failure]{Err: failure}
				case result.Ok[uint64, Failure]:
					value := __gp_m13.Value

					count = value
				default:
					panic("goplus: impossible enum value in match")
				}
				if kind > 2 {
					return result.Err[Operand, Failure]{Err: MalformedCode{Detail: fmt.Sprintf("unknown allocation kind %d", kind)}}
				}
				allocations[index] = Allocation{Kind: kind, Count: count}
			}
			return result.Ok[Operand, Failure]{Value: AllocationListOperand{Allocations: allocations}}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 4:
		switch __gp_m14 := any(decodeUnsigned(data, position, limits, depth)).(type) {
		case result.Err[uint64, Failure]:
			failure := __gp_m14.Err

			return result.Err[Operand, Failure]{Err: failure}
		case result.Ok[uint64, Failure]:
			index := __gp_m14.Value

			return result.Ok[Operand, Failure]{Value: LiteralOperand{Index: new(big.Int).SetUint64(index)}}
		default:
			panic("goplus: impossible enum value in match")
		}
	case 5:
		var register Operand
		switch __gp_m15 := any(decodeOperand(data, position, limits, depth)).(type) {
		case result.Err[Operand, Failure]:
			failure := __gp_m15.Err

			return result.Err[Operand, Failure]{Err: failure}
		case result.Ok[Operand, Failure]:
			found := __gp_m15.Value

			register = found
		default:
			panic("goplus: impossible enum value in match")
		}
		switch any(register).(type) {
		case XRegisterOperand:

		case YRegisterOperand:

		default:

			return result.Err[Operand, Failure]{Err: MalformedCode{Detail: "typed operand does not contain a register"}}
		}
		switch __gp_m17 := any(decodeUnsigned(data, position, limits, depth)).(type) {
		case result.Err[uint64, Failure]:
			failure := __gp_m17.Err

			return result.Err[Operand, Failure]{Err: failure}
		case result.Ok[uint64, Failure]:
			typeIndex := __gp_m17.Value

			return result.Ok[Operand, Failure]{Value: TypedRegisterOperand{Register: register, TypeIndex: typeIndex}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		return result.Err[Operand, Failure]{Err: MalformedCode{Detail: "unknown extended operand tag " + extension.String()}}
	}
}

func decodeUnsigned(
	data []byte,
	position *int,
	limits CodeDecodeLimits,
	depth int,
) result.Result[uint64, Failure] {
	switch __gp_m18 := any(decodeCompactNumber(data, position, limits, depth)).(type) {
	case result.Err[compactNumber, Failure]:
		failure := __gp_m18.Err

		return result.Err[uint64, Failure]{Err: failure}
	case result.Ok[compactNumber, Failure]:
		compact := __gp_m18.Value

		if compact.tag != 0 || compact.value == nil || !compact.value.IsUint64() {
			return result.Err[uint64, Failure]{Err: MalformedCode{Detail: "expected unsigned compact value"}}
		}
		return result.Ok[uint64, Failure]{Value: compact.value.Uint64()}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func decodeCompactNumber(
	data []byte,
	position *int,
	limits CodeDecodeLimits,
	depth int,
) result.Result[compactNumber, Failure] {
	if *position >= len(data) {
		return result.Err[compactNumber, Failure]{Err: Truncated{Part: "compact value"}}
	}
	first := data[*position]
	*position++
	tag := first & 0x07
	if first&0x08 == 0 {
		return result.Ok[compactNumber, Failure]{Value: compactNumber{
			tag: tag, value: new(big.Int).SetUint64(uint64(first >> 4)),
		}}
	}
	if first&0x10 == 0 {
		if *position >= len(data) {
			return result.Err[compactNumber, Failure]{Err: Truncated{Part: "two-byte compact value"}}
		}
		value := uint64(first&0xe0)<<3 | uint64(data[*position])
		*position++
		return result.Ok[compactNumber, Failure]{Value: compactNumber{
			tag: tag, value: new(big.Int).SetUint64(value),
		}}
	}
	lengthCode := int(first >> 5)
	length := lengthCode + 2
	if lengthCode == 7 {
		if depth >= limits.MaxOperandDepth {
			return result.Err[compactNumber, Failure]{Err: DecodeLimit{Name: "compact length depth", Limit: limits.MaxOperandDepth}}
		}
		switch __gp_m19 := any(decodeUnsigned(data, position, limits, depth+1)).(type) {
		case result.Err[uint64, Failure]:
			failure := __gp_m19.Err

			return result.Err[compactNumber, Failure]{Err: failure}
		case result.Ok[uint64, Failure]:
			extra := __gp_m19.Value

			if extra > uint64(limits.MaxIntegerBytes) {
				return result.Err[compactNumber, Failure]{Err: DecodeLimit{Name: "compact integer byte", Limit: limits.MaxIntegerBytes}}
			}
			length = int(extra) + 9
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	if length > limits.MaxIntegerBytes {
		return result.Err[compactNumber, Failure]{Err: DecodeLimit{Name: "compact integer byte", Limit: limits.MaxIntegerBytes}}
	}
	if length > len(data)-*position {
		return result.Err[compactNumber, Failure]{Err: Truncated{Part: "compact integer"}}
	}
	raw := data[*position : *position+length]
	*position += length
	value := new(big.Int).SetBytes(raw)
	if tag == 1 && raw[0]&0x80 != 0 {
		modulus := new(big.Int).Lsh(big.NewInt(1), uint(length*8))
		value.Sub(value, modulus)
	}
	return result.Ok[compactNumber, Failure]{Value: compactNumber{tag: tag, value: value}}
}
