// Code generated by goplus from genserver.gp. DO NOT EDIT.
//goplus:v v0.28.0

package genserver

import (
	"fmt"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
	"goforge.dev/gotp/kernel"
	"goforge.dev/gotp/term"
)

var (
	callTag          = term.MustAtom("$gen_call")
	castTag          = term.MustAtom("$gen_cast")
	replyTag         = term.MustAtom("$gen_reply")
	callbackErrorTag = term.MustAtom("callback_error")
	normalReason     = term.MustAtom("normal")
	systemTag        = term.MustAtom("system")
	okReply          = term.MustAtom("ok")
	errorReply       = term.MustAtom("error")
)

//goplus:enum Failure
type Failure interface{ isFailure() }

//goplus:variant (Failure) InvalidConfiguration(Detail string)
type InvalidConfiguration struct {
	Detail string
}

func (InvalidConfiguration) isFailure() {}

//goplus:variant (Failure) ExpectedInt64(Found term.Kind)
type ExpectedInt64 struct {
	Found term.Kind
}

func (ExpectedInt64) isFailure() {}

//goplus:variant (Failure) Foreign(Operation string, Cause error)
type Foreign struct {
	Operation string
	Cause     error
}

func (Foreign) isFailure() {}

//goplus:variant (Failure) ServerUnavailable(Server term.PID)
type ServerUnavailable struct {
	Server term.PID
}

func (ServerUnavailable) isFailure() {}

//goplus:variant (Failure) KernelFailure(Cause kernel.Failure)
type KernelFailure struct {
	Cause kernel.Failure
}

func (KernelFailure) isFailure() {}

//goplus:variant (Failure) CallbackFailure(Detail string)
type CallbackFailure struct {
	Detail string
}

func (CallbackFailure) isFailure() {}

// FailureCases selects one handler per Failure variant for FailureFold.
type FailureCases[R any] struct {
	InvalidConfiguration func(Detail string) R
	ExpectedInt64        func(Found term.Kind) R
	Foreign              func(Operation string, Cause error) R
	ServerUnavailable    func(Server term.PID) R
	KernelFailure        func(Cause kernel.Failure) R
	CallbackFailure      func(Detail string) R
}

// FailureFold reduces Failure by one-level case analysis.
func FailureFold[R any](f Failure, cs FailureCases[R]) R {
	switch m := any(f).(type) {
	case InvalidConfiguration:
		return cs.InvalidConfiguration(m.Detail)
	case ExpectedInt64:
		return cs.ExpectedInt64(m.Found)
	case Foreign:
		return cs.Foreign(m.Operation, m.Cause)
	case ServerUnavailable:
		return cs.ServerUnavailable(m.Server)
	case KernelFailure:
		return cs.KernelFailure(m.Cause)
	case CallbackFailure:
		return cs.CallbackFailure(m.Detail)
	default:
		panic("goplus: impossible enum value in FailureFold")
	}
}

// FailureEqOverrides carries optional per-variant hooks for FailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FailureEqOverrides struct {
	InvalidConfiguration func(x, y InvalidConfiguration) (eq, handled bool)
	ExpectedInt64        func(x, y ExpectedInt64) (eq, handled bool)
	Foreign              func(x, y Foreign) (eq, handled bool)
	ServerUnavailable    func(x, y ServerUnavailable) (eq, handled bool)
	KernelFailure        func(x, y KernelFailure) (eq, handled bool)
	CallbackFailure      func(x, y CallbackFailure) (eq, handled bool)
}

// FailureEqualWith reports structural equality of a and b under ov.
func FailureEqualWith(a, b Failure, ov FailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case InvalidConfiguration:
		y, ok := any(b).(InvalidConfiguration)
		if !ok {
			return false
		}
		if ov.InvalidConfiguration != nil {
			if eq, handled := ov.InvalidConfiguration(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	case ExpectedInt64:
		y, ok := any(b).(ExpectedInt64)
		if !ok {
			return false
		}
		if ov.ExpectedInt64 != nil {
			if eq, handled := ov.ExpectedInt64(x, y); handled {
				return eq
			}
		}
		if x.Found != y.Found {
			return false
		}
		return true
	case Foreign:
		y, ok := any(b).(Foreign)
		if !ok {
			return false
		}
		if ov.Foreign != nil {
			if eq, handled := ov.Foreign(x, y); handled {
				return eq
			}
		}
		if x.Operation != y.Operation {
			return false
		}
		if (x.Cause == nil) != (y.Cause == nil) {
			return false
		}
		if x.Cause != nil && x.Cause.Error() != y.Cause.Error() {
			return false
		}
		return true
	case ServerUnavailable:
		y, ok := any(b).(ServerUnavailable)
		if !ok {
			return false
		}
		if ov.ServerUnavailable != nil {
			if eq, handled := ov.ServerUnavailable(x, y); handled {
				return eq
			}
		}
		if x.Server != y.Server {
			return false
		}
		return true
	case KernelFailure:
		y, ok := any(b).(KernelFailure)
		if !ok {
			return false
		}
		if ov.KernelFailure != nil {
			if eq, handled := ov.KernelFailure(x, y); handled {
				return eq
			}
		}
		if x.Cause != y.Cause {
			return false
		}
		return true
	case CallbackFailure:
		y, ok := any(b).(CallbackFailure)
		if !ok {
			return false
		}
		if ov.CallbackFailure != nil {
			if eq, handled := ov.CallbackFailure(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// FailureEqual reports structural equality of a and b.
func FailureEqual(a, b Failure) bool {
	return FailureEqualWith(a, b, FailureEqOverrides{})
}

//goplus:method (Failure) Error
func Error(failure Failure) string {
	switch __gp_m0 := any(failure).(type) {
	case InvalidConfiguration:
		detail := __gp_m0.Detail

		return "gotp/genserver: invalid configuration: " + detail
	case ExpectedInt64:
		found := __gp_m0.Found

		return fmt.Sprintf("gotp/genserver: expected int64; found %v", found)
	case Foreign:
		operation := __gp_m0.Operation
		cause := __gp_m0.Cause

		return fmt.Sprintf("gotp/genserver: %s: %v", operation, cause)
	case ServerUnavailable:
		server := __gp_m0.Server

		return fmt.Sprintf("gotp/genserver: server process %v does not exist", server)
	case KernelFailure:
		cause := __gp_m0.Cause

		return "gotp/genserver: " + kernel.FailureError(cause)
	case CallbackFailure:
		detail := __gp_m0.Detail

		return "gotp/genserver: callback failed: " + detail
	default:
		panic("goplus: impossible enum value in match")
	}
}

type Codec[T any] interface {
	Encode(T) result.Result[term.Term, Failure]
	Decode(term.Term) result.Result[T, Failure]
}

type CodecFuncs[T any] struct {
	EncodeFunc func(T) result.Result[term.Term, Failure]
	DecodeFunc func(term.Term) result.Result[T, Failure]
}

func (codec CodecFuncs[T]) Encode(value T) result.Result[term.Term, Failure] {
	if codec.EncodeFunc == nil {
		return result.Err[term.Term, Failure]{Err: InvalidConfiguration{Detail: "encode function is nil"}}
	}
	return codec.EncodeFunc(value)
}

func (codec CodecFuncs[T]) Decode(value term.Term) result.Result[T, Failure] {
	if codec.DecodeFunc == nil {
		return result.Err[T, Failure]{Err: InvalidConfiguration{Detail: "decode function is nil"}}
	}
	return codec.DecodeFunc(value)
}

type TermCodec struct{}

func (TermCodec) Encode(value term.Term) result.Result[term.Term, Failure] {
	return result.Ok[term.Term, Failure]{Value: term.Clone(value)}
}

func (TermCodec) Decode(value term.Term) result.Result[term.Term, Failure] {
	return result.Ok[term.Term, Failure]{Value: term.Clone(value)}
}

type Int64Codec struct{}

func (Int64Codec) Encode(value int64) result.Result[term.Term, Failure] {
	return result.Ok[term.Term, Failure]{Value: term.Integer(value)}
}

func (Int64Codec) Decode(value term.Term) result.Result[int64, Failure] {
	switch __gp_m1 := any(value).(type) {
	case term.IntegerTerm:
		integer := __gp_m1.Value

		if integer.IsInt64() {
			return result.Ok[int64, Failure]{Value: integer.Int64()}
		}
		return result.Err[int64, Failure]{Err: ExpectedInt64{Found: term.TermKind(value)}}
	default:

		return result.Err[int64, Failure]{Err: ExpectedInt64{Found: term.TermKind(value)}}
	}
}

//goplus:enum CallResult[State, Reply any]
type CallResult[State, Reply any] interface{ isCallResult(State, Reply) }

//goplus:variant (CallResult[State, Reply]) ContinueCall(ReplyValue Reply, StateValue State)
type ContinueCall[State any, Reply any] struct {
	ReplyValue Reply
	StateValue State
}

func (ContinueCall[State, Reply]) isCallResult(State, Reply) {}

//goplus:variant (CallResult[State, Reply]) StopCall(ReplyValue Reply, StateValue State, Reason term.Term)
type StopCall[State any, Reply any] struct {
	ReplyValue Reply
	StateValue State
	Reason     term.Term
}

func (StopCall[State, Reply]) isCallResult(State, Reply) {}

// CallResultCases selects one handler per CallResult variant for CallResultFold.
type CallResultCases[State, Reply any, R any] struct {
	ContinueCall func(ReplyValue Reply, StateValue State) R
	StopCall     func(ReplyValue Reply, StateValue State, Reason term.Term) R
}

// CallResultFold reduces CallResult[State, Reply] by one-level case analysis.
func CallResultFold[State, Reply any, R any](v CallResult[State, Reply], cs CallResultCases[State, Reply, R]) R {
	switch m := any(v).(type) {
	case ContinueCall[State, Reply]:
		return cs.ContinueCall(m.ReplyValue, m.StateValue)
	case StopCall[State, Reply]:
		return cs.StopCall(m.ReplyValue, m.StateValue, m.Reason)
	default:
		panic("goplus: impossible enum value in CallResultFold")
	}
}

//goplus:enum EventResult[State any]
type EventResult[State any] interface{ isEventResult(State) }

//goplus:variant (EventResult[State]) ContinueEvent(StateValue State)
type ContinueEvent[State any] struct {
	StateValue State
}

func (ContinueEvent[State]) isEventResult(State) {}

//goplus:variant (EventResult[State]) StopEvent(StateValue State, Reason term.Term)
type StopEvent[State any] struct {
	StateValue State
	Reason     term.Term
}

func (StopEvent[State]) isEventResult(State) {}

// EventResultCases selects one handler per EventResult variant for EventResultFold.
type EventResultCases[State any, R any] struct {
	ContinueEvent func(StateValue State) R
	StopEvent     func(StateValue State, Reason term.Term) R
}

// EventResultFold reduces EventResult[State] by one-level case analysis.
func EventResultFold[State any, R any](e EventResult[State], cs EventResultCases[State, R]) R {
	switch m := any(e).(type) {
	case ContinueEvent[State]:
		return cs.ContinueEvent(m.StateValue)
	case StopEvent[State]:
		return cs.StopEvent(m.StateValue, m.Reason)
	default:
		panic("goplus: impossible enum value in EventResultFold")
	}
}

type CallHandler[State, Request, Reply any] func(
	*kernel.Context,
	Request,
	State,
) result.Result[CallResult[State, Reply], Failure]

type CastHandler[State, Cast any] func(
	*kernel.Context,
	Cast,
	State,
) result.Result[EventResult[State], Failure]

type InfoHandler[State any] func(
	*kernel.Context,
	kernel.Signal,
	State,
) result.Result[EventResult[State], Failure]

type CodeChangeHandler[State any] func(
	OldVersion term.Term,
	StateValue State,
	Extra term.Term,
) result.Result[State, Failure]

//goplus:enum systemRequest
type systemRequest interface{ isSystemRequest() }

//goplus:variant (systemRequest) SystemSuspend()
type systemSuspend struct{}

func (systemSuspend) isSystemRequest() {}

//goplus:variant (systemRequest) SystemResume()
type systemResume struct{}

func (systemResume) isSystemRequest() {}

//goplus:variant (systemRequest) SystemChangeCode(Module term.Term, OldVersion term.Term, Extra term.Term)
type systemChangeCode struct {
	module     term.Term
	oldVersion term.Term
	extra      term.Term
}

func (systemChangeCode) isSystemRequest() {}

//goplus:variant (systemRequest) UnknownSystemRequest(Request term.Term)
type unknownSystemRequest struct {
	request term.Term
}

func (unknownSystemRequest) isSystemRequest() {}

// systemRequestCases selects one handler per systemRequest variant for systemRequestFold.
type systemRequestCases[R any] struct {
	SystemSuspend        func() R
	SystemResume         func() R
	SystemChangeCode     func(Module term.Term, OldVersion term.Term, Extra term.Term) R
	UnknownSystemRequest func(Request term.Term) R
}

// systemRequestFold reduces systemRequest by one-level case analysis.
func systemRequestFold[R any](s systemRequest, cs systemRequestCases[R]) R {
	switch m := any(s).(type) {
	case systemSuspend:
		return cs.SystemSuspend()
	case systemResume:
		return cs.SystemResume()
	case systemChangeCode:
		return cs.SystemChangeCode(m.module, m.oldVersion, m.extra)
	case unknownSystemRequest:
		return cs.UnknownSystemRequest(m.request)
	default:
		panic("goplus: impossible enum value in systemRequestFold")
	}
}

// systemRequestEqOverrides carries optional per-variant hooks for systemRequestEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type systemRequestEqOverrides struct {
	SystemSuspend        func(x, y systemSuspend) (eq, handled bool)
	SystemResume         func(x, y systemResume) (eq, handled bool)
	SystemChangeCode     func(x, y systemChangeCode) (eq, handled bool)
	UnknownSystemRequest func(x, y unknownSystemRequest) (eq, handled bool)
}

// systemRequestEqualWith reports structural equality of a and b under ov.
func systemRequestEqualWith(a, b systemRequest, ov systemRequestEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case systemSuspend:
		y, ok := any(b).(systemSuspend)
		if !ok {
			return false
		}
		if ov.SystemSuspend != nil {
			if eq, handled := ov.SystemSuspend(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case systemResume:
		y, ok := any(b).(systemResume)
		if !ok {
			return false
		}
		if ov.SystemResume != nil {
			if eq, handled := ov.SystemResume(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case systemChangeCode:
		y, ok := any(b).(systemChangeCode)
		if !ok {
			return false
		}
		if ov.SystemChangeCode != nil {
			if eq, handled := ov.SystemChangeCode(x, y); handled {
				return eq
			}
		}
		if x.module != y.module {
			return false
		}
		if x.oldVersion != y.oldVersion {
			return false
		}
		if x.extra != y.extra {
			return false
		}
		return true
	case unknownSystemRequest:
		y, ok := any(b).(unknownSystemRequest)
		if !ok {
			return false
		}
		if ov.UnknownSystemRequest != nil {
			if eq, handled := ov.UnknownSystemRequest(x, y); handled {
				return eq
			}
		}
		if x.request != y.request {
			return false
		}
		return true
	}
	return false
}

// systemRequestEqual reports structural equality of a and b.
func systemRequestEqual(a, b systemRequest) bool {
	return systemRequestEqualWith(a, b, systemRequestEqOverrides{})
}

type systemEnvelope struct {
	from    term.PID
	replyTo term.PID
	tag     term.Term
	request systemRequest
}

type Config[State, Request, Reply, Cast any] struct {
	InitialState State
	RequestCodec Codec[Request]
	ReplyCodec   Codec[Reply]
	CastCodec    Codec[Cast]
	HandleCall   CallHandler[State, Request, Reply]
	HandleCast   CastHandler[State, Cast]
	HandleInfo   InfoHandler[State]
	CodeChange   CodeChangeHandler[State]
}

type Server[State, Request, Reply, Cast any] struct {
	state        State
	requestCodec Codec[Request]
	replyCodec   Codec[Reply]
	castCodec    Codec[Cast]
	handleCall   CallHandler[State, Request, Reply]
	handleCast   CastHandler[State, Cast]
	handleInfo   InfoHandler[State]
	codeChange   CodeChangeHandler[State]
	suspended    bool
}

func New[State, Request, Reply, Cast any](
	config Config[State, Request, Reply, Cast],
) result.Result[*Server[State, Request, Reply, Cast], Failure] {
	if config.RequestCodec == nil || config.ReplyCodec == nil || config.CastCodec == nil {
		return result.Err[*Server[State, Request, Reply, Cast], Failure]{Err: InvalidConfiguration{Detail: "all codecs are required"}}
	}
	if config.HandleCall == nil || config.HandleCast == nil {
		return result.Err[*Server[State, Request, Reply, Cast], Failure]{Err: InvalidConfiguration{Detail: "call and cast handlers are required"}}
	}
	return result.Ok[*Server[State, Request, Reply, Cast], Failure]{Value: &Server[State, Request, Reply, Cast]{
		state: config.InitialState, requestCodec: config.RequestCodec,
		replyCodec: config.ReplyCodec, castCodec: config.CastCodec,
		handleCall: config.HandleCall, handleCast: config.HandleCast,
		handleInfo: config.HandleInfo, codeChange: config.CodeChange,
	}}
}

func (server *Server[State, Request, Reply, Cast]) Behavior() kernel.Behavior {
	return func(context *kernel.Context) kernel.StepResult {
		var accept func(kernel.Signal) bool
		if server.suspended {
			accept = func(signal kernel.Signal) bool { return option.IsSome(systemEnvelopeFromSignal(signal)) }
		}
		switch __gp_m2 := any(context.Receive(accept)).(type) {
		case option.None[kernel.Signal]:

			return kernel.Wait{}
		case option.Some[kernel.Signal]:
			signal := __gp_m2.Value

			switch __gp_m3 := any(server.system(context, signal)).(type) {
			case option.Some[kernel.StepResult]:
				transition := __gp_m3.Value
				return transition
			case option.None[kernel.StepResult]:
			default:
				panic("goplus: impossible enum value in match")
			}
			switch __gp_m4 := any(signal).(type) {
			case kernel.UserSignal:
				message := __gp_m4.Message

				switch __gp_m5 := any(taggedTuple(message, "$gen_call", 4)).(type) {
				case option.Some[[]term.Term]:
					values := __gp_m5.Value

					return server.call(context, signal, values)
				case option.None[[]term.Term]:

				default:
					panic("goplus: impossible enum value in match")
				}
				switch __gp_m6 := any(taggedTuple(message, "$gen_cast", 2)).(type) {
				case option.Some[[]term.Term]:
					values := __gp_m6.Value

					return server.cast(context, values)
				case option.None[[]term.Term]:

				default:
					panic("goplus: impossible enum value in match")
				}
			default:

			}
			return server.info(context, signal)
		default:
			panic("goplus: impossible enum value in match")
		}
	}
}

func (server *Server[State, Request, Reply, Cast]) State() State {
	return server.state
}

func (server *Server[State, Request, Reply, Cast]) Suspended() bool { return server.suspended }

// assayxport:unit gotp.otp.gen-server-system
func (server *Server[State, Request, Reply, Cast]) system(context *kernel.Context, signal kernel.Signal) option.Option[kernel.StepResult] {
	switch __gp_m7 := any(systemEnvelopeFromSignal(signal)).(type) {
	case option.None[systemEnvelope]:
		return option.None[kernel.StepResult]{}
	case option.Some[systemEnvelope]:
		envelope := __gp_m7.Value

		var response term.Term = okReply
		switch __gp_m8 := any(envelope.request).(type) {
		case systemSuspend:
			server.suspended = true
		case systemResume:
			server.suspended = false
		case systemChangeCode:
			oldVersion := __gp_m8.oldVersion
			extra := __gp_m8.extra

			if !server.suspended {
				response = systemFailure("not_suspended")
			} else {
				switch __gp_m9 := any(server.ChangeCode(oldVersion, extra)).(type) {
				case result.Err[State, Failure]:
					failure := __gp_m9.Err
					response = term.Tuple(errorReply, term.Binary([]byte(Error(failure))))
				case result.Ok[State, Failure]:
				default:
					panic("goplus: impossible enum value in match")
				}
			}
		case unknownSystemRequest:
			response = systemFailure("unknown_system_msg")
		default:
			panic("goplus: impossible enum value in match")
		}
		context.Send(envelope.replyTo, term.Tuple(term.Clone(envelope.tag), response))
		return option.Some[kernel.StepResult]{Value: kernel.Yield{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func systemEnvelopeFromSignal(signal kernel.Signal) option.Option[systemEnvelope] {
	switch __gp_m10 := any(signal).(type) {
	case kernel.UserSignal:
		from := __gp_m10.From
		message := __gp_m10.Message

		switch __gp_m11 := any(message).(type) {
		case term.TupleTerm:
			values := __gp_m11.Elements

			if len(values) != 3 || !term.Equal(values[0], systemTag) {
				return option.None[systemEnvelope]{}
			}
			switch __gp_m12 := any(values[1]).(type) {
			case term.TupleTerm:
				reply := __gp_m12.Elements

				if len(reply) != 2 {
					return option.None[systemEnvelope]{}
				}
				switch __gp_m13 := any(reply[0]).(type) {
				case term.PIDTerm:
					replyTo := __gp_m13.Value

					if replyTo != from {
						return option.None[systemEnvelope]{}
					}
					return option.Some[systemEnvelope]{Value: systemEnvelope{from: from, replyTo: replyTo, tag: term.Clone(reply[1]), request: systemRequestFromTerm(values[2])}}
				default:
					return option.None[systemEnvelope]{}
				}
			default:
				return option.None[systemEnvelope]{}
			}
		default:
			return option.None[systemEnvelope]{}
		}
	default:
		return option.None[systemEnvelope]{}
	}
}

func systemRequestFromTerm(request term.Term) systemRequest {
	switch __gp_m14 := any(request).(type) {
	case term.AtomTerm:
		name := __gp_m14.Name

		switch name {
		case "suspend":
			return systemSuspend{}
		case "resume":
			return systemResume{}
		}
	case term.TupleTerm:
		values := __gp_m14.Elements

		if len(values) == 4 && term.Equal(values[0], term.MustAtom("change_code")) {
			return systemChangeCode{module: term.Clone(values[1]), oldVersion: term.Clone(values[2]), extra: term.Clone(values[3])}
		}
	default:

	}
	return unknownSystemRequest{request: term.Clone(request)}
}

func systemFailure(reason string) term.Term { return term.Tuple(errorReply, term.MustAtom(reason)) }

// assayxport:unit gotp.otp.gen-server-code-change
func (server *Server[State, Request, Reply, Cast]) ChangeCode(
	oldVersion term.Term,
	extra term.Term,
) result.Result[State, Failure] {
	if server.codeChange == nil {
		return result.Err[State, Failure]{Err: InvalidConfiguration{Detail: "code_change callback is nil"}}
	}
	switch __gp_m15 := any(server.codeChange(term.Clone(oldVersion), server.state, term.Clone(extra))).(type) {
	case result.Err[State, Failure]:
		failure := __gp_m15.Err
		return result.Err[State, Failure]{Err: failure}
	case result.Ok[State, Failure]:
		state := __gp_m15.Value
		server.state = state
		return result.Ok[State, Failure]{Value: state}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (server *Server[State, Request, Reply, Cast]) call(
	context *kernel.Context,
	signal kernel.Signal,
	values []term.Term,
) kernel.StepResult {
	var caller term.PID
	switch __gp_m16 := any(values[1]).(type) {
	case term.PIDTerm:
		found := __gp_m16.Value

		caller = found
	default:

		return server.info(context, signal)
	}
	var reference term.Reference
	switch __gp_m17 := any(values[2]).(type) {
	case term.ReferenceTerm:
		found := __gp_m17.Value

		reference = found
	default:

		return server.info(context, signal)
	}
	switch __gp_m18 := any(signal).(type) {
	case kernel.UserSignal:
		from := __gp_m18.From

		if caller != from {
			return server.info(context, signal)
		}
	default:

		return server.info(context, signal)
	}
	switch __gp_m19 := any(server.requestCodec.Decode(values[3])).(type) {
	case result.Err[Request, Failure]:
		failure := __gp_m19.Err

		return kernel.Stop{Reason: callbackFailure(failure)}
	case result.Ok[Request, Failure]:
		request := __gp_m19.Value

		switch __gp_m20 := any(server.handleCall(context, request, server.state)).(type) {
		case result.Err[CallResult[State, Reply], Failure]:
			failure := __gp_m20.Err

			return kernel.Stop{Reason: callbackFailure(failure)}
		case result.Ok[CallResult[State, Reply], Failure]:
			decision := __gp_m20.Value

			return server.completeCall(context, caller, reference, decision)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (server *Server[State, Request, Reply, Cast]) completeCall(
	context *kernel.Context,
	caller term.PID,
	reference term.Reference,
	decision CallResult[State, Reply],
) kernel.StepResult {
	var reply Reply
	var transition kernel.StepResult
	switch __gp_m21 := any(decision).(type) {
	case ContinueCall[State, Reply]:
		value := __gp_m21.ReplyValue
		state := __gp_m21.StateValue

		reply = value
		server.state = state
		transition = kernel.Yield{}
	case StopCall[State, Reply]:
		value := __gp_m21.ReplyValue
		state := __gp_m21.StateValue
		reason := __gp_m21.Reason

		reply = value
		server.state = state
		transition = kernel.Stop{Reason: effectiveReason(reason)}
	default:
		panic("goplus: impossible enum value in match")
	}
	switch __gp_m22 := any(server.replyCodec.Encode(reply)).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m22.Err

		return kernel.Stop{Reason: callbackFailure(failure)}
	case result.Ok[term.Term, Failure]:
		encoded := __gp_m22.Value

		context.Send(caller, term.Tuple(replyTag, term.ReferenceTerm{Value: reference}, encoded))
		return transition
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (server *Server[State, Request, Reply, Cast]) cast(
	context *kernel.Context,
	values []term.Term,
) kernel.StepResult {
	switch __gp_m23 := any(server.castCodec.Decode(values[1])).(type) {
	case result.Err[Cast, Failure]:
		failure := __gp_m23.Err

		return kernel.Stop{Reason: callbackFailure(failure)}
	case result.Ok[Cast, Failure]:
		value := __gp_m23.Value

		switch __gp_m24 := any(server.handleCast(context, value, server.state)).(type) {
		case result.Err[EventResult[State], Failure]:
			failure := __gp_m24.Err

			return kernel.Stop{Reason: callbackFailure(failure)}
		case result.Ok[EventResult[State], Failure]:
			decision := __gp_m24.Value

			return server.applyEvent(decision)
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (server *Server[State, Request, Reply, Cast]) info(
	context *kernel.Context,
	signal kernel.Signal,
) kernel.StepResult {
	if server.handleInfo == nil {
		return kernel.Yield{}
	}
	switch __gp_m25 := any(server.handleInfo(context, signal, server.state)).(type) {
	case result.Err[EventResult[State], Failure]:
		failure := __gp_m25.Err

		return kernel.Stop{Reason: callbackFailure(failure)}
	case result.Ok[EventResult[State], Failure]:
		decision := __gp_m25.Value

		return server.applyEvent(decision)
	default:
		panic("goplus: impossible enum value in match")
	}
}

func (server *Server[State, Request, Reply, Cast]) applyEvent(
	decision EventResult[State],
) kernel.StepResult {
	switch __gp_m26 := any(decision).(type) {
	case ContinueEvent[State]:
		state := __gp_m26.StateValue

		server.state = state
		return kernel.Yield{}
	case StopEvent[State]:
		state := __gp_m26.StateValue
		reason := __gp_m26.Reason

		server.state = state
		return kernel.Stop{Reason: effectiveReason(reason)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func effectiveReason(reason term.Term) term.Term {
	switch any(reason).(type) {
	case term.InvalidTerm:

		return normalReason
	default:

		return reason
	}
}

func callbackFailure(failure Failure) term.Term {
	return term.Tuple(callbackErrorTag, term.Binary([]byte(Error(failure))))
}

//goplus:enum ClientMutation
type ClientMutation interface{ isClientMutation() }

//goplus:variant (ClientMutation) RequestSent()
type RequestSent struct{}

func (RequestSent) isClientMutation() {}

// ClientMutationCases selects one handler per ClientMutation variant for ClientMutationFold.
type ClientMutationCases[R any] struct {
	RequestSent func() R
}

// ClientMutationFold reduces ClientMutation by one-level case analysis.
func ClientMutationFold[R any](v ClientMutation, cs ClientMutationCases[R]) R {
	switch any(v).(type) {
	case RequestSent:
		return cs.RequestSent()
	default:
		panic("goplus: impossible enum value in ClientMutationFold")
	}
}

// ClientMutationEqOverrides carries optional per-variant hooks for ClientMutationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ClientMutationEqOverrides struct {
	RequestSent func(x, y RequestSent) (eq, handled bool)
}

// ClientMutationEqualWith reports structural equality of a and b under ov.
func ClientMutationEqualWith(a, b ClientMutation, ov ClientMutationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case RequestSent:
		y, ok := any(b).(RequestSent)
		if !ok {
			return false
		}
		if ov.RequestSent != nil {
			if eq, handled := ov.RequestSent(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ClientMutationEqual reports structural equality of a and b.
func ClientMutationEqual(a, b ClientMutation) bool {
	return ClientMutationEqualWith(a, b, ClientMutationEqOverrides{})
}

func Cast[Value any](
	context *kernel.Context,
	server term.PID,
	value Value,
	codec Codec[Value],
) result.Result[ClientMutation, Failure] {
	if codec == nil {
		return result.Err[ClientMutation, Failure]{Err: InvalidConfiguration{Detail: "cast codec is nil"}}
	}
	switch __gp_m28 := any(codec.Encode(value)).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m28.Err

		return result.Err[ClientMutation, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		encoded := __gp_m28.Value

		switch any(context.Send(server, term.Tuple(castTag, encoded))).(type) {
		case kernel.Delivered:

			return result.Ok[ClientMutation, Failure]{Value: RequestSent{}}
		case kernel.NoProcess:

			return result.Err[ClientMutation, Failure]{Err: ServerUnavailable{Server: server}}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func BeginCall[Request any](
	context *kernel.Context,
	server term.PID,
	request Request,
	codec Codec[Request],
) result.Result[term.Reference, Failure] {
	if codec == nil {
		return result.Err[term.Reference, Failure]{Err: InvalidConfiguration{Detail: "request codec is nil"}}
	}
	switch __gp_m30 := any(codec.Encode(request)).(type) {
	case result.Err[term.Term, Failure]:
		failure := __gp_m30.Err

		return result.Err[term.Reference, Failure]{Err: failure}
	case result.Ok[term.Term, Failure]:
		encoded := __gp_m30.Value

		switch __gp_m31 := any(context.Monitor(server)).(type) {
		case result.Err[term.Reference, kernel.Failure]:
			cause := __gp_m31.Err

			return result.Err[term.Reference, Failure]{Err: KernelFailure{Cause: cause}}
		case result.Ok[term.Reference, kernel.Failure]:
			reference := __gp_m31.Value

			context.Send(server, term.Tuple(
				callTag,
				term.PIDTerm{Value: context.Self()},
				term.ReferenceTerm{Value: reference},
				encoded,
			))
			return result.Ok[term.Reference, Failure]{Value: reference}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

//goplus:enum ReplyPoll[Reply any]
type ReplyPoll[Reply any] interface{ isReplyPoll(Reply) }

//goplus:variant (ReplyPoll[Reply]) Pending()
type Pending[Reply any] struct{}

func (Pending[Reply]) isReplyPoll(Reply) {}

//goplus:variant (ReplyPoll[Reply]) ReplyReceived(Value Reply)
type ReplyReceived[Reply any] struct {
	Value Reply
}

func (ReplyReceived[Reply]) isReplyPoll(Reply) {}

//goplus:variant (ReplyPoll[Reply]) ServerDown(Reason term.Term)
type ServerDown[Reply any] struct {
	Reason term.Term
}

func (ServerDown[Reply]) isReplyPoll(Reply) {}

// ReplyPollCases selects one handler per ReplyPoll variant for ReplyPollFold.
type ReplyPollCases[Reply any, R any] struct {
	Pending       func() R
	ReplyReceived func(Value Reply) R
	ServerDown    func(Reason term.Term) R
}

// ReplyPollFold reduces ReplyPoll[Reply] by one-level case analysis.
func ReplyPollFold[Reply any, R any](v ReplyPoll[Reply], cs ReplyPollCases[Reply, R]) R {
	switch m := any(v).(type) {
	case Pending[Reply]:
		return cs.Pending()
	case ReplyReceived[Reply]:
		return cs.ReplyReceived(m.Value)
	case ServerDown[Reply]:
		return cs.ServerDown(m.Reason)
	default:
		panic("goplus: impossible enum value in ReplyPollFold")
	}
}

func ReceiveReply[Reply any](
	context *kernel.Context,
	reference term.Reference,
	codec Codec[Reply],
) result.Result[ReplyPoll[Reply], Failure] {
	if codec == nil {
		return result.Err[ReplyPoll[Reply], Failure]{Err: InvalidConfiguration{Detail: "reply codec is nil"}}
	}
	received := context.Receive(func(signal kernel.Signal) bool {
		return replySignalFor(signal, reference)
	})
	switch __gp_m32 := any(received).(type) {
	case option.None[kernel.Signal]:

		return result.Ok[ReplyPoll[Reply], Failure]{Value: Pending[Reply]{}}
	case option.Some[kernel.Signal]:
		signal := __gp_m32.Value

		switch __gp_m33 := any(signal).(type) {
		case kernel.DownSignal:
			reason := __gp_m33.Reason

			return result.Ok[ReplyPoll[Reply], Failure]{Value: ServerDown[Reply]{Reason: reason}}
		case kernel.UserSignal:
			message := __gp_m33.Message

			switch __gp_m34 := any(taggedTuple(message, "$gen_reply", 3)).(type) {
			case option.None[[]term.Term]:

				return result.Ok[ReplyPoll[Reply], Failure]{Value: Pending[Reply]{}}
			case option.Some[[]term.Term]:
				values := __gp_m34.Value

				switch __gp_m35 := any(codec.Decode(values[2])).(type) {
				case result.Err[Reply, Failure]:
					failure := __gp_m35.Err

					return result.Err[ReplyPoll[Reply], Failure]{Err: failure}
				case result.Ok[Reply, Failure]:
					reply := __gp_m35.Value

					context.Demonitor(reference, true)
					return result.Ok[ReplyPoll[Reply], Failure]{Value: ReplyReceived[Reply]{Value: reply}}
				default:
					panic("goplus: impossible enum value in match")
				}
			default:
				panic("goplus: impossible enum value in match")
			}
		default:

			return result.Ok[ReplyPoll[Reply], Failure]{Value: Pending[Reply]{}}
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func replySignalFor(signal kernel.Signal, reference term.Reference) bool {
	switch __gp_m36 := any(signal).(type) {
	case kernel.DownSignal:
		found := __gp_m36.Reference

		return found == reference
	case kernel.UserSignal:
		message := __gp_m36.Message

		switch __gp_m37 := any(taggedTuple(message, "$gen_reply", 3)).(type) {
		case option.None[[]term.Term]:

			return false
		case option.Some[[]term.Term]:
			values := __gp_m37.Value

			switch __gp_m38 := any(values[1]).(type) {
			case term.ReferenceTerm:
				found := __gp_m38.Value

				return found == reference
			default:

				return false
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:

		return false
	}
}

func taggedTuple(
	value term.Term,
	tag string,
	length int,
) option.Option[[]term.Term] {
	switch __gp_m39 := any(value).(type) {
	case term.TupleTerm:
		values := __gp_m39.Elements

		if len(values) != length {
			return option.None[[]term.Term]{}
		}
		switch __gp_m40 := any(values[0]).(type) {
		case term.AtomTerm:
			name := __gp_m40.Name

			if name == tag {
				return option.Some[[]term.Term]{Value: values}
			}
		default:

		}
		return option.None[[]term.Term]{}
	default:

		return option.None[[]term.Term]{}
	}
}
