// Code generated by goplus from main_test.gp. DO NOT EDIT.
//goplus:v v0.28.0

package main

import (
	"testing"

	"goforge.dev/goplus/std/result"
)

func TestRunRequiresCommand(t *testing.T) {
	switch __gp_m0 := any(run([]string{})).(type) {
	case result.Err[CommandResult, Failure]:
		failure := __gp_m0.Err

		switch any(failure).(type) {
		case UsageFailure:

		default:

			t.Fatalf("failure = %s", Error(failure))
		}
	case result.Ok[CommandResult, Failure]:

		t.Fatal("empty command completed")
	default:
		panic("goplus: impossible enum value in match")
	}
}

func TestRunRejectsUnknownCommand(t *testing.T) {
	switch __gp_m2 := any(run([]string{"not-a-command"})).(type) {
	case result.Err[CommandResult, Failure]:
		failure := __gp_m2.Err

		switch any(failure).(type) {
		case UsageFailure:

		default:

			t.Fatalf("failure = %s", Error(failure))
		}
	case result.Ok[CommandResult, Failure]:

		t.Fatal("unknown command completed")
	default:
		panic("goplus: impossible enum value in match")
	}
}
